#define INTERFACE_QUANTITY				35
#define INTERFACE_CANNONS				0
#define INTERFACE_STORE					1
#define INTERFACE_SHIP_CHOOSE			2
#define INTERFACE_SHIPYARD				3
#define INTERFACE_CHARACTER				4
#define INTERFACE_MAINMENU				5
#define INTERFACE_SHIPHOLD				6
#define INTERFACE_HIRECREW				7
#define INTERFACE_PASSENGERS			8
#define INTERFACE_RANSACK_JOIN			9
#define INTERFACE_RANSACK_CREW			10
#define INTERFACE_RANSACK_CAPTAIN		11
#define INTERFACE_RANSACK_MAIN			12
#define INTERFACE_TRANSFER_MAIN			13
#define INTERFACE_TRANSFER_GOODS		14
#define INTERFACE_TRANSFER_CHARACTER	15
#define INTERFACE_TRANSFER_CREW			16
#define INTERFACE_ITEMS					17
#define INTERFACE_CHARACTER_SELECT		18
#define INTERFACE_QUESTBOOK				19
#define INTERFACE_TRADEBOOK				20
#define INTERFACE_NATIONRELATION		21
#define INTERFACE_SAVELOAD				22
#define INTERFACE_FORTCAPTURE			23
#define INTERFACE_ITEMSBOX				24
#define INTERFACE_HELPSCREEN			25
#define INTERFACE_OPTIONSCREEN			26
#define INTERFACE_SELECTMENU			27
#define INTERFACE_ITEMSTRADE			28
#define INTERFACE_CONTROLS				29
#define INTERFACE_PERKS					30
#define INTERFACE_SALARY				31
#define INTERFACE_PLAYGAME				32
#define INTERFACE_ENDGAME				33
#define INTERFACE_LANGUAGESET			34

#define RC_INTERFACE_DO_NOTHING			-1

// main menu exit codes
#define RC_INTERFACE_MAIN_MENU_EXIT				45000
#define RC_INTERFACE_DO_NEW_GAME				45001
#define RC_INTERFACE_DO_LOAD_GAME				45002
#define RC_INTERFACE_DO_SAVE_GAME				45003
#define RC_INTERFACE_DO_OPTIONS					45004
#define RC_INTERFACE_DO_CONTROLS				45005
#define RC_INTERFACE_DO_CREDITS					45006
#define RC_INTERFACE_DO_RESUME_GAME				45007
// common interface codes
#define RC_INTERFACE_RIGHT_CHANGE				45010
#define RC_INTERFACE_LEFT_CHANGE				45011
#define RC_INTERFACE_ERROR						45012
// other interfaces exit codes
#define RC_INTERFACE_STORE_EXIT					45020
#define RC_INTERFACE_CANNONS_EXIT				45021
#define RC_INTERFACE_CHARACTER_EXIT				45022
#define RC_INTERFACE_HIRECREW_EXIT				45023
#define RC_INTERFACE_SHIPSTATE_EXIT				45024
#define RC_INTERFACE_SHIPSTATE_OK				45025
#define RC_INTERFACE_SHIPHOLD_EXIT				45026
#define RC_INTERFACE_SHIPYARD_EXIT				45027
#define RC_INTERFACE_PASSENGERS_EXIT			45028
#define RC_INTERFACE_RANSACK_JOIN_EXIT			45029
#define RC_INTERFACE_RANSACK_CREW_EXIT			45030
#define RC_INTERFACE_RANSACK_CAPTAIN_EXIT		45031
#define RC_INTERFACE_RANSACK_MAIN_EXIT			45032
#define RC_INTERFACE_TRANSFER_MAIN_EXIT			45033
#define RC_INTERFACE_TRANSFER_MAIN_RETURN		45034
#define RC_INTERFACE_TRANSFER_START_GOODS		45035
#define RC_INTERFACE_TRANSFER_START_CHARACTERS	45036
#define RC_INTERFACE_TRANSFER_START_CREW		45037
#define RC_INTERFACE_CHARACTER_SELECT_EXIT		45038
#define RC_INTERFACE_TRADEBOOK_EXIT				45039
#define RC_INTERFACE_QUESTBOOK_EXIT				45040
#define RC_INTERFACE_NATIONRELATION_EXIT		45041
#define RC_INTERFACE_SAVELOAD_EXIT				45042
#define RC_INTERFACE_ITEMS_EXIT					45043
#define RC_INTERFACE_FORTCAPTURE_EXIT			45044
#define RC_INTERFACE_ITEMSBOX_EXIT				45045
#define RC_INTERFACE_HELPSCREEN_EXIT			45046
#define RC_INTERFACE_OPTIONSCREEN_EXIT			45047
#define RC_INTERFACE_SELECTMENU_EXIT			45048
#define RC_INTERFACE_ITEMSTRADE_EXIT			45049
#define RC_INTERFACE_CONTROLS_EXIT				45050
#define RC_INTERFACE_PERKS_EXIT					45051
#define RC_INTERFACE_SALARY_EXIT				45052
#define RC_INTERFACE_PLAYGAME_EXIT				45053
#define RC_INTERFACE_ENDGAME_EXIT				45054
#define RC_INTERFACE_LANGUAGESET_EXIT			45055

#define MAX_SAVE_STORE_BLOCKS	160

int	interfaceResultCommand;
object	GameInterface;
object	LanguageObject;
object  Interfaces[INTERFACE_QUANTITY];

// состояние интерфейса
object InterfaceStates;

extern void InitBaseInterfaces();
extern void InitBaseInterfaces_main();
