
int CreateConceicaoCharacters(int n)
{
	ref ch;

	makeref(ch,Characters[n]);			// Jacinto Arcibaldo Barreto (townhall)
	ch.name 	= "Jacinto";
	ch.middlename 	= "Arcibaldo";
	ch.lastname 	= "Barreto";
	ch.id		= "Jacinto Arcibaldo Barreto";
	ch.model = "huber_por";
	ch.sex = "man";
	ch.location	= "Conceicao_townhall";
	ch.location.group = "sit";
	ch.location.locator = "sit1";
	ch.Dialog.Filename = "Jacinto Arcibaldo Barreto_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "60";
	ch.experience = "0";
	ch.skill.Leadership = "6";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "5";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetHuberType(ch);
	LAi_RemoveLoginTime(ch);
	LAi_group_MoveCharacter(ch, "CONCEICAO_CITIZENS");
	ch.greeting = "Gr_Jacinto Arcibaldo Barreto";
	n = n + 1;

	makeref(ch,Characters[n]);			// Humberto de Paiva (shipyard)
	ch.name 	= "Humberto";
	ch.lastname 	= "de Paiva";
	ch.id		= "Humberto de Paiva";
	ch.model = "man6_1";
	ch.sex = "man";
	ch.location	= "Conceicao_shipyard";
	ch.location.group = "sit";
	ch.location.locator = "sit1";
	ch.Dialog.Filename = "Humberto de Paiva_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "60";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "5";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetHuberType(ch);
	LAi_SetLoginTime(ch, 6.0, 21.98333);
	LAi_group_MoveCharacter(ch, "CONCEICAO_CITIZENS");
	ch.greeting = "Gr_Humberto de Paiva";
	n = n + 1;

// Conceicao soldiers' IDs  are "Con_soldier_1", etc

//Location: Conceicao Pier (an entrance to the town from the pier)

    makeref(ch,Characters[n]);			//Soldier на входе в город
	ch.name 	= "Soldier";
	ch.lastname 	= " ";
	ch.id		= "Con_soldier_1";
	ch.model	= "soldier_por2";
	ch.sound_type = "soldier";
	ch.sex = "man";
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Conceicao_port";
	ch.location.group = "goto";
	ch.location.locator = "goto12";
	ch.Dialog.Filename = "Conceicao Soldier_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	GiveItem2Character(ch, BLADE_SABER);
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "CONCEICAO_SOLDIERS");
	LAi_CharacterReincarnation(ch, true, true);
	ch.greeting = "Gr_Conceicao Soldier";
	n = n + 1;

    makeref(ch,Characters[n]);			//Soldier на входе в город -- one more
	ch.name 	= "Soldier";
	ch.lastname 	= " ";
	ch.id		= "Con_soldier_2";
	ch.model	= "soldier_por";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sound_type = "soldier";
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Conceicao_port";
	ch.location.group = "goto";
	ch.location.locator = "goto13";
	ch.Dialog.Filename = "Conceicao Soldier_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "CONCEICAO_SOLDIERS");
	ch.greeting = "Gr_Conceicao Soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			//Patrol
	ch.name 	= "Soldier";
	ch.lastname 	= " ";
	ch.id		= "Con_patrol_1";
	ch.model	= "soldier_por3";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sound_type = "soldier";
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Conceicao_port";
	ch.location.group = "goto";
	ch.location.locator = "goto11";
	ch.Dialog.Filename = "Patrol_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "2";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "CONCEICAO_SOLDIERS");
	ch.greeting = "Gr_Patrol";
	n = n + 1;

	makeref(ch,Characters[n]);			//Patrol
	ch.name 	= "Soldier";
	ch.lastname 	= " ";
	ch.id		= "Con_patrol_2";
	ch.model	= "soldier_por4";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sound_type = "soldier";
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Conceicao_port";
	ch.location.group = "goto";
	ch.location.locator = "goto5";
	ch.Dialog.Filename = "Patrol_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "2";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "CONCEICAO_SOLDIERS");
	ch.greeting = "Gr_Patrol";
	n = n + 1;

	makeref(ch,Characters[n]);		//Maria Rivaldo -- towngirl3
	ch.name 	= "Maria";
	ch.lastname = "Rivaldo";
	ch.id		= "Maria Rivaldo";
	ch.model	= "towngirl3";
	ch.sex = "woman";
	ch.fanatic = "1";
	ch.church = "Conceicao_church";
	ch.church.loc = "goto3";
	ch.back.location = "Conceicao_port";
	ch.back.locator = "goto11";
	ch.sound_type = "female_citizen";
	ch.location	= "Conceicao_port";
	ch.location.group = "goto";
	ch.location.locator = "goto11";
	ch.Dialog.Filename = "Conceicao Citizen_dialog.c";
	ch.greeting = "Gr_Woman_English Citizen";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "CONCEICAO_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);		//Rodrigo Caldeira -- fisherman
	ch.name 	= "Rodrigo";
	ch.lastname = "Caldeira";
	ch.id		= "Rodrigo Caldeira";
	ch.model	= "fisherman";
	ch.sex = "man";
	ch.sound_type = "seaman";
	ch.location	= "Conceicao_port";
	ch.location.group = "goto";
	ch.location.locator = "goto5";
	ch.Dialog.Filename = "Conceicao Citizen_dialog.c";
	ch.greeting = "Gr_Conceicao Citizen";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "CONCEICAO_CITIZENS");
	n = n + 1;

    makeref(ch,Characters[n]);		//Aleixo Simos -- chelovek
	ch.name 	= "Aleixo";
	ch.lastname = "Simos";
	ch.id		= "Aleixo Simos";
	ch.model	= "chelovek";
	ch.sex = "man";
	ch.fanatic = "1";
	ch.church = "Conceicao_church";
	ch.church.loc = "goto4";
	ch.back.location = "Conceicao_port";
	ch.back.locator = "goto9";
	ch.sound_type = "male_citizen";
	ch.location	= "Conceicao_port";
	ch.location.group = "goto";
	ch.location.locator = "goto9";
	ch.Dialog.Filename = "Conceicao Citizen_dialog.c";
	ch.greeting = "Gr_Conceicao Citizen";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "CONCEICAO_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);		//Miguel Filho -- chameleon
	ch.name 	= "Miguel";
	ch.lastname = "Filho";
	ch.id		= "Miguel Filho";
	ch.model	= "chameleon";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	ch.location	= "Conceicao_port";
	ch.location.group = "goto";
	ch.location.locator = "goto4";
	ch.Dialog.Filename = "Conceicao Citizen_dialog.c";
	ch.greeting = "Gr_Conceicao Citizen";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "CONCEICAO_CITIZENS");
	n = n + 1;

// Conceicao town:

    makeref(ch,Characters[n]);		//Victor Barros -- old_man1
	ch.name 	= "Victor";
	ch.lastname = "Barros";
	ch.id		= "Victor Barros";
	ch.model	= "old_man2";
	ch.sex = "man";
	ch.fanatic = "1";
	ch.church = "Conceicao_church";
	ch.church.loc = "goto5";
	ch.back.location = "Conceicao_town";
	ch.back.locator = "goto1";
	ch.sound_type = "male_citizen";
	ch.location	= "Conceicao_town";
	ch.location.group = "goto";
	ch.location.locator = "goto1";
	ch.Dialog.Filename = "Conceicao Citizen_dialog.c";
	ch.greeting = "Gr_Conceicao Citizen";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "10";
	ch.money = "1";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "CONCEICAO_CITIZENS");
	n = n + 1;

    makeref(ch,Characters[n]);		//Paolo Milazar -- man5
	ch.name 	= "Paolo";
	ch.lastname = "Milazar";
	ch.id		= "Paolo Milazar";
	ch.model	= "man5";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	ch.location	= "Conceicao_town";
	ch.location.group = "goto";
	ch.location.locator = "goto12";
	ch.Dialog.Filename = "Conceicao Citizen_dialog.c";
	ch.greeting = "Gr_Conceicao Citizen";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "CONCEICAO_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			//Soldier near the entrance from port
	ch.name 	= "Soldier";
	ch.lastname 	= " ";
	ch.id		= "Con_soldier_3";
	ch.model	= "soldier_por5";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sound_type = "soldier";
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Conceicao_town";
	ch.location.group = "goto";
	ch.location.locator = "goto28";
	ch.Dialog.Filename = "Conceicao Soldier_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "CONCEICAO_SOLDIERS");
	ch.greeting = "Gr_Conceicao Soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			//Soldier near the entrance from port
	ch.name 	= "Soldier";
	ch.lastname 	= " ";
	ch.id		= "Con_soldier_4";
	ch.model	= "soldier_por6";
	ch.sound_type = "soldier";
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Conceicao_town";
	ch.location.group = "goto";
	ch.location.locator = "goto29";
	ch.Dialog.Filename = "Conceicao Soldier_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "CONCEICAO_SOLDIERS");
	ch.greeting = "Gr_Conceicao Soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			//Soldier near the residence
	ch.name 	= "Soldier";
	ch.lastname 	= " ";
	ch.id		= "Con_soldier_5";
	ch.model	= "soldier_por2";
	ch.sound_type = "soldier";
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Conceicao_town";
	ch.location.group = "goto";
	ch.location.locator = "goto21";
	ch.Dialog.Filename = "Conceicao Soldier_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "CONCEICAO_SOLDIERS");
	ch.greeting = "Gr_Conceicao Soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			//Soldier near the residence
	ch.name 	= "Soldier";
	ch.lastname 	= " ";
	ch.id		= "Con_soldier_6";
	ch.model	= "soldier_por2";
	ch.sound_type = "soldier";
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Conceicao_town";
	ch.location.group = "goto";
	ch.location.locator = "goto22";
	ch.Dialog.Filename = "Conceicao Soldier_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "CONCEICAO_SOLDIERS");
	ch.greeting = "Gr_Conceicao Soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			//Soldier near the entrance from jungle
	ch.name 	= "Soldier";
	ch.lastname 	= " ";
	ch.id		= "Con_soldier_7";
	ch.model	= "soldier_por6";
	ch.sound_type = "soldier";
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Conceicao_town";
	ch.location.group = "goto";
	ch.location.locator = "goto19";
	ch.Dialog.Filename = "Conceicao Soldier_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "CONCEICAO_SOLDIERS");
	ch.greeting = "Gr_Conceicao Soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			//Soldier near the entrance from jungle
	ch.name 	= "Soldier";
	ch.lastname 	= " ";
	ch.id		= "Con_soldier_8";
	ch.model	= "soldier_por3";
	ch.sound_type = "soldier";
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Conceicao_town";
	ch.location.group = "goto";
	ch.location.locator = "goto20";
	ch.Dialog.Filename = "Conceicao Soldier_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "CONCEICAO_SOLDIERS");
	ch.greeting = "Gr_Conceicao Soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			//Patrol
	ch.name 	= "Soldier";
	ch.lastname 	= " ";
	ch.id		= "Con_patrol_3";
	ch.model	= "soldier_por2";
	ch.sound_type = "soldier";
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Conceicao_town";
	ch.location.group = "goto";
	ch.location.locator = "goto13";
	ch.Dialog.Filename = "Patrol_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "2";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "CONCEICAO_SOLDIERS");
	ch.greeting = "Gr_Patrol";
	n = n + 1;

	makeref(ch,Characters[n]);			//Patrol
	ch.name 	= "Soldier";
	ch.lastname 	= " ";
	ch.id		= "Con_patrol_4";
	ch.model	= "soldier_por6";
	ch.sound_type = "soldier";
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Conceicao_port";
	ch.location.group = "goto";
	ch.location.locator = "goto18";
	ch.Dialog.Filename = "Patrol_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "2";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "CONCEICAO_SOLDIERS");
	ch.greeting = "Gr_Patrol";
	n = n + 1;

	makeref(ch,Characters[n]);			//Patrol
	ch.name 	= "Soldier";
	ch.lastname 	= " ";
	ch.id		= "Con_patrol_5";
	ch.model	= "soldier_por5";
	ch.sound_type = "soldier";
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Conceicao_port";
	ch.location.group = "goto";
	ch.location.locator = "goto9";
	ch.Dialog.Filename = "Patrol_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "2";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "CONCEICAO_SOLDIERS");
	ch.greeting = "Gr_Patrol";
	n = n + 1;

    makeref(ch,Characters[n]);		//Irene Torres -- towngirl2
	ch.name 	= "Irene";
	ch.lastname = "Torres";
	ch.id		= "Irene Torres";
	ch.model	= "towngirl7";
	ch.sex = "woman";
	ch.fanatic = "1";
	ch.church = "Conceicao_church";
	ch.church.loc = "goto6";
	ch.back.location = "Conceicao_town";
	ch.back.locator = "goto13";
	ch.sound_type = "female_citizen";
	ch.location	= "Conceicao_town";
	ch.location.group = "goto";
	ch.location.locator = "goto13";
	ch.Dialog.Filename = "Conceicao Citizen_dialog.c";
	ch.greeting = "Gr_Woman_English Citizen";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "CONCEICAO_CITIZENS");
	n = n + 1;

    makeref(ch,Characters[n]);		//Mateus Branco -- korsar
	ch.name 	= "Mateus";
	ch.lastname = "Branco";
	ch.id		= "Mateus Branco";
	ch.model	= "korsar";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	ch.location	= "Conceicao_town";
	ch.location.group = "goto";
	ch.location.locator = "goto18";
	ch.Dialog.Filename = "Conceicao Citizen_dialog.c";
	ch.greeting = "Gr_Conceicao Citizen";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "CONCEICAO_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);		//Beatriz Medeiros -- towngirl1
	ch.name 	= "Beatriz";
	ch.lastname = "Medeiros";
	ch.id		= "Beatriz Medeiros";
	ch.model	= "towngirl1";
	ch.sex = "woman";
	ch.fanatic = "1";
	ch.church = "Conceicao_church";
	ch.church.loc = "goto7";
	ch.back.location = "Conceicao_town";
	ch.back.locator = "goto9";
	ch.sound_type = "female_citizen";
	ch.location	= "Conceicao_town";
	ch.location.group = "goto";
	ch.location.locator = "goto9";
	ch.Dialog.Filename = "Conceicao Citizen_dialog.c";
	ch.greeting = "Gr_Woman_English Citizen";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "CONCEICAO_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);		//Henrique d'Allmeida -- man6
	ch.name 	= "Henrique";
	ch.lastname = "d'Allmeida";
	ch.id		= "Henrique d'Allmeida";
	ch.model	= "sailor2";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	ch.location	= "Conceicao_town";
	ch.location.group = "goto";
	ch.location.locator = "goto11";
	ch.Dialog.Filename = "Conceicao Citizen_dialog.c";
	ch.greeting = "Gr_Conceicao Citizen";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "CONCEICAO_CITIZENS");
	n = n + 1;

    makeref(ch,Characters[n]);		// Rodrigo Neves -- capitan
	ch.name 	= "Rodrigo";
	ch.lastname = "Neves";
	ch.id		= "Rodrigo Neves";
	ch.model	= "chelovek1";
	ch.sex = "man";
	ch.fanatic = "1";
	ch.church = "Conceicao_church";
	ch.church.loc = "goto8";
	ch.back.location = "Conceicao_town";
	ch.back.locator = "goto17";
	ch.sound_type = "seaman";
	ch.location	= "Conceicao_town";
	ch.location.group = "goto";
	ch.location.locator = "goto17";
	ch.Dialog.Filename = "Conceicao Citizen_dialog.c";
	ch.greeting = "Gr_Conceicao Citizen";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "CONCEICAO_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);		//  Padre Valentim -- Monk
	ch.name 	= "Padre";
	ch.lastname = "Valentim";
	ch.id		= "Padre Valentim";
	ch.model	= "Monk";
	ch.sex = "man";
	ch.sound_type = "priest";
	ch.location	= "Conceicao_church";
	ch.location.group = "goto";
	ch.location.locator = "goto11";
	ch.Dialog.Filename = "Padre Valentim_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetPriestType(ch);
	LAi_group_MoveCharacter(ch, "CONCEICAO_CITIZENS");
	ch.greeting = "Gr_Padre Valentim";
	n = n + 1;

// Conceicao_Tavern:
    makeref(ch,Characters[n]);		//Duarte Correja -- tavern-keeper
	ch.name 	= "Duarte";
	ch.lastname = "Correja";
	ch.id		= "Duarte Correja";
	ch.model	= "man2";
	ch.sex = "man";
	ch.location	= "Conceicao_tavern";
	ch.location.group = "merchant";
	ch.location.locator = "goto1";
	ch.Dialog.Filename = "Duarte Correja_dialog.c";
	ch.greeting = "Gr_Duarte Correja";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.work = "";
	ch.money = "1";
	LAi_SetBarmanType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_group_MoveCharacter(ch, "CONCEICAO_CITIZENS");
	n = n + 1;

    makeref(ch,Characters[n]);		// Laurenco Costa -- fisherman
	ch.name 	= "Laurenco";
	ch.lastname = "Costa";
	ch.id		= "Laurenco Costa";
	ch.model	= "shkiper";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	ch.location	= "Conceicao_tavern";
	ch.location.group = "sit";
	ch.location.locator = "sit1";
	ch.Dialog.Filename = "Habitue_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	ch.quest.last_theme = "";
	LAi_SetSitType(ch);
	LAi_group_MoveCharacter(ch, "CONCEICAO_CITIZENS");
	n = n + 1;


    makeref(ch,Characters[n]);		// Carlos Resende -- fatman
	ch.name 	= "Carlos";
	ch.lastname = "Resende";
	ch.id		= "Carlos Resende";
	ch.model	= "fatman";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	ch.location	= "Conceicao_tavern";
	ch.location.group = "sit";
	ch.location.locator = "sit7";
	ch.Dialog.Filename = "Habitue_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	ch.quest.last_theme = "";
	LAi_SetSitType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_group_MoveCharacter(ch, "CONCEICAO_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);		// Conceicao_officiant
	ch.name 	= "Helena";
	ch.lastname = "Azocar";
	ch.id		= "Conceicao_officiant";
	ch.model	= "towngirl2";
	ch.sex = "woman";
	ch.sound_type = "female_citizen";
	ch.location	= "Conceicao_tavern";
	ch.location.group = "goto";
	ch.location.locator = "goto3";
	ch.Dialog.Filename = "Eng_Officiant_dialog.c";
	ch.greeting = "Gr_eng_officiant";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	ch.quest.sex = 0;
	ch.sex.time = 0;
	LAi_SetWaitressType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_group_MoveCharacter(ch, "CONCEICAO_CITIZENS");
	n = n + 1;

// Conceicao_Store:

    makeref(ch,Characters[n]);		// Martinho Guterres --
	ch.name 	= "Martinho";
	ch.lastname = "Guterres";
	ch.id		= "Martinho Guterres";
	ch.model	= "storeman";
	ch.sex = "man";
	ch.location	= "Conceicao_Store";
	ch.location.group = "sit";
	ch.location.locator = "sit1";
	ch.Dialog.Filename = "Martinho Guterres_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	ch.quest.trade_date = "";
	ch.quest.item_date = "";
	LAi_SetStayType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_group_MoveCharacter(ch, "CONCEICAO_CITIZENS");
	ch.greeting = "Gr_Martinho Guterres";
	n = n + 1;

// Smugglers_Lair:

	makeref(ch,Characters[n]);		//  Tomaz Cid -- Black_Corsair
	ch.name 	= "Tomaz";
	ch.lastname = "Cid";
	ch.id		= "Tomaz Cid";
	ch.model	= "man1_2";
	ch.sex = "man";
	ch.sound_type = "soldier";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Smugglers_Lair";
	ch.location.group = "goto";
	ch.location.locator = "character12";
	ch.Dialog.Filename = "smugglers citizen_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SMUGGLERS_SOLDIERS");
	n = n + 1;

	makeref(ch,Characters[n]);		//  Aristides Chiamulera -- man5
	ch.name 	= "Aristides";
	ch.lastname = "Chiamulera";
	ch.id		= "Aristides Chiamuler";
	ch.model	= "korsar";
	ch.sex = "man";
	ch.sound_type = "soldier";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Smugglers_Lair";
	ch.location.group = "goto";
	ch.location.locator = "character2";
	ch.Dialog.Filename = "smugglers citizen_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SMUGGLERS_SOLDIERS");
	n = n + 1;

	makeref(ch,Characters[n]);		//  Francisco Baia -- chameleon
	ch.name 	= "Francisco";
	ch.lastname = "Baia";
	ch.id		= "Francisco Baia";
	ch.model	= "chameleon";
	ch.sex = "man";
	ch.act.sound_type = "pirate";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Smugglers_Lair";
	ch.location.group = "goto";
	ch.location.locator = "goto20";
	ch.Dialog.Filename = "smugglers citizen_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetWarriorType(ch);
	LAi_warrior_DialogEnable(ch, true);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SMUGGLERS_SOLDIERS");
	n = n + 1;

	makeref(ch,Characters[n]);		//  Eloi Labat -- mongol
	ch.name 	= "Eloi";
	ch.lastname = "Labat";
	ch.id		= "Eloi Labat";
	ch.model	= "mongol";
	ch.sex = "man";
	ch.act.sound_type = "pirate";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Smugglers_Lair";
	ch.location.group = "goto";
	ch.location.locator = "goto25";
	ch.Dialog.Filename = "smugglers citizen_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetWarriorType(ch);
	LAi_warrior_DialogEnable(ch, true);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SMUGGLERS_SOLDIERS");
	n = n + 1;

	makeref(ch,Characters[n]);		//  Paolo Jardim -- fatman
	ch.name 	= "Paolo";
	ch.lastname = "Jardim";
	ch.id		= "Paolo Jardim";
	ch.model	= "fatman";
	ch.sex = "man";
	ch.act.sound_type = "pirate";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Smugglers_Lair";
	ch.location.group = "goto";
	ch.location.locator = "goto15";
	ch.Dialog.Filename = "smugglers citizen_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetWarriorType(ch);
	LAi_warrior_DialogEnable(ch, true);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SMUGGLERS_SOLDIERS");
	n = n + 1;

	makeref(ch,Characters[n]);		//  Valentim Ribeiro -- bocman
	ch.name 	= "Valentim";
	ch.lastname = "Ribeiro";
	ch.id		= "Valentim Ribeiro";
	ch.model	= "bocman";
	ch.sex = "man";
	ch.act.sound_type = "pirate";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Smugglers_Lair";
	ch.location.group = "goto";
	ch.location.locator = "goto23";
	ch.Dialog.Filename = "smugglers citizen_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetWarriorType(ch);
	LAi_warrior_DialogEnable(ch, true);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SMUGGLERS_SOLDIERS");
	n = n + 1;

	makeref(ch,Characters[n]);		//  Nuno Abrao -- corsair2
	ch.name 	= "Nuno";
	ch.lastname = "Abrao";
	ch.id		= "Nuno Abrao";
	ch.model	= "corsair2";
	ch.sex = "man";
	ch.act.sound_type = "pirate";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Smugglers_Lair";
	ch.location.group = "goto";
	ch.location.locator = "goto9";
	ch.Dialog.Filename = "smugglers citizen_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetWarriorType(ch);
	LAi_warrior_DialogEnable(ch, true);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SMUGGLERS_SOLDIERS");
	n = n + 1;

	makeref(ch,Characters[n]);		//  Emilio Guerra -- capitan
	ch.name 	= "Emilio";
	ch.lastname = "Guerra";
	ch.id		= "Emilio Guerra";
	ch.model	= "capitan";
	ch.sex = "man";
	ch.act.sound_type = "pirate";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Smugglers_Lair";
	ch.location.group = "goto";
	ch.location.locator = "goto6";
	ch.Dialog.Filename = "smugglers citizen_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetWarriorType(ch);
	LAi_warrior_DialogEnable(ch, true);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SMUGGLERS_SOLDIERS");
	n = n + 1;

	makeref(ch,Characters[n]);		//  Pascoal Labat -- man2
	ch.name 	= "Pascoal";
	ch.lastname = "Labat";
	ch.id		= "Pascoal Labat";
	ch.model	= "man2";
	ch.sex = "man";
	ch.act.type = "soldier";
	ch.act.soundtype = "pirate";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Smugglers_Lair";
	ch.location.group = "goto";
	ch.location.locator = "goto6";
	ch.Dialog.Filename = "Patrol_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetWarriorType(ch);
	LAi_warrior_DialogEnable(ch, true);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SMUGGLERS_SOLDIERS");
	ch.greeting = "Gr_Patrol";
	n = n + 1;

	makeref(ch,Characters[n]);		//  Luis Chagas -- man2
	ch.name 	= "Luis";
	ch.lastname = "Chagas";
	ch.id		= "Luis Chagas";
	ch.model	= "man2";
	ch.sex = "man";
	ch.act.type = "pirate";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Smugglers_Lair";
	ch.location.group = "goto";
	ch.location.locator = "goto23";
	ch.Dialog.Filename = "Patrol_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetWarriorType(ch);
	LAi_warrior_DialogEnable(ch, true);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SMUGGLERS_SOLDIERS");
	ch.greeting = "Gr_Patrol";
	n = n + 1;

// Smugglers_Store:

	makeref(ch,Characters[n]);		//  Leonardo Violate -- man2
	ch.name 	= "Leonardo";
	ch.lastname = "Violate";
	ch.id		= "Leonardo Violate";
	ch.model	= "man2";
	ch.sex = "man";
	ch.location	= "Smugglers_Store";
	ch.location.group = "sit";
	ch.location.locator = "sit1";
	ch.Dialog.Filename = "Leonardo Violate_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetMerchantType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_group_MoveCharacter(ch, "SMUGGLERS_CITIZENS");

	n = n + 1;

// Smugglers_Tavern:

	makeref(ch,Characters[n]);		//  Fabiao Dunga -- fatman2 (tractir holder)
	ch.name 	= "Fabiao";
	ch.lastname = "Dunga";
	ch.id		= "Fabiao Dunga";
	ch.model	= "fatman2";
	ch.sex = "man";
	ch.location	= "Smugglers_Tavern";
	ch.location.group = "merchant";
	ch.location.locator = "goto3";
	ch.Dialog.Filename = "Fabiao Dunga_dialog.c";
	ch.greeting = "Gr_Fabiao Dunga";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetBarmanType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_group_MoveCharacter(ch, "SMUGGLERS_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);		//  Christiano Bessa -- Corsair3
	ch.name 	= "Christiano";
	ch.lastname = "Bessa";
	ch.id		= "Christiano Bessa";
	ch.model	= "Corsair3";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	ch.location	= "Smugglers_Tavern";
	ch.location.group = "sit";
	ch.location.locator = "sit5";
	ch.Dialog.Filename = "habitue_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetSitType(ch);
	LAi_group_MoveCharacter(ch, "SMUGGLERS_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);		//  Adao Henriques -- korsar
	ch.name 	= "Adao";
	ch.lastname = "Henriques";
	ch.id		= "Adao Henriques";
	ch.model	= "korsar";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	ch.location	= "Smugglers_Tavern";
	ch.location.group = "sit";
	ch.location.locator = "sit4";
	ch.Dialog.Filename = "habitue_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetSitType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_group_MoveCharacter(ch, "SMUGGLERS_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);		//  Camilo Machado -- korsar
	ch.name 	= "Camilo";
	ch.lastname = "Machado";
	ch.id		= "Camilo Machado";
	ch.model	= "korsar";
	ch.sex = "man";
	GiveItem2Character(ch, GUN_COMMON);
	ch.equip.gun = GUN_COMMON;
	GiveItem2Character(ch, BLADE_LONG);
	ch.equip.blade = BLADE_LONG;
	ch.location	= "Smugglers_Residence";
	ch.location.group = "goto";
	ch.location.locator = "goto1";
	ch.Dialog.Filename = "Camilo Machado_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "0";
	LAi_SetMerchantType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 120.0, 120.0);
	LAi_group_MoveCharacter(ch, "SMUGGLERS_CITIZENS");
	ch.greeting = "Gr_camilo machado";
	n = n + 1;

	makeref(ch,Characters[n]);		//  Evaristo Filho -- korsar
	ch.name 	= "Evaristo";
	ch.lastname = "Filho";
	ch.id		= "Evaristo Filho";
	ch.model	= "man1";
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.sound_type = "soldier";
	ch.location	= "Smugglers_Lair";
	ch.location.group = "goto";
	ch.location.locator = "goto28";
	ch.Dialog.Filename = "Evaristo Filho_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "0";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SMUGGLERS_SOLDIERS");
	ch.greeting = "Gr_Evaristo Filho";
	n = n + 1;

	makeref(ch,Characters[n]);		//  Macario Regalo -- korsar
	ch.name 	= "Macario";
	ch.lastname = "Regalo";
	ch.id		= "Macario Regalo";
	ch.model	= "man2";
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.sound_type = "soldier";
	ch.location	= "Smugglers_Lair";
	ch.location.group = "goto";
	ch.location.locator = "goto29";
	ch.Dialog.Filename = "Evaristo Filho_dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "0";
	LAi_SetguardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "SMUGGLERS_SOLDIERS");
	ch.greeting = "Gr_Evaristo Filho";
	n = n + 1;

	makeref(ch,Characters[n]);		//  Smuggler_officiant -- шлюха в таверне
	ch.name 	= "Sofia";
	ch.lastname = "Guterres";
	ch.id		= "Smugglers_officiant";
	ch.model	= "towngirl1";
	ch.sex = "woman";
	ch.sound_type = "female_citizen";
	ch.location	= "Smugglers_tavern";
	ch.location.group = "goto";
	ch.location.locator = "goto6";
	ch.Dialog.Filename = "eng_officiant_dialog.c";
	ch.greeting = "Gr_eng_officiant";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "0";
	ch.quest.sex = "0";
	LAi_SetWaitressType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_group_MoveCharacter(ch, "SMUGGLERS_CITIZENS");
	n = n + 1;

	return n;
}