
int CreateFalaiseDeFleurCharacters(int n)
{
	ref ch;

	makeref(ch,Characters[n]);			//Antoine Lebretton (тавернщик) озвучка готова.
	ch.name 	= "Antoine";
	ch.lastname 	= "Lebretton";
	ch.id		= "Antoine Lebretton";
	ch.model = "Old_man1";
	ch.sex = "man";
	ch.location	= "Falaise_de_fleur_tavern";
	ch.location.group = "merchant";
	ch.location.locator = "goto1";
	ch.Dialog.Filename = "Antoine Lebretton_dialog.c";
	ch.greeting = "Gr_antoine lebretton";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "70";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "4";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.work = "";
	ch.quest.meeting = "0";
	LAi_SetBarmanType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	n = n + 1;

	trace ("n is " + n);

	makeref(ch,Characters[n]);		// Conceicao_officiant
	ch.name 	= "Pauline";
	ch.lastname = "Beteille";
	ch.id		= "Falaise_de_fleur_officiant";
	ch.model	= "towngirl2";
	ch.sex = "woman";
	ch.sound_type = "female_citizen";
	ch.location	= "FALAISE_DE_FLEUR_tavern";
	ch.location.group = "goto";
	ch.location.locator = "goto5";
	ch.Dialog.Filename = "Eng_Officiant_dialog.c";
	ch.greeting = "Gr_eng_officiant";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	ch.quest.sex = 0;
	ch.sex.time = 0;
	LAi_SetWaitressType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			// Arnaud Matton (хозяин магазина на Falaise De Fleur)
	ch.name 	= "Arnaud";
	ch.lastname 	= "Matton";
	ch.id		= "Arnaud Matton";
	ch.model = "storeman2";
	ch.sex = "man";
	ch.location	= "Falaise_de_Fleur_store";
	ch.location.group = "goto";
	ch.location.locator = "goto1";
	ch.Dialog.Filename = "Arnaud Matton_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "43";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "4";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.money.quest = "0";
	ch.quest.meeting = "0";
	ch.quest_begin = "0";
	ch.quest.to_redmond_1 = "0";
	ch.quest.trade_date = "";
	ch.quest.item_date = "";
	LAi_SetMerchantType(ch);
	LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	ch.greeting = "Gr_arnaud matton";
	n = n + 1;

	makeref(ch,Characters[n]);			// pater Jourdain (церковь)
	ch.name 	= "Pater";
	ch.lastname 	= "Jourdain";
	ch.id		= "pater Jourdain";
	ch.model	= "monk";
	ch.sex = "man";
	ch.sound_type = "priest";
	ch.location	= "Falaise_de_fleur_church";
	ch.location.group = "goto";
	ch.location.locator = "goto11";
	ch.Dialog.Filename = "pater Jourdain_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "58";
	ch.experience = "0";
	ch.skill.Leadership = "4";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	ch.quest.donations = "0";
	ch.quest.prihod = "0";
	LAi_SetPriestType(ch);
	LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	ch.greeting = "Gr_Pater Jourdain";
	n = n + 1;

	makeref(ch,Characters[n]);			// Jean Filaut (верфь)
	ch.name 	= "Jean";
	ch.lastname 	= "Filaut";
	ch.id		= "Jean Filaut";
	ch.model	= "man6";
	ch.sex = "man";
	ch.location	= "Falaise_de_Fleur_shipyard";
	ch.location.group = "sit";
	ch.location.locator = "sit3";
	ch.Dialog.Filename = "Jean Filaut_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "53";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "4";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "3";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetHuberType(ch);
	LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	ch.greeting = "Gr_jean filaut";
	n = n + 1;

	makeref(ch,Characters[n]);			// Joseph Claude Le Moigne (townhall)
	ch.name 	= "Joseph";
	ch.middlename 	= "Claude";
	ch.lastname 	= "Le Moigne";
	ch.id		= "Joseph Claude Le Moigne";
	ch.model = "huber_fra";
	ch.location	= "Falaise_de_fleur_townhall";
	ch.location.group = "goto";
	ch.location.locator = "goto8";
	ch.Dialog.Filename = "Joseph Claude Le Moigne_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "60";
	ch.experience = "0";
	ch.skill.Leadership = "6";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "5";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	ch.quest.english_war_ship = "0";
	LAi_RemoveLoginTime(ch);
	LAi_SetHuberStayType(ch);
	LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	LAi_SetStayHuberPointWindow(ch, "goto", "goto5");
	LAi_SetStayHuberPointMap(ch, "goto", "goto10");
	ch.greeting = "Gr_joseph claude le moigne";
	n = n + 1;

	makeref(ch,Characters[n]);			// Hardouin Aufort (офицер) озвучка готова
	ch.name 	= "Hardouin";
	ch.lastname 	= "Aufort";
	ch.id		= "Hardouin Aufort";
	ch.model = "offic_fra";
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	GiveItem2Character(ch, GUN_COMMON);
	ch.equip.gun = GUN_COMMON;
	GiveItem2Character(ch, BLADE_LONG);
	ch.equip.blade = BLADE_LONG;
	ch.location	= "Falaise_de_fleur_location_03";
	ch.location.group = "goto";
	ch.location.locator = "soldier04";
	ch.Dialog.Filename = "Hardouin Aufort_dialog.c";
	ch.greeting = "Gr_hardouin aufort";
	ch.nation = FRANCE;
	ch.rank 	= 5;
	ch.reputation = "52";
	ch.experience = "0";
	ch.skill.Leadership = "4";
	ch.skill.Fencing = "7";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 120.0, 120.0);
	LAi_group_MoveCharacter(ch, "FRANCE_SOLDIERS");
	n = n + 1;

	makeref(ch,Characters[n]);			// Turpin Cabanel (начальник порта) озвучка готова
	ch.name 	= "Turpin";
	ch.lastname 	= "Cabanel";
	ch.id		= "Turpin Cabanel";
	ch.model = "man6_1";
	ch.sex = "man";
	ch.sound_type = "merchant";
	ch.location	= "Head_port_house";
	ch.location.group = "goto";
	ch.location.locator = "locator1";
	ch.Dialog.Filename = "Turpin Cabanel_dialog.c";
	ch.greeting = "Gr_turpin cabanel";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "65";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.money.quest = "0";
	ch.quest.meeting = "0";
	ch.quest.smugglers = "0";
	LAi_SetStayType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	LAi_SetImmortal(ch, true);
	n = n + 1;

	///////////////////////////////////////////////////////////////////////////////////////////////
	// FALAISE DE FLEUR PORT 1
	///////////////////////////////////////////////////////////////////////////////////////////////

	makeref(ch,Characters[n]);		//Milon Blacque (сумасшедший старик на пристани) озвучка готова
	ch.name 	= "Milon";
	ch.lastname 	= "Blacque";
	ch.id		= "Milon Blacque";
	ch.model	= "Old_man1";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	ch.location	= "Falaise_de_fleur_port_01";
	ch.location.group = "goto";
	ch.location.locator = "carpenter1";
	ch.Dialog.Filename = "Falaise De Fleur citizen_dialog.c";//"Milon Blacque_dialog.c";
	ch.greeting = "Gr_Milon Blacque";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "45";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0"
	ch.quest.first_talk = "0";
	ch.quest.son = "0";
	LAi_SetMerchantType(ch);
	LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			//Orable Caron (плотник у лесов) озвучка готова
	ch.name 	= "Orable";
	ch.lastname 	= "Caron";
	ch.id		= "Orable Caron";
	ch.model = "man5";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	ch.location	= "Falaise_de_fleur_port_01";
	ch.location.group = "goto";
	ch.location.locator = "carpenter";
	ch.Dialog.Filename = "Falaise De Fleur citizen_dialog.c";//"Orable Caron_dialog.c";
	ch.greeting = "Gr_Orable Caron";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "38";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "6";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.quest.meeting = "0";
	ch.money = "10";
	LAi_SetMerchantType(ch);
	LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			// Gris Barthez
	ch.name 	= "Gris";
	ch.lastname 	= "Barthez";
	ch.id		= "Gris Barthez";
	ch.model = "fisherman";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	ch.fanatic = "1";
	ch.church = "Falaise_De_Fleur_church";
	ch.church.loc = "goto3";
	ch.back.location = "Falaise_de_fleur_port_01";
	ch.back.locator = "goto10";
	ch.location	= "Falaise_de_fleur_port_01";
	ch.location.group = "goto";
	ch.location.locator = "goto10";
	ch.Dialog.Filename = "Falaise De Fleur citizen_dialog.c";
	ch.greeting = "Gr_falaise de fleur citizen";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "40";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			// Huon Marly
	ch.name 	= "Huon";
	ch.lastname 	= "Marly";
	ch.id		= "Huon Marly";
	ch.model = "man5";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	ch.location	= "Falaise_de_fleur_port_01";
	ch.location.group = "goto";
	ch.location.locator = "goto4";
	ch.Dialog.Filename = "Falaise De Fleur citizen_dialog.c";
	ch.greeting = "Gr_falaise de fleur citizen";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "40";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			// Tancrede Rimbaud
	ch.name 	= "Tancrede";
	ch.lastname 	= "Rimbaud";
	ch.id		= "Tancrede Rimbaud";
	ch.model = "man4";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	ch.fanatic = "1";
	ch.church = "Falaise_De_Fleur_church";
	ch.church.loc = "goto4";
	ch.back.location = "Falaise_de_fleur_port_01";
	ch.back.locator = "goto17";
	ch.location	= "Falaise_de_fleur_port_01";
	ch.location.group = "goto";
	ch.location.locator = "goto17";
	ch.Dialog.Filename = "Falaise De Fleur citizen_dialog.c";
	ch.greeting = "Gr_Tancrede Rimbaud";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "40";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			// Pierre Biez
	ch.name 	= "Pierre";
	ch.lastname 	= "Biez";
	ch.id		= "Pierre Biez";
	ch.model = "brodyaga";
	ch.sex = "man";
	ch.sound_type = "poorman";
	ch.location	= "Falaise_de_fleur_port_01";
	ch.location.group = "goto";
	ch.location.locator = "goto8";
	ch.Dialog.Filename = "Falaise De Fleur citizen_dialog.c";
	ch.greeting = "Gr_falaise de fleur citizen";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "40";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	n = n + 1;

	///////////////////////////////////////////////////////////////////////////////////////////////
	// FALAISE DE FLEUR PORT 2
	///////////////////////////////////////////////////////////////////////////////////////////////

	makeref(ch,Characters[n]);			// Landri Chevit
	ch.name 	= "Landri";
	ch.lastname 	= "Chevit";
	ch.id		= "Landri Chevit";
	ch.model = "man2";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	ch.location	= "Falaise_de_fleur_port_02";
	ch.location.group = "goto";
	ch.location.locator = "locator18";
	ch.Dialog.Filename = "Falaise De Fleur citizen_dialog.c";
	ch.greeting = "Gr_falaise de fleur citizen";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "40";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			// Philippe Dary
	ch.name 	= "Philippe";
	ch.lastname 	= "Dary";
	ch.id		= "Philippe Dary";
	ch.model = "man5";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	ch.fanatic = "1";
	ch.church = "Falaise_De_Fleur_church";
	ch.church.loc = "goto5";
	ch.back.location = "Falaise_de_fleur_port_02";
	ch.back.locator = "citizen06";
	ch.location	= "Falaise_de_fleur_port_02";
	ch.location.group = "goto";
	ch.location.locator = "citizen06";
	ch.Dialog.Filename = "Falaise De Fleur citizen_dialog.c";
	ch.greeting = "Gr_falaise de fleur citizen";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "40";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			// Martin Hoschede
	ch.name 	= "Martin";
	ch.lastname 	= "Hoschede";
	ch.id		= "Martin Hoschede";
	ch.model = "man1_1";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	ch.location	= "Falaise_de_fleur_port_02";
	ch.location.group = "goto";
	ch.location.locator = "carpenter";
	ch.Dialog.Filename = "Falaise De Fleur citizen_dialog.c";
	ch.greeting = "Gr_falaise de fleur citizen";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "40";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetMerchantType(ch);
	LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			// Gaidon Pinette
	ch.name 	= "Gaidon";
	ch.lastname 	= "Pinette";
	ch.id		= "Gaidon Pinette";
	ch.model = "man3";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	ch.location	= "Falaise_de_fleur_port_02";
	ch.location.group = "goto";
	ch.location.locator = "locator 22";
	ch.Dialog.Filename = "Falaise De Fleur citizen_dialog.c";
	ch.greeting = "Gr_falaise de fleur citizen";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "40";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	n = n + 1;

	///////////////////////////////////////////////////////////////////////////////////////////////
	// FALAISE DE FLEUR LOCATION 02
	///////////////////////////////////////////////////////////////////////////////////////////////

	makeref(ch,Characters[n]);			// Emile Capelle
	ch.name 	= "Emile";
	ch.lastname 	= "Capelle";
	ch.id		= "Emile Capelle";
	ch.model = "chelovek";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	ch.fanatic = "1";
	ch.church = "Falaise_De_Fleur_church";
	ch.church.loc = "goto6";
	ch.back.location = "Falaise_de_fleur_location_02";
	ch.back.locator = "citizen03";
	ch.location	= "Falaise_de_fleur_location_02";
	ch.location.group = "goto";
	ch.location.locator = "citizen03";
	ch.Dialog.Filename = "Falaise De Fleur citizen_dialog.c";
	ch.greeting = "Gr_falaise de fleur citizen";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "40";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			// Doolin Soleuze
	ch.name 	= "Doolin";
	ch.lastname 	= "Soleuze";
	ch.id		= "Doolin Soleuze";
	ch.model = "man3";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	ch.location	= "Falaise_de_fleur_location_02";
	ch.location.group = "goto";
	ch.location.locator = "citizen07";
	ch.Dialog.Filename = "Falaise De Fleur citizen_dialog.c";
	ch.greeting = "Gr_falaise de fleur citizen";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "40";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			// Merle Granet
	ch.name 	= "Merle";
	ch.lastname 	= "Granet";
	ch.id		= "Merle Granet";
	ch.model = "towngirl2";
	ch.sex = "woman";
	ch.sound_type = "female_citizen";
	ch.fanatic = "1";
	ch.church = "Falaise_De_Fleur_church";
	ch.church.loc = "goto7";
	ch.back.location = "Falaise_de_fleur_location_02";
	ch.back.locator = "citizen01";
	ch.location	= "Falaise_de_fleur_location_02";
	ch.location.group = "goto";
	ch.location.locator = "citizen01";
	ch.Dialog.Filename = "Falaise De Fleur citizen_dialog.c";
	ch.greeting = "Gr_Woman_French citizen";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "40";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			// Prosper Deglau
	ch.name 	= "Prosper";
	ch.lastname 	= "Deglau";
	ch.id		= "Prosper Deglau";
	ch.model = "Corsair2";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Falaise_de_fleur_location_02";
	ch.location.group = "goto";
	ch.location.locator = "citizen09";
	ch.Dialog.Filename = "Falaise De Fleur citizen_dialog.c";
	ch.greeting = "Gr_falaise de fleur citizen";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "40";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			// Robert Mingeon
	ch.name 	= "Robert";
	ch.lastname 	= "Mingeon";
	ch.id		= "Robert Mingeon";
	ch.model = "man5";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	ch.fanatic = "1";
	ch.church = "Falaise_De_Fleur_church";
	ch.church.loc = "goto8";
	ch.back.location = "Falaise_de_fleur_location_02";
	ch.back.locator = "citizen06";
	ch.location	= "Falaise_de_fleur_location_02";
	ch.location.group = "goto";
	ch.location.locator = "citizen06";
	ch.Dialog.Filename = "Falaise De Fleur citizen_dialog.c";
	ch.greeting = "Gr_falaise de fleur citizen";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "40";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			// Valerian Alembert
	ch.name 	= "Valerian";
	ch.lastname 	= "Alembert";
	ch.id		= "Valerian Alembert";
	ch.model = "Corsair1";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Falaise_de_fleur_location_02";
	ch.location.group = "goto";
	ch.location.locator = "citizen04";
	ch.Dialog.Filename = "Falaise De Fleur citizen_dialog.c";
	ch.greeting = "Gr_falaise de fleur citizen";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "40";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			// Alban Sartre
	ch.name 	= "Alban";
	ch.lastname 	= "Sartre";
	ch.id		= "Alban Sartre";
	ch.model = "Old_man1";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	ch.location	= "Falaise_de_fleur_location_02";
	ch.location.group = "goto";
	ch.location.locator = "citizen02";
	ch.Dialog.Filename = "Falaise De Fleur citizen_dialog.c";
	ch.greeting = "Gr_falaise de fleur citizen";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "40";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	n = n + 1;

	///////////////////////////////////////////////////////////////////////////////////////////////
	// FALAISE DE FLEUR LOCATION 03
	///////////////////////////////////////////////////////////////////////////////////////////////

	makeref(ch,Characters[n]);			//Patric Cardone (ТОРГОВЕЦ НА ЛОТКЕ) озвучка готова.
	ch.name 	= "Patric";
	ch.lastname 	= "Cardone";
	ch.id		= "Patric Cardone";
	ch.model = "fatman1";
	ch.sex = "man";
	ch.sound_type = "merchant";
	ch.location	= "Falaise_de_fleur_location_03";
	ch.location.group = "merchant";
	ch.location.locator = "merchant1";
	ch.Dialog.Filename = "Item Trader_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "3";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.money.quest = "0";
	ch.quest.meeting = "0";
	ch.quest.teodoro = "0";
	LAi_SetMerchantType(ch);
	LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	ch.greeting = "Gr_Patric Cardone";
	n = n + 1;

	makeref(ch,Characters[n]);			// Octavien Sauvaigo
	ch.name 	= "Octavien";
	ch.lastname 	= "Sauvaigo";
	ch.id		= "Octavien Sauvaigo";
	ch.model = "man6";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	ch.fanatic = "1";
	ch.church = "Falaise_De_Fleur_church";
	ch.church.loc = "goto9";
	ch.back.location = "Falaise_de_fleur_location_03";
	ch.back.locator = "sitizen01";
	ch.location	= "Falaise_de_fleur_location_03";
	ch.location.group = "goto";
	ch.location.locator = "Sitizen01";
	ch.Dialog.Filename = "Falaise De Fleur citizen_dialog.c";
	ch.greeting = "Gr_falaise de fleur citizen";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "40";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			// Justin Beineix
	ch.name 	= "Justin";
	ch.lastname 	= "Beineix";
	ch.id		= "Justin Beineix";
	ch.model = "Corsair1";
	ch.sex = "man";
	ch.sound_type = "seaman";
	ch.location	= "Falaise_de_fleur_location_03";
	ch.location.group = "goto";
	ch.location.locator = "Sitizen02";
	ch.Dialog.Filename = "Falaise De Fleur citizen_dialog.c";
	ch.greeting = "Gr_falaise de fleur citizen";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "40";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			// Loup Letice
	ch.name 	= "Loup";
	ch.lastname 	= "Letice";
	ch.id		= "Loup Letice";
	ch.model = "man1";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	ch.fanatic = "1";
	ch.church = "Falaise_De_Fleur_church";
	ch.church.loc = "goto10";
	ch.back.location = "Falaise_de_fleur_location_03";
	ch.back.locator = "sitizen06";
	ch.location	= "Falaise_de_fleur_location_03";
	ch.location.group = "goto";
	ch.location.locator = "Sitizen06";
	ch.Dialog.Filename = "Falaise De Fleur citizen_dialog.c";
	ch.greeting = "Gr_falaise de fleur citizen";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "40";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			// Virginie Ruinart
	ch.name 	= "Virginie";
	ch.lastname 	= "Ruinart";
	ch.id		= "Virginie Ruinart";
	ch.model = "towngirl1";
	ch.sex = "woman";
	ch.sound_type = "female_citizen";
	ch.location	= "Falaise_de_fleur_location_03";
	ch.location.group = "goto";
	ch.location.locator = "merchant02";
	ch.Dialog.Filename = "Falaise De Fleur citizen_dialog.c";
	ch.greeting = "Gr_Woman_French citizen";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "40";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			// Sebastien Wilmart
	ch.name 	= "Sebastien";
	ch.lastname 	= "Wilmart";
	ch.id		= "Sebastien Wilmart";
	ch.model = "man5";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	ch.location	= "Falaise_de_fleur_location_03";
	ch.location.group = "goto";
	ch.location.locator = "Sitizen04";
	ch.Dialog.Filename = "Falaise De Fleur citizen_dialog.c";
	ch.greeting = "Gr_falaise de fleur citizen";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "40";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			// Honore Villette
	ch.name 	= "Honore";
	ch.lastname 	= "Villette";
	ch.id		= "Honore Villette";
	ch.model = "Mongol";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	ch.location	= "Falaise_de_fleur_location_03";
	ch.location.group = "goto";
	ch.location.locator = "Sitizen03";
	ch.Dialog.Filename = "Falaise De Fleur citizen_dialog.c";
	ch.greeting = "Gr_falaise de fleur citizen";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "40";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			// Helgot Cottard
	ch.name 	= "Helgot";
	ch.lastname 	= "Cottard";
	ch.id		= "Helgot Cottard";
	ch.model = "man3";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	ch.location	= "Falaise_de_fleur_location_03";
	ch.location.group = "goto";
	ch.location.locator = "Sitizen05";
	ch.Dialog.Filename = "Falaise De Fleur citizen_dialog.c";
	ch.greeting = "Gr_falaise de fleur citizen";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "40";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			// Celestin Fammeree
	ch.name 	= "Celestin";
	ch.lastname 	= "Fammeree";
	ch.id		= "Celestin Fammeree";
	ch.model = "man2";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	ch.location	= "Falaise_de_fleur_location_03";
	ch.location.group = "goto";
	ch.location.locator = "Sitizen07";
	ch.Dialog.Filename = "Falaise De Fleur citizen_dialog.c";
	ch.greeting = "Gr_falaise de fleur citizen";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "40";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	n = n + 1;

	///////////////////////////////////////////////////////////////////////////////////////////////
	// FALAISE DE FLEUR LOCATION 04
	///////////////////////////////////////////////////////////////////////////////////////////////

	makeref(ch,Characters[n]);			//Rachel Blacque (приемная дочь милона) озвучка готова
	ch.name 	= "Rachel";
	ch.lastname 	= "Blacque";
	ch.id		= "Rachel Blacque";
	ch.model = "towngirl1";
	ch.sex = "woman";
	ch.sound_type = "female_citizen";
	ch.location	= "Falaise_de_fleur_location_04";
	ch.location.group = "goto";
	ch.location.locator = "citizen01";
	ch.Dialog.Filename = "Falaise De Fleur citizen_dialog.c";//"Rachel Blacque_dialog.c";
	ch.greeting = "Gr_Rachel Blacque";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "55";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	ch.quest.badguy = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			// Felix Baijot
	ch.name 	= "Felix";
	ch.lastname 	= "Baijot";
	ch.id		= "Felix Baijot";
	ch.model = "Mongol";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	ch.location	= "Falaise_de_fleur_location_04";
	ch.location.group = "goto";
	ch.location.locator = "citizen02";
	ch.Dialog.Filename = "Falaise De Fleur citizen_dialog.c";
	ch.greeting = "Gr_falaise de fleur citizen";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "40";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			// Florentin Oudet
	ch.name 	= "Florentin";
	ch.lastname 	= "Oudet";
	ch.id		= "Florentin Oudet";
	ch.model = "Corsair1_2";
	ch.sex = "man";
	ch.sound_type = "seaman";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Falaise_de_fleur_location_04";
	ch.location.group = "goto";
	ch.location.locator = "citizen05";
	ch.Dialog.Filename = "Falaise De Fleur citizen_dialog.c";
	ch.greeting = "Gr_falaise de fleur citizen";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "40";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	n = n + 1;

	///////////////////////////////////////////////////////////////////////////////////////////////
	// FALAISE DE FLEUR LOCATION 05
	///////////////////////////////////////////////////////////////////////////////////////////////

	makeref(ch,Characters[n]);			// Amadeo Theriot
	ch.name 	= "Amadeo";
	ch.lastname 	= "Theriot";
	ch.id		= "Amadeo Theriot";
	ch.model = "korsar";
	ch.sex = "man";
	ch.sound_type = "seaman";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Falaise_de_fleur_location_05";
	ch.location.group = "goto";
	ch.location.locator = "citizen01";
	ch.Dialog.Filename = "Falaise De Fleur citizen_dialog.c";
	ch.greeting = "Gr_falaise de fleur citizen";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "40";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			// Brantome Visse
	ch.name 	= "Brantome";
	ch.lastname 	= "Visse";
	ch.id		= "Brantome Visse";
	ch.model = "man1_1";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	ch.location	= "Falaise_de_fleur_location_05";
	ch.location.group = "goto";
	ch.location.locator = "citizen03";
	ch.Dialog.Filename = "Falaise De Fleur citizen_dialog.c";
	ch.greeting = "Gr_falaise de fleur citizen";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "40";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			// Fluvant Trenet
	ch.name 	= "Fluvant";
	ch.lastname 	= "Trenet";
	ch.id		= "Fluvant Trenet";
	ch.model = "chelovek";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	ch.location	= "Falaise_de_fleur_location_05";
	ch.location.group = "goto";
	ch.location.locator = "citizen04";
	ch.Dialog.Filename = "Falaise De Fleur citizen_dialog.c";
	ch.greeting = "Gr_falaise de fleur citizen";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "40";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			// Gentile Hurtis
	ch.name 	= "Gentile";
	ch.lastname 	= "Hurtis";
	ch.id		= "Gentile Hurtis";
	ch.model = "towngirl1";
	ch.sex = "woman";
	ch.sound_type = "female_citizen";
	ch.location	= "Falaise_de_fleur_location_05";
	ch.location.group = "goto";
	ch.location.locator = "citizen05";
	ch.Dialog.Filename = "Falaise De Fleur citizen_dialog.c";
	ch.greeting = "Gr_Woman_French citizen";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "40";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			// Beuve Jenlain
	ch.name 	= "Beuve";
	ch.lastname 	= "Jenlain";
	ch.id		= "Beuve Jenlain";
	ch.model = "Black_Corsair";
	ch.sex = "man";
	ch.sound_type = "seaman";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Falaise_de_fleur_location_05";
	ch.location.group = "goto";
	ch.location.locator = "citizen06";
	ch.Dialog.Filename = "Falaise De Fleur citizen_dialog.c";
	ch.greeting = "Gr_falaise de fleur citizen";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "40";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			// Corneille Maccaux
	ch.name 	= "Corneille";
	ch.lastname 	= "Maccaux";
	ch.id		= "Corneille Maccaux";
	ch.model = "bocman";
	ch.sex = "man";
	ch.sound_type = "seaman";
	ch.location	= "Falaise_de_fleur_location_05";
	ch.location.group = "goto";
	ch.location.locator = "citizen02";
	ch.Dialog.Filename = "Falaise De Fleur citizen_dialog.c";
	ch.greeting = "Gr_falaise de fleur citizen";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "40";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			//Lucien Bescanceny (вор, спит в своем доме) озвучка готова
	ch.name 	= "Lucien";
	ch.lastname 	= "Bescanceny";
	ch.id		= "Lucien Bescanceny";
	ch.model = "fatman";
	ch.sex = "man";
	ch.sound_type = "pirate";
	ch.location	= "house_of_laurence";
	ch.location.group = "goto";
	ch.location.locator = "goto2";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.Dialog.Filename = "Lucien Bescanceny_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "28";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "2";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetMerchantType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 60.0, 60.0);
	LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	ch.greeting = "Gr_Lucien Bescanceny";
	n = n + 1;

	makeref(ch,Characters[n]);			// Teodoro Fernandez ()
	ch.name 	= "Teodoro";
	ch.lastname 	= "Fernandez";
	ch.id		= "Teodoro Fernandez";
	ch.model = "blaze";
	ch.location	= "none";
	ch.Dialog.Filename = "Teodoro Fernandez_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "30";
	ch.experience = "0";
	ch.skill.Leadership = "5";
	ch.skill.Fencing = "6";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			// Thierry Bosquet (буканер в таверне)
	ch.name 	= "Thierry";
	ch.lastname 	= "Bosquet";
	ch.id		= "Thierry Bosquet";
	ch.model = "Black_Corsair";
	ch.sound_type = "seaman";
	ch.sex = "man";
	GiveItem2Character(ch, "blade7");
	ch.equip.blade = "blade7";
	ch.location	= "Falaise_de_fleur_tavern";
	ch.location.group = "sit";
	ch.location.locator = "sit2";
	ch.Dialog.Filename = "Thierry Bosquet_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 3;
	ch.reputation = "35";
	ch.experience = "40";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "4";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "3";
	ch.skill.Cannons = "3";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "600";
	ch.quest.meeting = "0";
	ch.quest.gambling = "0";
	LAi_SetSitType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	ch.greeting = "Gr_thierry bosquet";
	n = n + 1;

	makeref(ch,Characters[n]);			// Marc Blacque (находится на английском острове, сын Милона)
	ch.name 	= "Marc";
	ch.lastname 	= "Blacque";
	ch.id		= "Marc Blacque";
	ch.model = "Chameleon";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	ch.location	= "Redmond_town_01";
	ch.location.group = "goto";
	ch.location.locator = "cityzen4";
	ch.Dialog.Filename = "Falaise De Fleur citizen_dialog.c";//"Marc Blacque_dialog.c";
	ch.greeting = "Gr_Marc Blacque";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "0";
	ch.skill.Leadership = "2";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "3";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			// Andre Juliao (Контрабандист в таверне) озвучка готова.
	ch.name 	= "Andre";
	ch.lastname 	= "Juliao";
	ch.id		= "Andre Juliao";
	ch.model = "man2";
	ch.sex = "man";
	ch.sound_type = "pirate";
	ch.location	= "Falaise_de_fleur_tavern";
	ch.location.group = "sit";
	ch.location.locator = "sit3";
	ch.Dialog.Filename = "Andre Juliao_dialog.c";
	ch.greeting = "Gr_andre juliao";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "34";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "4";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "5";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetSitType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			// Raoul Calmes (контрабандист в доме) озвучка готова.
	ch.name 	= "Raoul";
	ch.lastname 	= "Calmes";
	ch.id		= "Raoul Calmes";
	ch.model = "man2";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "house_of_smuggler_in_FiF";
	ch.location.group = "goto";
	ch.location.locator = "goto2";
	ch.Dialog.Filename = "Raoul Calmes_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "40";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "4";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	ch.quest.visit = "0";
	LAi_SetMerchantType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	ch.greeting = "Gr_Raoul Calmes";
	n = n + 1;

	makeref(ch,Characters[n]);			// Elzire Ayarai (девушка, сидит в своем доме)
	ch.name 	= "Elzire";
	ch.lastname 	= "Ayarai";
	ch.id		= "Elzire Ayarai";
	ch.model = "towngirl3";
	ch.sex = "woman";
	ch.sound_type = "female_citizen";
	ch.location	= "house_of_Elzire_Ayarai";
	ch.location.group = "goto";
	ch.location.locator = "goto2";
	ch.Dialog.Filename = "Elzire Ayarai_dialog.c";
	ch.greeting = "Gr_elzire ayarai";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "40";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetMerchantType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			// Sabine Matton  дочь Арно маттона //скрыта
	ch.name 	= "Sabine";
	ch.nickname = "Sabie";
	ch.lastname 	= "Matton";
	ch.id		= "Sabine Matton";
	ch.FaceId = 15;
	ch.model = "towngirl1";
	ch.sound_type = "female_citizen";
	ch.sex = "woman";
	ch.location	= "none";
	ch.location.group = "goto";
	ch.location.locator = "none";
	ch.Dialog.Filename = "Sabine Matton_dialog.c";
	ch.greeting = "Gr_Sabine Matton";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "40";
	ch.experience = "0";
	ch.skill.Leadership = "0";
	ch.skill.Fencing = "0";
	ch.skill.Sailing = "0";
	ch.skill.Accuracy = "0";
	ch.skill.Cannons = "0";
	ch.skill.Grappling = "0";
	ch.skill.Repair = "0";
	ch.skill.Defence = "0";
	ch.skill.Commerce = "0";
	ch.skill.Sneak = "0";
	ch.money = "10";
	ch.quest.meeting = "0";
	ch.quest.hire = "0";
	ch.quest.love = "0";
	LAi_SetMerchantType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_group_MoveCharacter(ch, "FRANCE_CITIZENS");
	n = n + 1;

	///////////////////////////////////////////////////////////////////////////////////////////////
	// SOLDIERS
	///////////////////////////////////////////////////////////////////////////////////////////////

	makeref(ch,Characters[n]);			// Soldier
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Falaise De Fleur Soldier 01";
	ch.model = "Soldier_Fra";
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Falaise_de_fleur_port_01";
	ch.location.group = "goto";
	ch.location.locator = "goto19";
	ch.Dialog.Filename = "Falaise De Fleur Soldier_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "FRANCE_SOLDIERS");
	ch.greeting = "Gr_falaise de fleur soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			// Soldier
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Falaise De Fleur Soldier 02";
	ch.model = "Soldier_Fra2";
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Falaise_de_fleur_port_01";
	ch.location.group = "goto";
	ch.location.locator = "goto18";
	ch.Dialog.Filename = "Falaise De Fleur Soldier_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "FRANCE_SOLDIERS");
	ch.greeting = "Gr_falaise de fleur soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			// Soldier
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Falaise De Fleur Soldier 03";
	ch.model = "Soldier_Fra5";
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Falaise_de_fleur_port_01";
	ch.location.group = "goto";
	ch.location.locator = "goto3";
	ch.Dialog.Filename = "Falaise De Fleur Soldier_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "FRANCE_SOLDIERS");
	ch.greeting = "Gr_falaise de fleur soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			// patrol
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Falaise De Fleur patrol 01";
	ch.model = "Soldier_Fra4";
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Falaise_de_fleur_port_01";
	ch.location.group = "goto";
	ch.location.locator = "goto8";
	ch.Dialog.Filename = "Patrol_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "FRANCE_SOLDIERS");
	ch.greeting = "Gr_Patrol";
	n = n + 1;

	makeref(ch,Characters[n]);			// patrol
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Falaise De Fleur patrol 02";
	ch.model = "Soldier_Fra3";
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Falaise_de_fleur_port_01";
	ch.location.group = "goto";
	ch.location.locator = "goto7";
	ch.Dialog.Filename = "Patrol_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "2";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "FRANCE_SOLDIERS");
	ch.greeting = "Gr_Patrol";
	n = n + 1;

	makeref(ch,Characters[n]);			// Soldier
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Falaise De Fleur Soldier 04";
	ch.model = "Soldier_Fra2";
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Falaise_de_fleur_location_02";
	ch.location.group = "goto";
	ch.location.locator = "locator33";
	ch.Dialog.Filename = "Falaise De Fleur Soldier_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "FRANCE_SOLDIERS");
	ch.greeting = "Gr_falaise de fleur soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			// Soldier
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Falaise De Fleur Soldier 05";
	ch.model = "Soldier_Fra6";
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Falaise_de_fleur_location_02";
	ch.location.group = "goto";
	ch.location.locator = "locator32";
	ch.Dialog.Filename = "Falaise De Fleur Soldier_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "FRANCE_SOLDIERS");
	ch.greeting = "Gr_falaise de fleur soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			// Soldier
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Falaise De Fleur Soldier 06";
	ch.model = "Soldier_Fra";
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Falaise_de_fleur_location_02";
	ch.location.group = "goto";
	ch.location.locator = "locator34";
	ch.Dialog.Filename = "Falaise De Fleur Soldier_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "FRANCE_SOLDIERS");
	ch.greeting = "Gr_falaise de fleur soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			// Soldier
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Falaise De Fleur Soldier 07";
	ch.model = "Soldier_Fra2";
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Falaise_de_fleur_location_02";
	ch.location.group = "goto";
	ch.location.locator = "locator35";
	ch.Dialog.Filename = "Falaise De Fleur Soldier_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "FRANCE_SOLDIERS");
	ch.greeting = "Gr_falaise de fleur soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			// Soldier
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Falaise De Fleur Soldier 08";
	ch.model = "Soldier_Fra4";
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Falaise_de_fleur_location_02";
	ch.location.group = "goto";
	ch.location.locator = "locator30";
	ch.Dialog.Filename = "Falaise De Fleur Soldier_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "FRANCE_SOLDIERS");
	ch.greeting = "Gr_falaise de fleur soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			// Soldier
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Falaise De Fleur Soldier 09";
	ch.model = "Soldier_Fra6";
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Falaise_de_fleur_location_02";
	ch.location.group = "goto";
	ch.location.locator = "locator31";
	ch.Dialog.Filename = "Falaise De Fleur Soldier_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "FRANCE_SOLDIERS");
	ch.greeting = "Gr_falaise de fleur soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			// patrol
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Falaise De Fleur patrol 03";
	ch.model = "Soldier_Fra3";
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Falaise_de_fleur_location_02";
	ch.location.group = "goto";
	ch.location.locator = "locator14";
	ch.Dialog.Filename = "Patrol_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "FRANCE_SOLDIERS");
	ch.greeting = "Gr_Patrol";
	n = n + 1;

	makeref(ch,Characters[n]);			// patrol
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Falaise De Fleur patrol 04";
	ch.model = "Soldier_Fra";
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Falaise_de_fleur_location_02";
	ch.location.group = "goto";
	ch.location.locator = "locator15";
	ch.Dialog.Filename = "Patrol_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "FRANCE_SOLDIERS");
	ch.greeting = "Gr_Patrol";
	n = n + 1;

	makeref(ch,Characters[n]);			// Soldier
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Falaise De Fleur Soldier 10";
	ch.model = "Soldier_Fra4";
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Falaise_de_fleur_location_03";
	ch.location.group = "goto";
	ch.location.locator = "soldier01";
	ch.Dialog.Filename = "Falaise De Fleur Soldier_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "FRANCE_SOLDIERS");
	ch.greeting = "Gr_falaise de fleur soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			// Soldier
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Falaise De Fleur Soldier 11";
	ch.model = "Soldier_Fra2";
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Falaise_de_fleur_location_03";
	ch.location.group = "goto";
	ch.location.locator = "soldier02";
	ch.Dialog.Filename = "Falaise De Fleur Soldier_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "FRANCE_SOLDIERS");
	ch.greeting = "Gr_falaise de fleur soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			// Soldier
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Falaise De Fleur Soldier 12";
	ch.model = "Soldier_Fra";
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Falaise_de_fleur_location_03";
	ch.location.group = "goto";
	ch.location.locator = "locator36";
	ch.Dialog.Filename = "Falaise De Fleur Soldier_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "FRANCE_SOLDIERS");
	ch.greeting = "Gr_falaise de fleur soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			// Soldier
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Falaise De Fleur Soldier 13";
	ch.model = "Soldier_Fra5";
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Falaise_de_fleur_location_03";
	ch.location.group = "goto";
	ch.location.locator = "locator37";
	ch.Dialog.Filename = "Falaise De Fleur Soldier_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "FRANCE_SOLDIERS");
	ch.greeting = "Gr_falaise de fleur soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			// Soldier
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Falaise De Fleur Soldier 14";
	ch.model = "Soldier_Fra4";
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Falaise_de_fleur_location_03";
	ch.location.group = "goto";
	ch.location.locator = "locator38";
	ch.Dialog.Filename = "Falaise De Fleur Soldier_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "FRANCE_SOLDIERS");
	ch.greeting = "Gr_falaise de fleur soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			// Soldier
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Falaise De Fleur Soldier 15";
	ch.model = "Soldier_Fra3";
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Falaise_de_fleur_location_03";
	ch.location.group = "goto";
	ch.location.locator = "locator18";
	ch.Dialog.Filename = "Falaise De Fleur Soldier_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "FRANCE_SOLDIERS");
	ch.greeting = "Gr_falaise de fleur soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			// patrol
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Falaise De Fleur patrol 05";
	ch.model = "Soldier_Fra6";
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Falaise_de_fleur_location_03";
	ch.location.group = "goto";
	ch.location.locator = "locator9";
	ch.Dialog.Filename = "Patrol_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "FRANCE_SOLDIERS");
	ch.greeting = "Gr_Patrol";
	n = n + 1;

	makeref(ch,Characters[n]);			// patrol
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Falaise De Fleur patrol 06";
	ch.model = "Soldier_Fra3";
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Falaise_de_fleur_location_03";
	ch.location.group = "goto";
	ch.location.locator = "locator13";
	ch.Dialog.Filename = "Patrol_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "FRANCE_SOLDIERS");
	ch.greeting = "Gr_Patrol";
	n = n + 1;

	makeref(ch,Characters[n]);			// patrol
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Falaise De Fleur patrol 07";
	ch.model = "Soldier_Fra4";
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Falaise_de_fleur_location_03";
	ch.location.group = "goto";
	ch.location.locator = "locator21";
	ch.Dialog.Filename = "Patrol_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "FRANCE_SOLDIERS");
	ch.greeting = "Gr_Patrol";
	n = n + 1;

	makeref(ch,Characters[n]);			// Soldier
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Falaise De Fleur Soldier 14";
	ch.model = "Soldier_Fra3";
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Falaise_de_fleur_location_04";
	ch.location.group = "goto";
	ch.location.locator = "locator27";
	ch.Dialog.Filename = "Falaise De Fleur Soldier_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "FRANCE_SOLDIERS");
	ch.greeting = "Gr_falaise de fleur soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			// Soldier
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Falaise De Fleur Soldier 15";
	ch.model = "Soldier_Fra5";
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Falaise_de_fleur_location_04";
	ch.location.group = "goto";
	ch.location.locator = "locator28";
	ch.Dialog.Filename = "Falaise De Fleur Soldier_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "2";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "FRANCE_SOLDIERS");
	ch.greeting = "Gr_falaise de fleur soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			// Soldier
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Falaise De Fleur Soldier 16";
	ch.model = "Soldier_Fra4";
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Falaise_de_fleur_location_04";
	ch.location.group = "goto";
	ch.location.locator = "locator26";
	ch.Dialog.Filename = "Falaise De Fleur Soldier_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "4";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "FRANCE_SOLDIERS");
	ch.greeting = "Gr_falaise de fleur soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			// Soldier
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Falaise De Fleur Soldier 17";
	ch.model = "Soldier_Fra2";
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Falaise_de_fleur_location_04";
	ch.location.group = "goto";
	ch.location.locator = "locator25";
	ch.Dialog.Filename = "Falaise De Fleur Soldier_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "FRANCE_SOLDIERS");
	ch.greeting = "Gr_falaise de fleur soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			// patrol
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Falaise De Fleur patrol 08";
	ch.model = "Soldier_Fra";
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Falaise_de_fleur_location_04";
	ch.location.group = "goto";
	ch.location.locator = "locator8";
	ch.Dialog.Filename = "Patrol_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "FRANCE_SOLDIERS");
	ch.greeting = "Gr_Patrol";
	n = n + 1;

	makeref(ch,Characters[n]);			// Soldier
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Falaise De Fleur Soldier 18";
	ch.model = "Soldier_Fra";
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Falaise_de_fleur_location_05";
	ch.location.group = "goto";
	ch.location.locator = "locator31";
	ch.Dialog.Filename = "Falaise De Fleur Soldier_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "FRANCE_SOLDIERS");
	ch.greeting = "Gr_falaise de fleur soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			// Soldier
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Falaise De Fleur Soldier 19";
	ch.model = "Soldier_Fra4";
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Falaise_de_fleur_location_05";
	ch.location.group = "goto";
	ch.location.locator = "locator32";
	ch.Dialog.Filename = "Falaise De Fleur Soldier_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "2";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "FRANCE_SOLDIERS");
	ch.greeting = "Gr_falaise de fleur soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			// Soldier
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Falaise De Fleur Soldier 20";
	ch.model = "Soldier_Fra3";
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Falaise_de_fleur_location_05";
	ch.location.group = "goto";
	ch.location.locator = "locator30";
	ch.Dialog.Filename = "Falaise De Fleur Soldier_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "2";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "FRANCE_SOLDIERS");
	ch.greeting = "Gr_falaise de fleur soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			// Soldier
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Falaise De Fleur Soldier 21";
	ch.model = "Soldier_Fra6";
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Falaise_de_fleur_location_05";
	ch.location.group = "goto";
	ch.location.locator = "locator19";
	ch.Dialog.Filename = "Falaise De Fleur Soldier_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "FRANCE_SOLDIERS");
	ch.greeting = "Gr_falaise de fleur soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			// patrol
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Falaise De Fleur patrol 09";
	ch.model = "Soldier_Fra3";
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Falaise_de_fleur_location_05";
	ch.location.group = "goto";
	ch.location.locator = "locator16";
	ch.Dialog.Filename = "Patrol_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "FRANCE_SOLDIERS");
	ch.greeting = "Gr_Patrol";
	n = n + 1;

	makeref(ch,Characters[n]);			// patrol
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Falaise De Fleur patrol 10";
	ch.model = "Soldier_Fra2";
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Falaise_de_fleur_location_05";
	ch.location.group = "goto";
	ch.location.locator = "locator23";
	ch.Dialog.Filename = "Patrol_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "FRANCE_SOLDIERS");
	ch.greeting = "Gr_Patrol";
	n = n + 1;

	makeref(ch,Characters[n]);			// Soldier
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Falaise De Fleur Soldier 22";
	ch.model = "Soldier_Fra6";
	ch.sex = "man";
	ch.sound_type = "soldier";
		LAi_CharacterReincarnation(ch, true, true);
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Falaise_de_fleur_port_02";
	ch.location.group = "goto";
	ch.location.locator = "soldier_01";
	ch.Dialog.Filename = "Falaise De Fleur Soldier_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "4";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "FRANCE_SOLDIERS");
	ch.greeting = "Gr_falaise de fleur soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			// Soldier
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Falaise De Fleur Soldier 23";
	ch.model = "Soldier_Fra3";
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Falaise_de_fleur_port_02";
	ch.location.group = "goto";
	ch.location.locator = "soldier_02";
	ch.Dialog.Filename = "Falaise De Fleur Soldier_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "2";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "FRANCE_SOLDIERS");
	ch.greeting = "Gr_falaise de fleur soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			// Soldier
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Falaise De Fleur Soldier 24";
	ch.model = "Soldier_Fra5";
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Falaise_de_fleur_port_02";
	ch.location.group = "goto";
	ch.location.locator = "citizen07";
	ch.Dialog.Filename = "Falaise De Fleur Soldier_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "2";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "FRANCE_SOLDIERS");
	ch.greeting = "Gr_falaise de fleur soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			// patrol
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Falaise De Fleur patrol 11";
	ch.model = "Soldier_Fra2";
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Falaise_de_fleur_port_02";
	ch.location.group = "goto";
	ch.location.locator = "locator28";
	ch.Dialog.Filename = "Patrol_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.meeting = "0";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "FRANCE_SOLDIERS");
	ch.greeting = "Gr_Patrol";
	n = n + 1;

	return n;
}
	