
int CreateOfficersCharacters(int n)
{
	ref ch;

	makeref(ch,Characters[n]);		//Даниэль
	ch.name 	= "Danielle";
	ch.lastname = "Greene";
	ch.id		= "Danielle";
	ch.nation	= ENGLAND;
	ch.model	= "Danielle";
	ch.activity_begin = "0";
	ch.activity_end = "24";
	ch.sex = "woman";
	ch.luck = 4;
	GiveItem2Character(ch, "blade6");
	TakeNItems(ch,"potion1", Rand(4)+1);
	ch.equip.blade = "blade6";
	GiveItem2Character(ch, GUN_COMMON);
	ch.equip.gun = GUN_COMMON;
	ch.location	= "";
	ch.location.group = "";
	ch.location.locator = "";
	ch.Dialog.Filename = "Danielle_dialog.c";
	ch.greeting = "Gr_danielle";
	ch.rank 	= 4;
	ch.reputation = "50";
	ch.experience = CalculateExperienceFromRank(4)+ (CalculateExperienceFromRank(4)/10 + rand(4000));
	ch.skill.Leadership = "2";
	ch.skill.Fencing = "4";
	ch.skill.Sailing = "2";
	ch.skill.Accuracy = "3";
	ch.skill.Cannons = "2";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "0";
	ch.perks.list.LongRangeShoot = true;
	ch.Ship.Name = "Vertigo";
	ch.Ship.Type = SHIP_SCHOONER2_ENGLAND;
	ch.Ship.Cannons.Type = CANNON_TYPE_CANNON_LBS16;
	ch.ship.cargo.goods.bombs = 1000;
	ch.FaceId = 30;
	n = n + 1;

	makeref(ch,Characters[n]);			// Baldewyn Coffier  офицер казначей сидит в таверне.
	ch.name 	= "Baldewyn";
	ch.lastname 	= "Coffier";
	ch.id		= "Baldewyn Coffier";
	ch.loyality = 10;
	ch.alignment = "good";
	ch.model = "fatman2_1";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	TakeNItems(ch,"potion1", Rand(4)+1);
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "none";
	ch.location.group = "sit";
	ch.location.locator = "sit1";
	ch.homelocation	= "Falaise_de_fleur_tavern";
	ch.homelocation.group = "sit";
	ch.homelocation.locator = "sit1";
	ch.homestate = "sit";
	ch.Dialog.Filename = "Baldewyn Coffier_dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 3;
	ch.reputation = "60";
	ch.experience = CalculateExperienceFromRank(3)+ (CalculateExperienceFromRank(3)/10 + rand(3000));
	ch.skill.Leadership = "0";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "0";
	ch.skill.Accuracy = "0";
	ch.skill.Cannons = "0";
	ch.skill.Grappling = "0";
	ch.skill.Repair = "0";
	ch.skill.Defence = "0";
	ch.skill.Commerce = "5";
	ch.skill.Sneak = "0";
	ch.money = "0";
	ch.quest.meeting = "0";
	ch.quest.hire = "0";
	ch.perks.list.BasicCommerce = true;
	LAi_SetSitType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_NoRebirthEnable(ch);
	ch.greeting = "Gr_baldewyn coffier";
	n = n + 1;

	makeref(ch,Characters[n]);			// Ralph Fawn  боцман девушки.
	ch.name 	= "Ralph";
	ch.lastname 	= "Fawn";
	ch.id		= "Ralph Fawn";
	ch.model = "fawn";
	ch.sex = "man";
	ch.sound_type = "seaman";
	ch.location	= "none";
	ch.location.group = "none";
	ch.location.locator = "none";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.Dialog.Filename = "Ralph Fawn_dialog.c";
	ch.greeting = "Gr_Ralph Fawn";
	ch.nation = ENGLAND;
	ch.rank 	= 3;
	ch.reputation = "50";
	ch.experience = CalculateExperienceFromRank(3)+ (CalculateExperienceFromRank(3)/10 + rand(3000));
	ch.skill.Leadership = "2";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "3";
	ch.skill.Repair = "1";
	ch.skill.Defence = "2";
	ch.skill.Commerce = "0";
	ch.skill.Sneak = "0";
	ch.money = "0";
	ch.quest.meeting = "0";
	ch.quest.hire = "0";
	LAi_SetStayType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 10.0, 10.0);
	LAi_NoRebirthEnable(ch);
	n = n + 1;

	makeref(ch,Characters[n]);			// Edgar Attwood тюремщик на редмонде - канонир.
	ch.name 	= "Edgar";
	ch.lastname 	= "Attwood";
	ch.id		= "Edgar Attwood";
	ch.loyality = 10;
	ch.alignment = "bad";
	ch.model = "old_man2";
	ch.sex = "man";
	ch.sound_type = "pirate";
	TakeNItems(ch,"potion1", Rand(4)+1);
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Redmond_prison";
	ch.location.group = "goto";
	ch.location.locator = "goto13";
	ch.homelocation	= "Redmond_prison";
	ch.homelocation.group = "goto";
	ch.homelocation.locator = "goto13";
	ch.homestate = "citizen";
	ch.Dialog.Filename = "Edgar Attwood_dialog.c";
	ch.nation = ENGLAND;
	ch.rank 	= 5;
	ch.reputation = "35";
	ch.experience = CalculateExperienceFromRank(5)+ (CalculateExperienceFromRank(5)/10 + rand(5000));
	ch.skill.Leadership = "0";
	ch.skill.Fencing = "2";
	ch.skill.Sailing = "0";
	ch.skill.Accuracy = "5";
	ch.skill.Cannons = "6";
	ch.skill.Grappling = "0";
	ch.skill.Repair = "1";
	ch.skill.Defence = "0";
	ch.skill.Commerce = "0";
	ch.skill.Sneak = "0";
	ch.money = "0";
	ch.quest.meeting = "0";
	ch.quest.to_hire = "0";
	ch.perks.list.FastReload = true;
	ch.perks.list.HullDamageUp = true;
	ch.perks.list.BasicBattleState = true;
	LAi_SetCitizenType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_NoRebirthEnable(ch);
	ch.greeting = "Gr_Edgar Attwood";
	n = n + 1;

	makeref(ch,Characters[n]);			// Lucas Da Saldanha
	ch.name 	= "Lucas";
	ch.lastname 	= "Da Saldanha";
	ch.id		= "Lucas Da Saldanha";
	ch.loyality = 10;
	ch.alignment = "good";
	ch.model = "lucas";
	ch.sex = "man";
	ch.location	= "none";
	ch.location.group = "goto";
	ch.location.locator = "goto7";
	ch.homelocation	= "Muelle_residence";
	ch.homelocation.group = "goto";
	ch.homelocation.locator = "goto2";
	ch.homestate = "citizen";
	ch.Dialog.Filename = "Lucas Da Saldanha_dialog.c";
	ch.greeting = "Gr_Lucas Da Saldanha";
	ch.nation = SPAIN;
	ch.rank 	= 5;
	ch.reputation = "70";
	TakeNItems(ch,"potion1", Rand(4)+1);
	ch.experience = CalculateExperienceFromRank(5)+ (CalculateExperienceFromRank(5)/10 + rand(5000));
	ch.skill.Leadership = "3";
	ch.skill.Fencing = "6";
	ch.skill.Sailing = "0";
	ch.skill.Accuracy = "3";
	ch.skill.Cannons = "3";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "0";
	ch.skill.Sneak = "0";
	ch.money = "0";
	ch.perks.list.CriticalHit = true;
	ch.perks.list.Gunman = true;
	ch.quest.meeting = "0";
	LAi_SetStayType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_NoRebirthEnable(ch);
	n = n + 1;

	makeref(ch,Characters[n]);			// Изобретатель
	ch.name 	= "Clement";
	ch.lastname 	= "Barnabas";
	ch.lastname 	= "Aurentius";
	ch.id		= "Researcher";
	ch.model = "researcher";
	ch.sex = "man";
	ch.sound_type = "male_citizen";
	ch.location	= "none";
	ch.location.group = "goto";
	ch.location.locator = "goto7";
	ch.Dialog.Filename = "researcher_dialog.c";
	ch.greeting = "Gr_researcher";
	ch.nation = ENGLAND;
	ch.rank 	= 1;
	ch.reputation = "70";
	ch.experience = "0";
	ch.skill.Leadership = "0";
	ch.skill.Fencing = "0";
	ch.skill.Sailing = "0";
	ch.skill.Accuracy = "0";
	ch.skill.Cannons = "0";
	ch.skill.Grappling = "0";
	ch.skill.Repair = "9";
	ch.skill.Defence = "0";
	ch.skill.Commerce = "0";
	ch.skill.Sneak = "0";
	ch.money = "0";
	ch.quest.meeting = "0";
	ch.Ship.Name = "Astra";
	ch.Ship.Type = SHIP_TARTANE;
	ch.Ship.Stopped = true;
	ch.Ship.Cannons.Type = CANNON_TYPE_NONECANNON;
	LAi_SetCitizenType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_NoRebirthEnable(ch);
	LAi_SetImmortal(ch, true);
	n = n + 1;

	makeref(ch,Characters[n]);			//Leborio Drago worker in mine
	ch.name 	= "Leborio";
	ch.lastname 	= "Drago";
	ch.id		= "Leborio Drago";
	ch.loyality = 10;
	ch.alignment = "good";
	ch.model	= "blackman";
	ch.sex = "man";
	ch.location	= "Oxbay_mine";
	ch.location.group = "goto";
	ch.location.locator = "goto6";
	ch.homelocation	= "Falaise_de_fleur_port";
	ch.homelocation.group = "goto";
	ch.homelocation.locator = "goto4";
	ch.homestate = "citizen";
	ch.Dialog.Filename = "Leborio Drago_dialog.c";
	ch.greeting = "Gr_Leborio Drago";
	ch.nation = FRANCE;
	ch.rank 	= 4;
	ch.reputation = "42";
	TakeNItems(ch,"potion1", Rand(4)+1);
	ch.experience = CalculateExperienceFromRank(4)+ (CalculateExperienceFromRank(4)/10 + rand(4000));
	ch.skill.Leadership = "2";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "4";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "2";
	ch.skill.Defence = "2";
	ch.skill.Commerce = "0";
	ch.skill.Sneak = "0";
	ch.money = "0";
	ch.quest.hire = "";
	ch.perks.list.LightRepair = true;
	ch.perks.list.SharedExperience = true;
	LAi_SetCitizenType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_NoRebirthEnable(ch);
	n = n + 1;

	makeref(ch,Characters[n]);			// Gervasio Serrao - в таверне пиратского острова
	ch.name 	= "Gervasio";
	ch.lastname 	= "Serrao";
	ch.id		= "Gervasio Serrao";
	ch.model = "bocman4";
	ch.loyality = 10;
	ch.alignment = "bad";
	ch.sex = "man";
	ch.sound_type = "seaman";
	ch.nation	= PIRATE;
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Pirate_tavern";
	ch.location.group = "sit";
	ch.location.locator = "sit5";
	ch.homelocation	= "Pirate_tavern";
	ch.homelocation.group = "sit";
	ch.homelocation.locator = "sit5";
	ch.homestate = "sit";
	ch.Dialog.Filename = "Gervasio Serrao_dialog.c";
	ch.rank 	= 4;
	ch.reputation = "22";
	TakeNItems(ch,"potion1", Rand(4)+1);
	ch.experience = CalculateExperienceFromRank(4)+ (CalculateExperienceFromRank(4)/10 + rand(4000));
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "5";
	ch.skill.Sailing = "0";
	ch.skill.Accuracy = "0";
	ch.skill.Cannons = "0";
	ch.skill.Grappling = "5";
	ch.skill.Repair = "0";
	ch.skill.Defence = "0";
	ch.skill.Commerce = "0";
	ch.skill.Sneak = "0";
	ch.money = "0";
	ch.quest.hire = "0";
	ch.perks.list.Rush = true;
	LAi_SetSitType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_NoRebirthEnable(ch);
	ch.greeting = "Gr_Gervasio Serrao";
	n = n + 1;

	makeref(ch,Characters[n]);			// Clair Larrouse французский пират в таверне Исла Муэлле.
	ch.name 	= "Clair";
	ch.lastname 	= "Larrouse";
	ch.id		= "Clair Larrouse";
	ch.model = "corsair1_1";
	ch.sex = "man";
	ch.loyality = 10;
	ch.alignment = "bad";
	ch.nation	= FRANCE;
	ch.sound_type = "pirate";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "none";
	ch.location.group = "sit";
	ch.location.locator = "sit6";
	ch.homelocation	= "Muelle_tavern";
	ch.homelocation.group = "sit";
	ch.homelocation.locator = "sit6";
	ch.homestate = "sit";
	ch.Dialog.Filename = "Habitue_dialog.c";//"Clair Larrouse_dialog.c";
	ch.rank 	= 6;
	ch.reputation = "42";
	TakeNItems(ch,"potion1", Rand(4)+1);
	ch.experience = CalculateExperienceFromRank(6)+ (CalculateExperienceFromRank(6)/10 + rand(6000));
	ch.skill.Leadership = "2";
	ch.skill.Fencing = "5";
	ch.skill.Sailing = "4";
	ch.skill.Accuracy = "3";
	ch.skill.Cannons = "2";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "0";
	ch.skill.Defence = "2";
	ch.skill.Commerce = "0";
	ch.skill.Sneak = "0";
	ch.money = "0";
	ch.quest.meeting = "0";
	ch.quest.goldmine = "0";
	ch.Ship.Name = "Cheri";
	ch.Ship.Type = SHIP_BRIG_FRANCE;
	ch.Ship.Stopped = true;
	ch.Ship.Cannons.Type = CANNON_TYPE_CANNON_LBS12;
	ch.perks.list.CriticalHit = true;
	ch.perks.list.BasicDefense = true;
	ch.perks.list.CrewDamageUp = true;
	LAi_SetSitType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_NoRebirthEnable(ch);
	ch.greeting = "Gr_Clair Larrouse";
	n = n + 1;

	makeref(ch,Characters[n]);			// Jaoquin De Masse  мальтийский рыцарь.
	ch.name 	= "Jaoquin";
	ch.lastname 	= "De Masse";
	ch.id		= "Jaoquin De Masse";
	ch.model = "maltese";
	ch.sex = "man";
	ch.loyality = 10;
	ch.nation	= SPAIN;
	ch.alignment = "good";
	ch.sound_type = "priest";
	GiveItem2Character(ch, "blade8");
	ch.equip.blade = "blade8";
	ch.location	= "none";
	ch.location.group = "none";
	ch.location.locator = "none";
	ch.homelocation	= "Muelle_church";
	ch.homelocation.group = "goto";
	ch.homelocation.locator = "goto2";
	ch.homestate = "citizen";
	ch.Dialog.Filename = "Jaoquin De Masse_dialog.c";
	ch.greeting = "Gr_Jaoquin de masse";
	ch.rank 	= 8;
	ch.reputation = "75";
	TakeNItems(ch,"potion1", Rand(4)+1);
	ch.experience = CalculateExperienceFromRank(8)+ (CalculateExperienceFromRank(8)/10 + rand(8000));
	ch.skill.Leadership = "6";
	ch.skill.Fencing = "7";
	ch.skill.Sailing = "0";
	ch.skill.Accuracy = "3";
	ch.skill.Cannons = "0";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "4";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "0";
	ch.money = "0";
	ch.quest.meeting = "0";
	ch.perks.list.CriticalHit = true;
	ch.perks.list.BasicDefense = true;
	ch.perks.list.AdvancedDefense = true;
	ch.perks.list.IronWill = true;
	LAi_SetMerchantType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_NoRebirthEnable(ch);
	n = n + 1;

	makeref(ch,Characters[n]);			// Nigel Blythe.
	ch.name 	= "Nigel";
	ch.lastname 	= "Blythe";
	ch.id		= "Nigel Blythe";
	ch.model = "will_2";
	ch.sex = "man";
	ch.loyality = 10;
	ch.nation	= PIRATE;
	ch.alignment = "bad";
	ch.location	= "QC_town";
	ch.location.group = "goto";
	ch.location.locator = "character4";
	ch.homelocation	= "QC_town";
	ch.homelocation.group = "goto";
	ch.homelocation.locator = "character4";
	ch.homestate = "citizen";
	ch.Dialog.Filename = "Nigel Blythe_dialog.c";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.rank 	= 4;
	ch.reputation = "24";
	TakeNItems(ch,"potion1", Rand(4)+1);
	ch.experience = CalculateExperienceFromRank(4)+ (CalculateExperienceFromRank(4)/10 + rand(4000));
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "5";
	ch.skill.Sailing = "2";
	ch.skill.Accuracy = "4";
	ch.skill.Cannons = "0";
	ch.skill.Grappling = "4";
	ch.skill.Repair = "0";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "0";
	ch.skill.Sneak = "0";
	ch.money = "0";
	ch.perks.list.BasicDefense = true;
	ch.perks.list.CriticalHit = true;
	LAi_SetMerchantType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_NoRebirthEnable(ch);
	ch.greeting = "Gr_Nigel Blythe";
	n = n + 1;

	makeref(ch,Characters[n]);			// Artois Voysey.
	ch.name 	= "Artois";
	ch.lastname 	= "Voysey";
	ch.id		= "Artois Voysey";
	ch.model = "man6";
	ch.sex = "man";
	ch.act.type = "merchant";
	ch.loyality = 10;
	ch.alignment = "good";
	ch.nation	= FRANCE;
	GiveItem2Character(ch, "blade6");
	ch.equip.blade = "blade6";
	ch.location	= "QC_town";
	ch.location.group = "goto";
	ch.location.locator = "goto5";
	ch.homelocation	= "QC_town";
	ch.homelocation.group = "goto";
	ch.homelocation.locator = "goto5";
	ch.homestate = "citizen";
	ch.Dialog.Filename = "Artois Voysey_dialog.c";
	ch.rank 	= 4;
	ch.reputation = "64";
	TakeNItems(ch,"potion1", Rand(4)+1);
	ch.experience = CalculateExperienceFromRank(4)+ (CalculateExperienceFromRank(4)/10 + rand(4000));
	ch.skill.Leadership = "3";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "5";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "0";
	ch.skill.Repair = "0";
	ch.skill.Defence = "0";
	ch.skill.Commerce = "3";
	ch.skill.Sneak = "0";
	ch.money = "0";
	ch.perks.list.ShipSpeedUp = true;
	LAi_SetMerchantType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 8.0, 8.0);
	LAi_NoRebirthEnable(ch);
	ch.greeting = "Gr_Artois Voysey";
	n = n + 1;

	//Hitman

	makeref(ch,Characters[n]);			// Amerigo Vieira
	ch.name 	= "Amerigo";
	ch.lastname 	= "Vieira";
	ch.id		= "Amerigo Vieira";
	ch.model = "pirat9";
	ch.sound_type = "pirate";
	ch.sex = "man";
	ch.loyality = 7;
	ch.alignment = "bad";
	GiveItem2Character(ch, "blade14");
	ch.equip.blade = "blade14";
	ch.nation	= PORTUGAL;
	GiveItem2Character(ch, GUN_COMMON);
	ch.equip.gun = GUN_COMMON;
	ch.location	= "none";
	ch.location.group = "";
	ch.location.locator = "";
	ch.homelocation	= "";
	ch.homelocation.group = "";
	ch.homelocation.locator = "";
	ch.homestate = "stay";
	ch.Dialog.Filename = "Amerigo Vieira_dialog.c";
	ch.greeting = "Gr_Amerigo Vieira";
	ch.rank 	= 9;
	ch.reputation = "50";
	TakeNItems(ch,"potion1", Rand(4)+1);
	ch.experience = CalculateExperienceFromRank(9)+ (CalculateExperienceFromRank(9)/10 + rand(9000));
	ch.skill.Leadership = "3";
	ch.skill.Fencing = "10";
	ch.skill.Sailing = "0";
	ch.skill.Accuracy = "0";
	ch.skill.Cannons = "0";
	ch.skill.Grappling = "6";
	ch.skill.Repair = "0";
	ch.skill.Defence = "0";
	ch.skill.Commerce = "0";
	ch.skill.Sneak = "2";
	ch.money = "0";
	ch.quest.meeting = "0";
	ch.perks.list.BasicDefense = true;
	ch.perks.list.AdvancedDefense = true;
	ch.perks.list.SwordplayProfessional = true;
	ch.perks.list.CriticalHit = true;
	ch.perks.list.Gunman = true;
	LAi_SetStayType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 150.0, 150.0);
	LAi_NoRebirthEnable(ch);
	n = n + 1;

	makeref(ch,Characters[n]);		// Florens Clauss
	ch.name 	= "Florens";
	ch.lastname = "Clauss";
	ch.id		= "Florens Clauss";
	ch.model	= "bocman3";
	ch.sex = "man";
	ch.loyality = 10;
	ch.alignment = "bad";
	GiveItem2Character(ch, "blade4");
	ch.equip.blade = "blade4";
	ch.location	= "";
	ch.location.group = "";
	ch.location.locator = "";
	ch.Dialog.Filename = "Clauss_dialog.c";
	ch.nation = PIRATE;
	ch.rank 	= 6;
	ch.reputation = "48";
	TakeNItems(ch,"potion1", Rand(4)+1);
	ch.experience = CalculateExperienceFromRank(6)+ (CalculateExperienceFromRank(6)/10 + rand(6000));
	ch.skill.Leadership = "3";
	ch.skill.Fencing = "4";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "4";
	ch.skill.Repair = "1";
	ch.skill.Defence = "5";
	ch.skill.Commerce = "0";
	ch.skill.Sneak = "0";
	ch.perks.list.BasicDefense = true;
	ch.perks.list.LongRangeGrappling = true;
	ch.money = "1";
	LAi_SetCitizenType(ch);
	ch.greeting = "Gr_Clauss";
	n = n + 1;

	makeref(ch,Characters[n]);			//Rys Bloom
	ch.name 	= "Rys";
	ch.lastname 	= "Bloom";
	ch.id		= "Rys Bloom";
	ch.model	= "Chameleon";
	ch.sex = "man";
	ch.loyality = 15;
	ch.alignment = "good";
	ch.sound_type = "seaman";
	GiveItem2Character(ch, "blade6");
	ch.equip.blade = "blade6";
	ch.location	= "Redmond_port";
	ch.location.group = "goto";
	ch.location.locator = "cityzen_1";
	ch.Dialog.Filename = "Rys Bloom_dialog.c";
	ch.greeting = "Gr_Rys Bloom";
	ch.rank 	= 1;
	ch.reputation = "45";
	TakeNItems(ch,"potion1", Rand(4)+1);
	ch.experience = CalculateExperienceFromRank(1)+ (CalculateExperienceFromRank(1)/10 + rand(500));
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "0";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "0";
	ch.skill.Commerce = "0";
	ch.skill.Sneak = "0";
	ch.money = "0";
	ch.quest.help = "0";
	ch.quest.dialog = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);		// Random Officer 0
	ch.name 	= "";
	ch.lastname = "";
	ch.id		= "Enc_Officer_00";
	ch.model	= "";
	ch.sex = "man";
	ch.location	= "";
	ch.location.group = "";
	ch.location.locator = "";
	ch.Dialog.Filename = "";
	ch.nation = PIRATE;
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "";
	ch.skill.Leadership = "";
	ch.skill.Fencing = "";
	ch.skill.Sailing = "";
	ch.skill.Accuracy = "";
	ch.skill.Cannons = "";
	ch.skill.Grappling = "";
	ch.skill.Repair = "";
	ch.skill.Defence = "";
	ch.skill.Commerce = "";
	ch.skill.Sneak = "";

	n = n + 1;


	makeref(ch,Characters[n]);		// Random Officer 1
	ch.name 	= "";
	ch.lastname = "";
	ch.id		= "Enc_Officer_01";
	ch.model	= "";
	ch.sex = "man";
	ch.location	= "";
	ch.location.group = "";
	ch.location.locator = "";
	ch.Dialog.Filename = "";
	ch.nation = PIRATE;
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "";
	ch.skill.Leadership = "";
	ch.skill.Fencing = "";
	ch.skill.Sailing = "";
	ch.skill.Accuracy = "";
	ch.skill.Cannons = "";
	ch.skill.Grappling = "";
	ch.skill.Repair = "";
	ch.skill.Defence = "";
	ch.skill.Commerce = "";
	ch.skill.Sneak = "";

	n = n + 1;

	makeref(ch,Characters[n]);		// Random Officer 2
	ch.name 	= "";
	ch.lastname = "";
	ch.id		= "Enc_Officer_02";
	ch.model	= "";
	ch.sex = "man";
	ch.location	= "";
	ch.location.group = "";
	ch.location.locator = "";
	ch.Dialog.Filename = "";
	ch.nation = PIRATE;
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "";
	ch.skill.Leadership = "";
	ch.skill.Fencing = "";
	ch.skill.Sailing = "";
	ch.skill.Accuracy = "";
	ch.skill.Cannons = "";
	ch.skill.Grappling = "";
	ch.skill.Repair = "";
	ch.skill.Defence = "";
	ch.skill.Commerce = "";
	ch.skill.Sneak = "";

	n = n + 1;

	makeref(ch,Characters[n]);		// Random Officer 3
	ch.name 	= "";
	ch.lastname = "";
	ch.id		= "Enc_Officer_03";
	ch.model	= "";
	ch.sex = "man";
	ch.location	= "";
	ch.location.group = "";
	ch.location.locator = "";
	ch.Dialog.Filename = "";
	ch.nation = PIRATE;
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "";
	ch.skill.Leadership = "";
	ch.skill.Fencing = "";
	ch.skill.Sailing = "";
	ch.skill.Accuracy = "";
	ch.skill.Cannons = "";
	ch.skill.Grappling = "";
	ch.skill.Repair = "";
	ch.skill.Defence = "";
	ch.skill.Commerce = "";
	ch.skill.Sneak = "";

	n = n + 1;

	makeref(ch,Characters[n]);		// Random Officer 4
	ch.name 	= "";
	ch.lastname = "";
	ch.id		= "Enc_Officer_04";
	ch.model	= "";
	ch.sex = "man";
	ch.location	= "";
	ch.location.group = "";
	ch.location.locator = "";
	ch.Dialog.Filename = "";
	ch.nation = PIRATE;
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "";
	ch.skill.Leadership = "";
	ch.skill.Fencing = "";
	ch.skill.Sailing = "";
	ch.skill.Accuracy = "";
	ch.skill.Cannons = "";
	ch.skill.Grappling = "";
	ch.skill.Repair = "";
	ch.skill.Defence = "";
	ch.skill.Commerce = "";
	ch.skill.Sneak = "";

	n = n + 1;


	makeref(ch,Characters[n]);		// Random Officer 5
	ch.name 	= "";
	ch.lastname = "";
	ch.id		= "Enc_Officer_05";
	ch.model	= "";
	ch.sex = "man";
	ch.location	= "";
	ch.location.group = "";
	ch.location.locator = "";
	ch.Dialog.Filename = "";
	ch.nation = PIRATE;
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "";
	ch.skill.Leadership = "";
	ch.skill.Fencing = "";
	ch.skill.Sailing = "";
	ch.skill.Accuracy = "";
	ch.skill.Cannons = "";
	ch.skill.Grappling = "";
	ch.skill.Repair = "";
	ch.skill.Defence = "";
	ch.skill.Commerce = "";
	ch.skill.Sneak = "";

	n = n + 1;

	makeref(ch,Characters[n]);		// Random Officer 6
	ch.name 	= "";
	ch.lastname = "";
	ch.id		= "Enc_Officer_06";
	ch.model	= "";
	ch.sex = "man";
	ch.location	= "";
	ch.location.group = "";
	ch.location.locator = "";
	ch.Dialog.Filename = "";
	ch.nation = PIRATE;
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "";
	ch.skill.Leadership = "";
	ch.skill.Fencing = "";
	ch.skill.Sailing = "";
	ch.skill.Accuracy = "";
	ch.skill.Cannons = "";
	ch.skill.Grappling = "";
	ch.skill.Repair = "";
	ch.skill.Defence = "";
	ch.skill.Commerce = "";
	ch.skill.Sneak = "";

	n = n + 1;


	makeref(ch,Characters[n]);		// Random Officer 7
	ch.name 	= "";
	ch.lastname = "";
	ch.id		= "Enc_Officer_07";
	ch.model	= "";
	ch.sex = "man";
	ch.location	= "";
	ch.location.group = "";
	ch.location.locator = "";
	ch.Dialog.Filename = "";
	ch.nation = PIRATE;
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "";
	ch.skill.Leadership = "";
	ch.skill.Fencing = "";
	ch.skill.Sailing = "";
	ch.skill.Accuracy = "";
	ch.skill.Cannons = "";
	ch.skill.Grappling = "";
	ch.skill.Repair = "";
	ch.skill.Defence = "";
	ch.skill.Commerce = "";
	ch.skill.Sneak = "";

	n = n + 1;


	makeref(ch,Characters[n]);		// Random Officer 8
	ch.name 	= "";
	ch.lastname = "";
	ch.id		= "Enc_Officer_08";
	ch.model	= "";
	ch.sex = "man";
	ch.location	= "";
	ch.location.group = "";
	ch.location.locator = "";
	ch.Dialog.Filename = "";
	ch.nation = PIRATE;
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "";
	ch.skill.Leadership = "";
	ch.skill.Fencing = "";
	ch.skill.Sailing = "";
	ch.skill.Accuracy = "";
	ch.skill.Cannons = "";
	ch.skill.Grappling = "";
	ch.skill.Repair = "";
	ch.skill.Defence = "";
	ch.skill.Commerce = "";
	ch.skill.Sneak = "";

	n = n + 1;


	makeref(ch,Characters[n]);		// Random Officer 9
	ch.name 	= "";
	ch.lastname = "";
	ch.id		= "Enc_Officer_09";
	ch.model	= "";
	ch.sex = "man";
	ch.location	= "";
	ch.location.group = "";
	ch.location.locator = "";
	ch.Dialog.Filename = "";
	ch.nation = PIRATE;
	ch.rank 	= 1;
	ch.reputation = "50";
	ch.experience = "";
	ch.skill.Leadership = "";
	ch.skill.Fencing = "";
	ch.skill.Sailing = "";
	ch.skill.Accuracy = "";
	ch.skill.Cannons = "";
	ch.skill.Grappling = "";
	ch.skill.Repair = "";
	ch.skill.Defence = "";
	ch.skill.Commerce = "";
	ch.skill.Sneak = "";

	n = n + 1;

	return n;
}