
int CreateOxbayCharacters(int n)
{
	ref ch;
//Location: Oxbay Pier (an entrance to the town from the pier)

	makeref(ch,Characters[n]);		//Бартоломью Парднер - Местный капитан каботажного плавания
	ch.name 	= "Bartholomew";
	ch.lastname 	= "Pardner";
	ch.id		= "Bartholomew Pardner";
	ch.model	= "bocman1";
	ch.sex = "man";
	ch.sound_type = "seaman";
	ch.location	= "Oxbay_port";
	ch.location.group = "goto";
	ch.location.locator = "goto9";
	ch.Dialog.Filename = "Oxbay citizen_dialog.c";
	ch.greeting = "Gr_Oxbay Citizen";
	ch.quest.area = "Oxbay";
	ch.nation = ENGLAND;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			//Оливер Блакстер - местный рыбак и перевозчик
	ch.name 	= "Olyver";
	ch.lastname 	= "Blaxter";
	ch.id		= "Olyver Blaxter";
	ch.model	= "fisherman1";
	ch.sex = "man";
	ch.sound_type = "seaman";
	ch.location	= "Oxbay_port";
	ch.location.group = "goto";
	ch.location.locator = "goto6";
	ch.Dialog.Filename = "oxbay citizen_dialog.c";
	ch.greeting = "Gr_Oxbay Citizen";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			//Soldier на входе в город
	ch.name 	= "Soldier";
	ch.lastname 	= " ";
	ch.id		= "Ox_soldier_1";
	ch.model	= "soldier_eng";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Oxbay_port";
	ch.location.group = "goto";
	ch.location.locator = "goto23";
	ch.Dialog.Filename = "Oxbay Soldier_dialog.c";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "5";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Oxbay Soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			//Soldier на входе в город
	ch.name 	= "Soldier";
	ch.lastname 	= " ";
	ch.id		= "Ox_soldier_2";
	ch.model	= "soldier_eng2";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Oxbay_port";
	ch.location.group = "goto";
	ch.location.locator = "goto21";
	ch.Dialog.Filename = "oxbay soldier_dialog.c";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Oxbay Soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			//Patrol
	ch.name 	= "Soldier";
	ch.lastname 	= " ";
	ch.id		= "Ox_patrol_1";
	ch.model	= "soldier_eng3";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Oxbay_port";
	ch.location.group = "goto";
	ch.location.locator = "goto18";
	ch.Dialog.Filename = "patrol_dialog.c";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Patrol";
	n = n + 1;

	makeref(ch,Characters[n]);			//Patrol
	ch.name 	= "Soldier";
	ch.lastname 	= " ";
	ch.id		= "Ox_patrol_2";
	ch.model	= "soldier_eng2";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Oxbay_port";
	ch.location.group = "goto";
	ch.location.locator = "goto12";
	ch.Dialog.Filename = "patrol_dialog.c";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Patrol";
	n = n + 1;

	makeref(ch,Characters[n]);			//Беатрис Эпплгейт
	ch.name 	= "Beatrice";
	ch.lastname 	= "Applegate";
	ch.id		= "Beatrice Applegate";
	ch.model	= "towngirl1_1";
	ch.sound_type = "female_citizen";
	ch.sex = "woman";
	ch.location	= "Oxbay_port";
	ch.location.group = "goto";
	ch.location.locator = "goto18";
	ch.Dialog.Filename = "Oxbay citizen_dialog.c";
	ch.greeting = "Gr_Woman_English Citizen";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			//Бреннан Эпплгейт
	ch.name 	= "Brennan";
	ch.lastname 	= "Applegate";
	ch.id		= "Brennan Applegate";
	ch.model	= "man4";
	ch.sound_type = "male_citizen";
	ch.sex = "man";
	ch.location	= "Oxbay_port";
	ch.location.group = "goto";
	ch.location.locator = "goto13";
	ch.Dialog.Filename = "oxbay citizen_dialog.c";
	ch.greeting = "Gr_Oxbay Citizen";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

//Location: Oxbay Town

	makeref(ch,Characters[n]);			//Soldier near Seagates of Oxbay
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Ox_Soldier_3";
	ch.model	= "soldier_eng6";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Oxbay_town";
	ch.location.group = "goto";
	ch.location.locator = "goto3";
	ch.Dialog.Filename = "Oxbay soldier_dialog.c";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "6";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Oxbay Soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			//Soldier near Seagates of Oxbay
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Ox_soldier_4";
	ch.model	= "soldier_eng3";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Oxbay_town";
	ch.location.group = "goto";
	ch.location.locator = "goto4";
	ch.Dialog.Filename = "Oxbay soldier_dialog.c";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "5";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Oxbay Soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			//Soldier near Seagates of Oxbay
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Ox_Soldier_5";
	ch.model	= "soldier_eng4";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Oxbay_town";
	ch.location.group = "goto";
	ch.location.locator = "goto1";
	ch.Dialog.Filename = "Oxbay soldier_dialog.c";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "6";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Oxbay Soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			//Soldier near Seagates of Oxbay
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Ox_soldier_6";
	ch.model	= "soldier_eng2";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Oxbay_town";
	ch.location.group = "goto";
	ch.location.locator = "goto2";
	ch.Dialog.Filename = "Oxbay soldier_dialog.c";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "5";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Oxbay Soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			//Patrol
	ch.name 	= "Soldier";
	ch.lastname 	= " ";
	ch.id		= "Ox_patrol_3";
	ch.model	= "soldier_eng4";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Oxbay_town";
	ch.location.group = "goto";
	ch.location.locator = "goto31";
	ch.Dialog.Filename = "patrol_dialog.c";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Patrol";
	n = n + 1;

	makeref(ch,Characters[n]);			//Patrol
	ch.name 	= "Soldier";
	ch.lastname 	= " ";
	ch.id		= "Ox_patrol_4";
	ch.model	= "soldier_eng6";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Oxbay_town";
	ch.location.group = "goto";
	ch.location.locator = "goto20";
	ch.Dialog.Filename = "patrol_dialog.c";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Patrol";
	n = n + 1;

	makeref(ch,Characters[n]);			//Мозес Блинман
	ch.name 	= "Moses";
	ch.lastname 	= "Blinman";
	ch.id		= "Moses Blinman";
	ch.model	= "fatman1";
	ch.sound_type = "male_citizen";
	ch.sex = "man";
	ch.location	= "Oxbay_town";
	ch.location.group = "goto";
	ch.location.locator = "goto12";
	ch.Dialog.Filename = "Oxbay citizen_dialog.c";
	ch.greeting = "Gr_Oxbay Citizen";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			// Эд Постль - торговец в палатке
	ch.name 	= "Ed";
	ch.lastname 	= "Postle";
	ch.id		= "Ed Postle";
	ch.model	= "Man2";
	ch.sound_type = "merchant";
	ch.sex = "man";
	ch.location	= "Oxbay_town";
	ch.location.group = "merchant";
	ch.location.locator = "merchant1";
	ch.Dialog.Filename = "Oxbay citizen_dialog.c";
	ch.greeting = "Gr_Oxbay Citizen";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetMerchantType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			//Лавиния Оулт
	ch.name 	= "Lavinia";
	ch.lastname 	= "Ault";
	ch.id		= "Lavinia Ault";
	ch.model	= "towngirl1";
	ch.sound_type = "female_citizen";
	ch.sex = "woman";
	ch.location	= "Oxbay_town";
	ch.location.group = "goto";
	ch.location.locator = "goto28";
	ch.Dialog.Filename = "Oxbay citizen_dialog.c";
	ch.greeting = "Gr_Woman_English Citizen";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			//Флэнн Викерс
	ch.name 	= "Flann";
	ch.lastname 	= "Vickers";
	ch.id		= "Flann Vickers";
	ch.model	= "sailor2";
	ch.sound_type = "seaman";
	ch.sex = "man";
	ch.location	= "Oxbay_port";
	ch.location.group = "merchant";
	ch.location.locator = "merchant1";
	ch.Dialog.Filename = "Item Trader_dialog.c";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetMerchantType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");

	n = n + 1;

	makeref(ch,Characters[n]);		//Питер Дэшвуд
	ch.name 	= "Peter";
	ch.lastname 	= "Dashwood";
	ch.id		= "Peter Dashwood";
	ch.model	= "man1";
	ch.sound_type = "male_citizen";
	ch.sex = "man";
	ch.location	= "Oxbay_town";
	ch.location.group = "goto";
	ch.location.locator = "goto8";
	ch.Dialog.Filename = "Oxbay citizen_dialog.c";
	ch.greeting = "Gr_Oxbay Citizen";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.pay100 = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			//Флора Дебни
	ch.name 	= "Flora";
	ch.lastname 	= "Debney";
	ch.id		= "Flora Debney";
	ch.model	= "towngirl3";
	ch.sex = "woman";
	ch.sound_type = "female_citizen";
	ch.location	= "Oxbay_town";
	ch.location.group = "goto";
	ch.location.locator = "goto21";
	ch.Dialog.Filename = "Oxbay citizen_dialog.c";
	ch.greeting = "Gr_Woman_English Citizen";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			//A pirate that offers teaching
	ch.name 	= "One-eyed";
	ch.lastname 	= "Sean";
	ch.id		= "One-eyed Sean";
	ch.model	= "Corsair2";
	ch.model.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.act.type = "citizen";
	ch.sound_type = "pirate";
	ch.location	= "Oxbay_town_01";
	ch.location.group = "goto";
	ch.location.locator = "goto9";
	ch.Dialog.Filename = "Oxbay citizen_dialog.c";
	ch.greeting = "Gr_Oxbay Citizen";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetCitizenType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

//Location: Oxbay Tavern

	makeref(ch,Characters[n]);			// Эверард Гордон
	ch.name 	= "Everard";
	ch.lastname 	= "Gordon";
	ch.id		= "Everard Gordon";
	ch.model	= "old_man1";
	ch.sex = "man";
	ch.location	= "Oxbay_tavern";
	ch.location.group = "merchant";
	ch.location.locator = "goto1";
	ch.Dialog.Filename = "Everard Gordon_dialog.c";
	ch.greeting = "Gr_Everard Gordon";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.work = "";
	ch.money = "10";
	LAi_SetBarmanType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);		// Oxbay_officiant
	ch.name 	= "Mary";
	ch.lastname = "Bekker";
	ch.id		= "Oxbay_officiant";
	ch.model	= "towngirl5";
	ch.sex = "woman";
	ch.sound_type = "female_citizen";
	ch.location	= "Oxbay_tavern";
	ch.location.group = "goto";
	ch.location.locator = "goto5";
	ch.Dialog.Filename = "Eng_Officiant_dialog.c";
	ch.nation = ENGLAND;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	ch.quest.sex = 0;
	ch.sex.time = 0;
	LAi_SetWaitressType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			// Ральф Матер
	ch.name 	= "Raulf";
	ch.lastname 	= "Mather";
	ch.id		= "Raulf Mather";
	ch.model	= "bocman";
	ch.sound_type = "seaman";
	ch.sex = "man";
	ch.location	= "Oxbay_tavern";
	ch.location.group = "sit";
	ch.location.locator = "sit1";
	ch.Dialog.Filename = "Habitue_dialog.c";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.last_theme = "";
	LAi_SetSitType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			// Triston Bonger
	ch.name 	= "Triston";
	ch.lastname 	= "Bonger";
	ch.id		= "Triston Bonger";
	ch.model	= "man6_1";
	ch.sound_type = "male_citizen";
	ch.sex = "man";
	ch.location	= "Oxbay_tavern";
	ch.location.group = "sit";
	ch.location.locator = "sit3";
	ch.Dialog.Filename = "Habitue_dialog.c";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.last_theme = "";
	LAi_SetSitType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			// Peter Blaxter
	ch.name 	= "Peter";
	ch.lastname 	= "Blaxter";
	ch.id		= "Peter Blaxter";
	ch.model	= "man3";
	ch.sound_type = "male_citizen";
	ch.sex = "man";
	ch.location	= "Oxbay_tavern";
	ch.location.group = "sit";
	ch.location.locator = "sit3";
	ch.Dialog.Filename = "Habitue_dialog.c";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.last_theme = "";
	LAi_SetSitType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

//Location: Oxbay Store (Where the church stands)

	makeref(ch,Characters[n]);			//Алан Майлдс
	ch.name 	= "Alan";
	ch.lastname 	= "Milds";
	ch.id		= "Alan Milds";
	ch.model	= "storeman2";
	ch.sex = "man";
	ch.location	= "Oxbay_store";
	ch.location.group = "sit";
	ch.location.locator = "sit1";
	ch.Dialog.Filename = "Alan Milds_dialog.c";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.trade_date = "";
	ch.quest.item_date = "";
	LAi_SetStayType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	ch.greeting = "Gr_Alan Milds";
	n = n + 1;

//Location: Oxbay Shipyard (Where the church stands)

	makeref(ch,Characters[n]);			//Оуэн Мак Дори
	ch.name 	= "Oweyn";
	ch.lastname 	= "McDorey";
	ch.id		= "Oweyn McDorey";
	ch.model	= "Sailor6";
	ch.sex = "man";
	ch.location	= "Oxbay_shipyard";
	ch.location.group = "sit";
	ch.location.locator = "sit_1";
	ch.Dialog.Filename = "Oweyn McDorey_dialog.c";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetHuberType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	ch.greeting = "Gr_Oweyn McDorey";
	n = n + 1;

//Location: Oxbay Town Exit

	makeref(ch,Characters[n]);
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Ox_soldier_7";
	ch.model	= "soldier_eng3";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Oxbay_town_exit";
	ch.location.group = "goto";
	ch.location.locator = "citizen010";
	ch.Dialog.Filename = "Oxbay soldier_dialog.c";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "5";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Oxbay Soldier";
	n = n + 1;

	makeref(ch,Characters[n]);
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Ox_soldier_8";
	ch.model	= "soldier_eng3";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Oxbay_town_exit";
	ch.location.group = "goto";
	ch.location.locator = "citizen09";
	ch.Dialog.Filename = "Oxbay soldier_dialog.c";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "5";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Oxbay Soldier";
	n = n + 1;

// Soldiers are called "Green_soldier_n"
// Location: Greenford_port

	makeref(ch,Characters[n]);			// Evan Hart -- fisherman
	ch.name 	= "Evan";
	ch.lastname = "Hart";
	ch.id		= "Evan Hart";
	ch.model	= "fisherman";
	ch.sound_type = "seaman";
	ch.sex = "man";
	ch.location	= "Greenford_port";
	ch.location.group = "goto";
	ch.location.locator = "goto18";
	ch.Dialog.Filename = "Greenford Citizen_dialog.c";
	ch.greeting = "Gr_Greenford Citizen";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			// Peter Butner -- Chelovek
	ch.name 	= "Peter";
	ch.lastname = "Butner";
	ch.id		= "Peter Butner";
	ch.model	= "Chelovek";
	ch.sound_type = "male_citizen";
	ch.sex = "man";
	ch.location	= "Greenford_port";
	ch.location.group = "goto";
	ch.location.locator = "goto10";
	ch.Dialog.Filename = "Greenford Citizen_dialog.c";
	ch.greeting = "Gr_Greenford Citizen";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			// Celia Shedder -- towngirl2
	ch.name 	= "Celia";
	ch.lastname = "Shedder";
	ch.id		= "Celia Shedder";
	ch.model	= "towngirl2_1";
	ch.sound_type = "female_citizen";
	ch.sex = "woman";
	ch.location	= "Greenford_port";
	ch.location.group = "goto";
	ch.location.locator = "goto14";
	ch.Dialog.Filename = "Greenford Citizen_dialog.c";
	ch.greeting = "Gr_Woman_English Citizen";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;


	makeref(ch,Characters[n]);			// John Coy -- 
	ch.name 	= "John";
	ch.lastname = "Coy";
	ch.id		= "John Coy";
	ch.model	= "chelovek1";
	ch.sound_type = "male_citizen";
	ch.sex = "man";
	ch.location	= "Greenford_port";
	ch.location.group = "goto";
	ch.location.locator = "goto16";
	ch.Dialog.Filename = "Greenford Citizen_dialog.c";
	ch.greeting = "Gr_Greenford Citizen";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			// Walter Peate -- man4
	ch.name 	= "Walter";
	ch.lastname = "Peate";
	ch.id		= "Walter Peate";
	ch.model	= "sailor3";
	ch.sound_type = "seaman";
	ch.sex = "man";
	ch.location	= "Greenford_port";
	ch.location.group = "goto";
	ch.location.locator = "goto5";
	ch.Dialog.Filename = "Greenford Citizen_dialog.c";
	ch.greeting = "Gr_Greenford Citizen";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			// Gabriel Damerall -- Old_man1
	ch.name 	= "Gabriel";
	ch.lastname = "Damerall";
	ch.id		= "Gabriel Damerall";
	ch.model	= "Old_man1";
	ch.sound_type = "male_citizen";
	ch.sex = "man";
	ch.location	= "Greenford_port";
	ch.location.group = "goto";
	ch.location.locator = "goto3";
	ch.Dialog.Filename = "Greenford Citizen_dialog.c";
	ch.greeting = "Gr_Greenford Citizen";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			// Soldier near the exit from port
	ch.name 	= "Soldier";
	ch.lastname = "";
	ch.id		= "Green_soldier_1";
	ch.model	= "Soldier_Eng";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Greenford_port";
	ch.location.group = "goto";
	ch.location.locator = "goto23";
	ch.Dialog.Filename = "Greenford soldier_dialog.c";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Greenford Soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			// Soldier near the exit from port -- another one
	ch.name 	= "Soldier";
	ch.lastname = "";
	ch.id		= "Green_soldier_2";
	ch.model	= "Soldier_Eng3";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Greenford_port";
	ch.location.group = "goto";
	ch.location.locator = "goto24";
	ch.Dialog.Filename = "Greenford soldier_dialog.c";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Greenford Soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			// Patrol
	ch.name 	= "Soldier";
	ch.lastname = "";
	ch.id		= "Green_patrol_1";
	ch.model	= "Soldier_Eng5";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Greenford_port";
	ch.location.group = "goto";
	ch.location.locator = "goto22";
	ch.Dialog.Filename = "patrol_dialog.c";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "4";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Patrol";
	n = n + 1;

	makeref(ch,Characters[n]);			// Patrol
	ch.name 	= "Soldier";
	ch.lastname = "";
	ch.id		= "Green_patrol_2";
	ch.model	= "Soldier_Eng4";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Greenford_port";
	ch.location.group = "goto";
	ch.location.locator = "goto16";
	ch.Dialog.Filename = "patrol_dialog.c";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Patrol";
	n = n + 1;


// Location: Greenford_town

	makeref(ch,Characters[n]);			//Soldier near prison
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Eng_soldier_40";
	ch.model	= "soldier_eng2";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Greenford_town";
	ch.location.group = "goto";
	ch.location.locator = "goto20";
	ch.Dialog.Filename = "Greenford soldier_dialog.c";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "5";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Greenford Soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			//Soldier near prison
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Eng_soldier_41";
	ch.model	= "soldier_eng6";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Greenford_town";
	ch.location.group = "goto";
	ch.location.locator = "goto41";
	ch.Dialog.Filename = "Greenford soldier_dialog.c";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Greenford Soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			// Soldier near the entrance to the town from port
	ch.name 	= "Soldier";
	ch.lastname = "";
	ch.id		= "Green_soldier_3";
	ch.model	= "Soldier_Eng";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Greenford_town";
	ch.location.group = "goto";
	ch.location.locator = "goto8";
	ch.Dialog.Filename = "Greenford Soldier_dialog.c";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Greenford Soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			// Soldier near the entrance to the town from port -- another one
	ch.name 	= "Soldier";
	ch.lastname = "";
	ch.id		= "Green_soldier_4";
	ch.model	= "Soldier_Eng2";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Greenford_town";
	ch.location.group = "goto";
	ch.location.locator = "goto40";
	ch.Dialog.Filename = "Greenford Soldier_dialog.c";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Greenford Soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			// Patrol
	ch.name 	= "Soldier";
	ch.lastname = "";
	ch.id		= "Green_patrol_3";
	ch.model	= "Soldier_Eng4";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Greenford_town";
	ch.location.group = "goto";
	ch.location.locator = "goto4";
	ch.Dialog.Filename = "patrol_dialog.c";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "4";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Patrol";
	n = n + 1;

	makeref(ch,Characters[n]);			// Patrol
	ch.name 	= "Soldier";
	ch.lastname = "";
	ch.id		= "Green_patrol_4";
	ch.model	= "Soldier_Eng5";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Greenford_town";
	ch.location.group = "goto";
	ch.location.locator = "goto27";
	ch.Dialog.Filename = "patrol_dialog.c";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "4";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Patrol";
	n = n + 1;

	makeref(ch,Characters[n]);			// Patrol
	ch.name 	= "Soldier";
	ch.lastname = "";
	ch.id		= "Green_patrol_41";
	ch.model	= "Soldier_Eng5";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Greenford_town";
	ch.location.group = "goto";
	ch.location.locator = "goto17";
	ch.Dialog.Filename = "patrol_dialog.c";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "4";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Patrol";
	n = n + 1;

	makeref(ch,Characters[n]);			// Soldier near the exit from town
	ch.name 	= "Soldier";
	ch.lastname = "";
	ch.id		= "Green_soldier_5";
	ch.model	= "Soldier_Eng6";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Greenford_town";
	ch.location.group = "goto";
	ch.location.locator = "goto35";
	ch.Dialog.Filename = "Greenford Soldier_dialog.c";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Greenford Soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			// Soldier near the the exit from town -- another one
	ch.name 	= "Soldier";
	ch.lastname = "";
	ch.id		= "Green_soldier_6";
	ch.model	= "Soldier_Eng";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Greenford_town";
	ch.location.group = "goto";
	ch.location.locator = "goto36";
	ch.Dialog.Filename = "Greenford Soldier_dialog.c";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Greenford Soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			// Soldier near the 2nd exit from town
	ch.name 	= "Soldier";
	ch.lastname = "";
	ch.id		= "Green_soldier_7";
	ch.model	= "Soldier_Eng2";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Greenford_town";
	ch.location.group = "goto";
	ch.location.locator = "goto22";
	ch.Dialog.Filename = "Greenford Soldier_dialog.c";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Greenford Soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			// Soldier near the the 2nd exit from town -- another one
	ch.name 	= "Soldier";
	ch.lastname = "";
	ch.id		= "Green_soldier_8";
	ch.model	= "Soldier_Eng3";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Greenford_town";
	ch.location.group = "goto";
	ch.location.locator = "goto39";
	ch.Dialog.Filename = "Greenford Soldier_dialog.c";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Greenford Soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			// Bernard Gosling -- korsar
	ch.name 	= "Bernard";
	ch.lastname = "Gosling";
	ch.id		= "Bernard Gosling";
	ch.model	= "korsar";
	ch.sound_type = "pirate";
	ch.sex = "man";
	ch.location	= "Greenford_town";
	ch.location.group = "goto";
	ch.location.locator = "goto5";
	ch.Dialog.Filename = "Greenford Citizen_dialog.c";
	ch.greeting = "Gr_Greenford Citizen";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			// Garry Ankers -- Brodyaga
	ch.name 	= "Garry";
	ch.lastname = "Ankers";
	ch.id		= "Garry Ankers";
	ch.model	= "Brodyaga";
	ch.sound_type = "male_citizen";
	ch.sex = "man";
	ch.location	= "Greenford_town";
	ch.location.group = "goto";
	ch.location.locator = "goto13";
	ch.Dialog.Filename = "Greenford Citizen_dialog.c";
	ch.greeting = "Gr_Greenford Citizen";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "0";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			// Susannah Lazar -- towngirl3
	ch.name 	= "Susannah";
	ch.lastname = "Lazar";
	ch.id		= "Susannah Lazar";
	ch.model	= "towngirl3";;
	ch.sound_type = "female_citizen";
	ch.sex = "woman";
	ch.location	= "Greenford_town";
	ch.location.group = "goto";
	ch.location.locator = "goto12";
	ch.Dialog.Filename = "Greenford Citizen_dialog.c";
	ch.greeting = "Gr_Woman_English Citizen";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "0";
	LAi_SetMerchantType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			// Michael Collop -- man2
	ch.name 	= "Michael";
	ch.lastname = "Collop";
	ch.id		= "Michael Collop";
	ch.model	= "man2";
	ch.sound_type = "male_citizen";
	ch.sex = "man";
	ch.location	= "Greenford_town";
	ch.location.group = "goto";
	ch.location.locator = "goto15";
	ch.Dialog.Filename = "Greenford Citizen_dialog.c";
	ch.greeting = "Gr_Greenford Citizen";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			// Edgar Malter -- man3
	ch.name 	= "Edgar";
	ch.lastname = "Malter";
	ch.id		= "Edgar Malter";
	ch.model	= "man3";
	ch.sound_type = "male_citizen";
	ch.sex = "man";
	ch.location	= "Greenford_town";
	ch.location.group = "goto";
	ch.location.locator = "goto38";
	ch.Dialog.Filename = "Greenford Citizen_dialog.c";
	ch.greeting = "Gr_Greenford Citizen";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			// Alan Newman -- man6
	ch.name 	= "Alan";
	ch.lastname = "Newman";
	ch.id		= "Alan Newman";
	ch.model	= "man6";
	ch.sound_type = "male_citizen";
	ch.sex = "man";
	ch.location	= "Greenford_town";
	ch.location.group = "goto";
	ch.location.locator = "goto17";
	ch.Dialog.Filename = "Greenford Citizen_dialog.c";
	ch.greeting = "Gr_Greenford Citizen";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			// Audrey Proude -- towngirl1
	ch.name 	= "Audrey";
	ch.lastname = "Proude";
	ch.id		= "Audrey Proude";
	ch.model	= "towngirl1";
	ch.sound_type = "female_citizen";
	ch.sex = "woman";
	ch.location	= "Greenford_town";
	ch.location.group = "goto";
	ch.location.locator = "goto33";
	ch.Dialog.Filename = "Greenford Citizen_dialog.c";
	ch.greeting = "Gr_Woman_English Citizen";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;


// Location: Greenford_Store

	makeref(ch,Characters[n]);			// John  Filbert --
	ch.name 	= "John";
	ch.lastname = "Filbert";
	ch.id		= "John  Filbert";
	ch.model	= "Storeman";
	ch.sex = "man";
	ch.location	= "Greenford_Store";
	ch.location.group = "sit";
	ch.location.locator = "sit1";
	ch.Dialog.Filename = "John  Filbert_dialog.c";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	ch.quest.trade_date = "";
	ch.quest.item_date = "";
	LAi_SetStayType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	ch.greeting = "Gr_John  Filbert";
	n = n + 1;


// Location: Greenford_shipyard


	makeref(ch,Characters[n]);			// David Fairweather -- man1
	ch.name 	= "David";
	ch.lastname = "Fairweather";
	ch.id		= "David Fairweather";
	ch.model	= "man1";
	ch.sex = "man";
	ch.location	= "Greenford_shipyard";
	ch.location.group = "sit";
	ch.location.locator = "sit1";
	ch.Dialog.Filename = "David Fairweather_dialog.c";
	ch.greeting = "Gr_David Fairweather";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetHuberType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;


// Location: Greenford_Tevern


	makeref(ch,Characters[n]);			// Simon Hanpool -- Chameleon (tavern keeper)
	ch.name 	= "Simon";
	ch.lastname = "Hanpool";
	ch.id		= "Simon Hanpool";
	ch.model	= "man2";
	ch.sex = "man";
	ch.location	= "Greenford_Tavern";
	ch.location.group = "merchant";
	ch.location.locator = "goto3";
	ch.Dialog.Filename = "Simon Hanpool_dialog.c";
	ch.greeting = "Gr_Simon Hanpool";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.repqtation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	ch.work = "";
	LAi_SetBarmanType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			// Ralph Damerell -- Corsair3
	ch.name 	= "Ralph";
	ch.lastname = "Damerell";
	ch.id		= "Ralph Damerell";
	ch.model	= "Corsair3";
	ch.sound_type = "pirate";
	ch.sex = "man";
	ch.location	= "Greenford_Tavern";
	ch.location.group = "sit";
	ch.location.locator = "sit5";
	ch.Dialog.Filename = "Habitue_dialog.c";
	ch.greeting = "Gr_Ralph Damerell";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	ch.quest.last_theme = "";
	LAi_SetSitType(ch);
	LAi_SetLoginTime(ch, 4.0, 19.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;


	makeref(ch,Characters[n]);			// Frederyk Kember -- man4
	ch.name 	= "Frederyk";
	ch.lastname = "Kember";
	ch.id		= "Frederyk Kember";
	ch.model	= "man4";
	ch.sound_type = "male_citizen";
	ch.sex = "man";
	ch.location	= "Greenford_Tavern";
	ch.location.group = "sit";
	ch.location.locator = "sit1";
	ch.Dialog.Filename = "Habitue_dialog.c";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	LAi_SetSitType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);		// Conceicao_officiant
	ch.name 	= "Nadine";
	ch.lastname = "Jansen";
	ch.id		= "Greenford_officiant";
	ch.model	= "towngirl2";
	ch.sex = "woman";
	ch.sound_type = "female_citizen";
	ch.location	= "Greenford_tavern";
	ch.location.group = "goto";
	ch.location.locator = "goto6";
	ch.Dialog.Filename = "Eng_Officiant_dialog.c";
	ch.nation = ENGLAND;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	ch.quest.sex = 0;
	ch.sex.time = 0;
	LAi_SetWaitressType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	//Greenford prison

	makeref(ch,Characters[n]);		//Коммендант тюрьмы на Гринфорде
	ch.name 	= "Ronald";
	ch.lastname 	= "Blacklock";
	ch.id		= "Greenford Prison Commendant";
	ch.model	= "offic_eng";
	ch.sex = "man";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.location	= "Greenford_prison";
	ch.location.group = "sit";
	ch.location.locator = "sit1";
	ch.Dialog.Filename = "Greenford Commander_dialog.c";
	ch.nation = ENGLAND;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "6";
	ch.skill.Fencing = "9";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "6";
	ch.skill.Cannons = "5";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "8";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetHuberType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Greenford Commander";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	GiveItem2Character(ch, "Pistol1");
	ch.equip.gun = "Pistol1";
	n = n + 1;

	makeref(ch,Characters[n]);			//Soldier in prison
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Eng_soldier_38";
	ch.model	= "soldier_eng5";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Greenford_prison";
	ch.location.group = "goto";
	ch.location.locator = "goto16";
	ch.Dialog.Filename = "Greenford soldier_dialog.c";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "6";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Greenford Soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			//Soldier in prison
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Eng_soldier_39";
	ch.model	= "soldier_eng4";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Greenford_prison";
	ch.location.group = "goto";
	ch.location.locator = "goto14";
	ch.Dialog.Filename = "Greenford soldier_dialog.c";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "4";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Greenford Soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			//Soldier in Greenford_exit
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Green_exit_soldier_01";
	ch.model	= "soldier_eng5";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Greenford_town_exit";
	ch.location.group = "goto";
	ch.location.locator = "goto8";
	ch.Dialog.Filename = "Greenford soldier_dialog.c";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "6";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Greenford Soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			//Soldier in Greenford_exit
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Green_exit_soldier_02";
	ch.model	= "soldier_eng2";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Greenford_town_exit";
	ch.location.group = "goto";
	ch.location.locator = "goto9";
	ch.Dialog.Filename = "Greenford soldier_dialog.c";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "4";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Greenford Soldier";
	n = n + 1;

	//Greenford mine

	makeref(ch,Characters[n]);			//Soldier in mine
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Mine_soldier_01";
	ch.model	= "soldier_eng6";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Oxbay_mine";
	ch.location.group = "goto";
	ch.location.locator = "goto9";
	ch.Dialog.Filename = "Mine soldier_dialog.c";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "6";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Mine Soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			//Soldier in mine
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Mine_soldier_02";
	ch.model	= "soldier_eng2";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Oxbay_mine";
	ch.location.group = "goto";
	ch.location.locator = "goto10";
	ch.Dialog.Filename = "Mine soldier_dialog.c";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "6";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Mine Soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			//Soldier in mine
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Mine_soldier_03";
	ch.model	= "soldier_eng5";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Oxbay_mine";
	ch.location.group = "goto";
	ch.location.locator = "goto11";
	ch.Dialog.Filename = "Mine soldier_dialog.c";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "6";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Mine Soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			//Soldier in mine
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Mine_soldier_04";
	ch.model	= "soldier_eng6";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Oxbay_mine";
	ch.location.group = "goto";
	ch.location.locator = "goto12";
	ch.Dialog.Filename = "Mine soldier_dialog.c";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "6";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Mine Soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			//worker in mine
	ch.name 	= "Miner";
	ch.lastname 	= "";
	ch.id		= "Miner_01";
	ch.model	= "rabwhite";
	ch.sound_type = "worker";
	ch.sex = "man";
	ch.location	= "Oxbay_mine";
	ch.location.group = "goto";
	ch.location.locator = "goto2";
	ch.Dialog.Filename = "Miner_dialog.c";
	ch.greeting = "Gr_Miner";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetCitizenType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 60.0, 60.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			//worker in mine
	ch.name 	= "Miner";
	ch.lastname 	= "";
	ch.id		= "Miner_02";
	ch.model	= "rabwhite";
	ch.sound_type = "worker";
	ch.sex = "man";
	ch.location	= "Oxbay_mine";
	ch.location.group = "goto";
	ch.location.locator = "goto5";
	ch.Dialog.Filename = "Miner_dialog.c";
	ch.greeting = "Gr_Miner";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetCitizenType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 60.0, 60.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			//worker in mine
	ch.name 	= "Miner";
	ch.lastname 	= "";
	ch.id		= "Miner_03";
	ch.model	= "rabWhite";
	ch.sound_type = "worker";
	ch.sex = "man";
	ch.location	= "Oxbay_mine";
	ch.location.group = "goto";
	ch.location.locator = "goto8";
	ch.Dialog.Filename = "Miner_dialog.c";
	ch.greeting = "Gr_Miner";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetCitizenType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 60.0, 60.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			//worker in mine
	ch.name 	= "Miner";
	ch.lastname 	= "";
	ch.id		= "Miner_05";
	ch.model	= "RabWhite";
	ch.sound_type = "worker";
	ch.sex = "man";
	ch.location	= "Oxbay_mine";
	ch.location.group = "goto";
	ch.location.locator = "goto3";
	ch.Dialog.Filename = "Miner_dialog.c";
	ch.greeting = "Gr_Miner";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetCitizenType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 60.0, 60.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			//Mines Commander
	ch.name 	= "Mines Commander";
	ch.lastname 	= "";
	ch.id		= "Mine_Commander";
	ch.model	= "offic_eng";
	ch.act.sound_type = "soldier";
	ch.sex = "man";
	GiveItem2Character(ch, GUN_COMMON);
	ch.equip.gun = GUN_COMMON;
	GiveItem2Character(ch, BLADE_LONG);
	ch.equip.blade = BLADE_LONG;
	ch.location	= "Mines_commander_house";
	ch.location.group = "goto";
	ch.location.locator = "goto3";
	ch.Dialog.Filename = "Mine Commander_dialog.c";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "6";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 100.0, 100.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Mine Commander";
	n = n + 1;

	makeref(ch,Characters[n]);			//Soldier in canyon
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Mine_soldier_05";
	ch.model	= "soldier_eng3";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Oxbay_canyon";
	ch.location.group = "merchant";
	ch.location.locator = "goto22";
	ch.Dialog.Filename = "Mine soldier_dialog.c";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "6";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Mine Soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			//Soldier in canyon
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Mine_soldier_06";
	ch.model	= "soldier_eng";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Oxbay_canyon";
	ch.location.group = "merchant";
	ch.location.locator = "goto23";
	ch.Dialog.Filename = "Mine soldier_dialog.c";
	ch.rank 	= 1;
	ch.nation = ENGLAND;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "6";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Mine Soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			//Father Jerald
	ch.name 	= "Father";
	ch.lastname 	= "Jerald";
	ch.id		= "Father Jerald";
	ch.model	= "monk";
	ch.sound_type = "priest";
	ch.sex = "man";
	ch.location	= "Greenford_church";
	ch.location.group = "goto";
	ch.location.locator = "goto11";
	ch.Dialog.Filename = "Father jerald_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetPriestType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	ch.greeting = "Gr_Father Jerald";
	n = n + 1;

	makeref(ch,Characters[n]);			//Gilbert Ballester
	ch.name 	= "Gilbert";
	ch.lastname 	= "Ballester";
	ch.id		= "Gilbert Ballester";
	ch.model	= "monk2";
	ch.sound_type = "priest";
	ch.sex = "man";
	ch.location	= "greenford_church";
	ch.location.group = "goto";
	ch.location.locator = "goto12";
	ch.Dialog.Filename = "Gilbert Ballester_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetPriestType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	ch.greeting = "Gr_Gilbert Ballester";
	n = n + 1;

	return n;
}