
int CreateRedmondCharacters(int n)
{
	ref ch;
//Location: Redmond Pier (an entrance to the town from the pier)

	makeref(ch,Characters[n]);		//Laurence Wellman - port administrator
	ch.name 	= "Laurence";
	ch.lastname 	= "Wellman";
	ch.id		= "Laurence Wellman";
	ch.model	= "man3";
	ch.sex = "man";
	ch.location	= "Redmond_Head_port_house";
	ch.sound_type = "male_citizen";
	ch.location.group = "goto";
	ch.location.locator = "locator1";
	ch.Dialog.Filename = "Laurence Wellman_dialog.c";
	ch.greeting = "Gr_Laurence Wellman";
	ch.nation = ENGLAND;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetStayType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			//Soldier на входе в город
	ch.name 	= "Soldier";
	ch.lastname 	= " ";
	ch.id		= "Red_soldier_1";
	ch.model	= "soldier_eng2";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Redmond_port";
	ch.location.group = "goto";
	ch.location.locator = "soldier_1";
	ch.Dialog.Filename = "Redmond Soldier_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Redmond Soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			//Soldier на входе в город
	ch.name 	= "Soldier";
	ch.lastname 	= " ";
	ch.id		= "Red_soldier_2";
	ch.model	= "soldier_eng3";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Redmond_port";
	ch.location.group = "goto";
	ch.location.locator = "soldier_2";
	ch.Dialog.Filename = "redmond soldier_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Redmond Soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			//Patrol
	ch.name 	= "Soldier";
	ch.lastname 	= " ";
	ch.id		= "Red_patrol_1";
	ch.model	= "soldier_eng5";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Redmond_port";
	ch.location.group = "goto";
	ch.location.locator = "goto_58";
	ch.Dialog.Filename = "Patrol_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Patrol";
	n = n + 1;

	makeref(ch,Characters[n]);			//Patrol
	ch.name 	= "Soldier";
	ch.lastname 	= " ";
	ch.id		= "Red_patrol_2";
	ch.model	= "soldier_eng4";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Redmond_port";
	ch.location.group = "goto";
	ch.location.locator = "goto_22";
	ch.Dialog.Filename = "Patrol_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Patrol";
	n = n + 1;

	makeref(ch,Characters[n]);			//грузчик в порту
	ch.name 	= "Docker";
	ch.lastname 	= "";
	ch.id		= "Red_Docker_1";
	ch.model	= "black_corsair";
	ch.sound_type = "worker";
	ch.sex = "man";
	ch.location	= "Redmond_port";
	ch.location.group = "goto";
	ch.location.locator = "goto_59";
	ch.Dialog.Filename = "redmond citizen_dialog.c";
	ch.greeting = "Gr_Redmond Citizen";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			//грузчик в порту
	ch.name 	= "Docker";
	ch.lastname 	= "";
	ch.id		= "Red_Docker_2";
	ch.model	= "man5";
	ch.sound_type = "worker";
	ch.sex = "man";
	ch.location	= "Redmond_port";
	ch.location.group = "goto";
	ch.location.locator = "goto_18";
	ch.Dialog.Filename = "redmond citizen_dialog.c";
	ch.greeting = "Gr_Redmond Citizen";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			//торговец в порту
	ch.name 	= "Randolf";
	ch.lastname 	= "Potter";
	ch.id		= "Randolf Potter";
	ch.model	= "man4";
	ch.sound_type = "merchant";
	ch.sex = "man";
	ch.location	= "Redmond_port";
	ch.location.group = "goto";
	ch.location.locator = "cityzen_5";
	ch.Dialog.Filename = "Item trader_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetMerchantType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			//торговец в порту
	ch.name 	= "Brian";
	ch.lastname 	= "Prew";
	ch.id		= "Brian Prew";
	ch.model	= "searcher";
	ch.sound_type = "merchant";
	ch.sex = "man";
	ch.location	= "Redmond_port";
	ch.location.group = "goto";
	ch.location.locator = "cityzen_4";
	ch.Dialog.Filename = "Item trader_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetMerchantType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			//Джиллиан Эттербери
	ch.name 	= "Gillian";
	ch.lastname 	= "Atterbury";
	ch.id		= "Gillian Atterbury";
	ch.model	= "towngirl2";
	ch.sound_type = "female_citizen";
	ch.sex = "woman";
	ch.location	= "Redmond_port";
	ch.location.group = "goto";
	ch.location.locator = "goto_51";
	ch.Dialog.Filename = "redmond citizen_dialog.c";
	ch.greeting = "Gr_Woman_English Citizen";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			//Гриффит Пибоди - представитель верфи
	ch.name 	= "Griffith";
	ch.lastname 	= "Peabody";
	ch.id		= "Griffith Peabody";
	ch.model	= "Searcher";
	ch.sound_type = "male_citizen";
	ch.sex = "man";
	ch.location	= "Redmond_port";
	ch.location.group = "goto";
	ch.location.locator = "goto_39";
	ch.Dialog.Filename = "redmond citizen_dialog.c";
	ch.greeting = "Gr_Redmond Citizen";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);		//Henry the beggar
	ch.name 	= "Henry";
	ch.lastname 	= "";
	ch.id		= "Henry";
	ch.model	= "brodyaga";
	ch.sound_type = "poorman";
	ch.sex = "man";
	ch.location	= "Redmond_town_01";
	ch.location.group = "goto";
	ch.location.locator = "citizen03";
	ch.Dialog.Filename = "Redmond Citizen_dialog.c";
	ch.greeting = "Gr_Redmond Citizen";
	ch.greeting = "Gr_Henry";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.pay100 = "0";
	LAi_SetPoorType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			//Soldier near Seagates of Redmond
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Eng_Soldier_1";
	ch.model	= "soldier_eng5";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Redmond_town_01";
	ch.location.group = "goto";
	ch.location.locator = "soldier01";
	ch.Dialog.Filename = "Redmond soldier_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "6";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Redmond Soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			//Soldier near Seagates of Redmond
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Eng_soldier_2";
	ch.model	= "soldier_eng6";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Redmond_town_01";
	ch.location.group = "goto";
	ch.location.locator = "soldier02";
	ch.Dialog.Filename = "Redmond soldier_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "5";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Redmond Soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			//Patrol
	ch.name 	= "Soldier";
	ch.lastname 	= " ";
	ch.id		= "Red_patrol_3";
	ch.model	= "soldier_eng3";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Redmond_town_01";
	ch.location.group = "goto";
	ch.location.locator = "goto18";
	ch.Dialog.Filename = "Patrol_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Patrol";
	n = n + 1;

	makeref(ch,Characters[n]);			//Patrol
	ch.name 	= "Soldier";
	ch.lastname 	= " ";
	ch.id		= "Red_patrol_4";
	ch.model	= "soldier_eng5";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Redmond_town_01";
	ch.location.group = "goto";
	ch.location.locator = "goto26";
	ch.Dialog.Filename = "Patrol_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Patrol";
	n = n + 1;

/*	makeref(ch,Characters[n]);			//Docker near Seagates of Redmond
	ch.name 	= "Docker";
	ch.lastname 	= "";
	ch.id		= "Eng_Docker_1";
	ch.model	= "black_corsair";
	ch.sex = "man";
	ch.sound_type = "worker";
	ch.location	= "Redmond_town_01";
	ch.location.group = "goto";
	ch.location.locator = "citizen05";
	ch.Dialog.Filename = "redmond citizen_dialog.c";
	ch.greeting = "Gr_Redmond Citizen";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;*/

/*	makeref(ch,Characters[n]);			//Docker near Seagates of Redmond
	ch.name 	= "Docker";
	ch.lastname 	= "";
	ch.id		= "Eng_Docker_2";
	ch.model	= "man4";
	ch.model.sex = "man";
	ch.sound_type = "worker";
	ch.location	= "Redmond_town_01";
	ch.location.group = "goto";
	ch.location.locator = "goto_3";
	ch.Dialog.Filename = "redmond citizen_dialog.c";
	ch.greeting = "Gr_Redmond Citizen";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;*/

	makeref(ch,Characters[n]);			// Jane Attwell
	ch.name 	= "Jane";
	ch.lastname 	= "Attwell";
	ch.id		= "Jane Attwell";
	ch.model	= "towngirl7";
	ch.sound_type = "female_citizen";
	ch.fanatic = "1";
	ch.church = "Redmond_church";
	ch.church.loc = "goto3";
	ch.back.location = "Redmond_town_01";
	ch.back.locator = "citizen06";
	ch.sex = "woman";
	ch.location	= "Redmond_town_01";
	ch.location.group = "goto";
	ch.location.locator = "citizen06";
	ch.Dialog.Filename = "Redmond Citizen_dialog.c";
	ch.greeting = "Gr_Woman_English Citizen";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

//Location: Redmond Church Plaza (Where the church stands)

	makeref(ch,Characters[n]);			//Father Bernard
	ch.name 	= "Father";
	ch.lastname 	= "Bernard";
	ch.id		= "Father Bernard";
	ch.model	= "monk";
	ch.sound_type = "priest";
	ch.sex = "man";
	ch.location	= "Redmond_church";
	ch.location.group = "goto";
	ch.location.locator = "goto11";
	ch.Dialog.Filename = "Father Bernard_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.quest.church_help = "0";
	ch.money = "10";
	LAi_SetPriestType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	ch.greeting = "Gr_Father Bernard";
	n = n + 1;

	makeref(ch,Characters[n]);			//Robert Blewett
	ch.name 	= "Robert";
	ch.lastname 	= "Blewett";
	ch.id		= "Robert Blewett";
	ch.model	= "old_man1";
	ch.sound_type = "male_citizen";
	ch.fanatic = "1";
	ch.church = "Redmond_church";
	ch.church.loc = "goto4";
	ch.back.location = "Redmond_town_03";
	ch.back.locator = "cityzen03";
	ch.sex = "man";
	ch.model.animation = "man";
	ch.location	= "Redmond_town_03";
	ch.location.group = "goto";
	ch.location.locator = "cityzen03";
	ch.Dialog.Filename = "Redmond Citizen_dialog.c";
	ch.greeting = "Gr_Redmond Citizen";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			//Miles Biddick
	ch.name 	= "Miles";
	ch.lastname 	= "Biddick";
	ch.id		= "Miles Biddick";
	ch.model	= "Searcher";
	ch.sound_type = "male_citizen";
	ch.sex = "man";
	ch.location	= "Redmond_town_03";
	ch.location.group = "goto";
	ch.location.locator = "cityzen06";
	ch.Dialog.Filename = "Redmond Citizen_dialog.c";
	ch.greeting = "Gr_Redmond Citizen";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			//Gareth Swingler
	ch.name 	= "Gareth";
	ch.lastname 	= "Swingler";
	ch.id		= "Gareth Swingler";
	ch.model	= "man2";
	ch.sound_type = "male_citizen";
	ch.sex = "man";
	ch.location	= "Redmond_town_03";
	ch.location.group = "goto";
	ch.location.locator = "cityzen04";
	ch.Dialog.Filename = "Redmond Citizen_dialog.c";
	ch.greeting = "Gr_Redmond Citizen";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			//Eamonn Larter
	ch.name 	= "Eamonn";
	ch.lastname 	= "Larter";
	ch.id		= "Eamonn Larter";
	ch.model	= "man1_2";
	ch.sound_type = "male_citizen";
	ch.fanatic = "1";
	ch.church = "Redmond_church";
	ch.church.loc = "goto6";
	ch.back.location = "Redmond_town_03";
	ch.back.locator = "cityzen07";
	ch.sex = "man";
	ch.location	= "Redmond_town_03";
	ch.location.group = "goto";
	ch.location.locator = "cityzen07";
	ch.Dialog.Filename = "Redmond Citizen_dialog.c";
	ch.greeting = "Gr_Redmond Citizen";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "3";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			//Soldier near gates
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Eng_soldier_3";
	ch.model	= "soldier_eng4";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Redmond_town_03";
	ch.location.group = "goto";
	ch.location.locator = "soldier01";
	ch.Dialog.Filename = "Redmond soldier_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "7";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Redmond Soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			//Soldier near gates
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Eng_Soldier_4";
	ch.model	= "soldier_eng3";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Redmond_town_03";
	ch.location.group = "goto";
	ch.location.locator = "soldier02";
	ch.Dialog.Filename = "Redmond Soldier_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "4";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Redmond Soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			//Patrol
	ch.name 	= "Soldier";
	ch.lastname 	= " ";
	ch.id		= "Red_patrol_7";
	ch.model	= "soldier_eng2";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Redmond_town_03";
	ch.location.group = "goto";
	ch.location.locator = "goto33";
	ch.Dialog.Filename = "Patrol_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.95);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Patrol";
	n = n + 1;

	makeref(ch,Characters[n]);			//Patrol
	ch.name 	= "Soldier";
	ch.lastname 	= " ";
	ch.id		= "Red_patrol_8";
	ch.model	= "soldier_eng";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Redmond_town_03";
	ch.location.group = "goto";
	ch.location.locator = "goto46";
	ch.Dialog.Filename = "Patrol_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Patrol";
	n = n + 1;

	makeref(ch,Characters[n]);			//Magdalen Ayler
	ch.name 	= "Magdalen";
	ch.lastname 	= "Ayler";
	ch.id		= "Magdalen Ayler";
	ch.model	= "towngirl2";
	ch.sound_type = "female_citizen";
	ch.sex = "woman";
	ch.location	= "Redmond_town_03";
	ch.location.group = "goto";
	ch.location.locator = "cityzen02";
	ch.Dialog.Filename = "Redmond Citizen_dialog.c";
	ch.greeting = "Gr_Woman_English Citizen";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			//Jacob Bewighte
	ch.name 	= "Jacob";
	ch.lastname 	= "Bewighte";
	ch.id		= "Jacob Bewighte";
	ch.model	= "man3";
	ch.sound_type = "male_citizen";
	ch.sex = "man";
	ch.location	= "Redmond_town_03";
	ch.location.group = "goto";
	ch.location.locator = "cityzen08";
	ch.Dialog.Filename = "Redmond Citizen_dialog.c";
	ch.greeting = "Gr_Redmond Citizen";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

//Location: Redmond Residence Square (A square with a fountain)

	makeref(ch,Characters[n]);			//Soldier near residence entrance
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Eng_Soldier_5";
	ch.model	= "soldier_eng5";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Redmond_town_01";
	ch.location.group = "goto";
	ch.location.locator = "soldier1";
	ch.Dialog.Filename = "Redmond Soldier_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "7";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Redmond Soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			//Soldier near residence entrance
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Eng_Soldier_6";
	ch.model	= "soldier_eng";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Redmond_town_01";
	ch.location.group = "goto";
	ch.location.locator = "soldier2";
	ch.Dialog.Filename = "Redmond Soldier_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "6";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Redmond Soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			//Soldier near residence entrance
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Eng_soldier_31";
	ch.model	= "soldier_eng6";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Redmond_town_01";
	ch.location.group = "goto";
	ch.location.locator = "goto11";
	ch.Dialog.Filename = "Redmond soldier_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "7";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Redmond Soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			//Soldier near residence entrance
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Eng_soldier_32";
	ch.model	= "soldier_eng4";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Redmond_town_01";
	ch.location.group = "goto";
	ch.location.locator = "goto25";
	ch.Dialog.Filename = "Redmond soldier_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "6";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Redmond Soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			//Patrol
	ch.name 	= "Soldier";
	ch.lastname 	= " ";
	ch.id		= "Red_patrol_5";
	ch.model	= "soldier_eng2";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Redmond_town_01";
	ch.location.group = "goto";
	ch.location.locator = "goto15";
	ch.Dialog.Filename = "Patrol_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Patrol";
	n = n + 1;

	makeref(ch,Characters[n]);			//Patrol
	ch.name 	= "Soldier";
	ch.lastname 	= " ";
	ch.id		= "Red_patrol_6";
	ch.model	= "soldier_eng3";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Redmond_town_01";
	ch.location.group = "goto";
	ch.location.locator = "goto20";
	ch.Dialog.Filename = "Patrol_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Patrol";
	n = n + 1;

	makeref(ch,Characters[n]);			//Marvin Peutherer
	ch.name 	= "Marvin";
	ch.lastname 	= "Peutherer";
	ch.id		= "Marvin Peutherer";
	ch.model	= "old_man1";
	ch.sound_type = "male_citizen";
	ch.sex = "man";
	ch.location	= "Redmond_town_01";
	ch.location.group = "goto";
	ch.location.locator = "cityzen10";
	ch.Dialog.Filename = "Redmond Citizen_dialog.c";
	ch.greeting = "Gr_Redmond Citizen";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;


	makeref(ch,Characters[n]);			//Yvonne Dale
	ch.name 	= "Yvonne";
	ch.lastname 	= "Dale";
	ch.id		= "Yvonne Dale";
	ch.model	= "towngirl2";
	ch.sound_type = "female_citizen";
	ch.sex = "woman";
	ch.location	= "Redmond_town_01";
	ch.location.group = "goto";
	ch.location.locator = "cityzen5";
	ch.Dialog.Filename = "Redmond Citizen_dialog.c";
	ch.greeting = "Gr_Woman_English Citizen";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

//Location:Town exit near the river (where the small market is situtated)

	makeref(ch,Characters[n]);			//Soldier near town gates
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Eng_Soldier_7";
	ch.model	= "soldier_eng2";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Redmond_town_04";
	ch.location.group = "goto";
	ch.location.locator = "soldier01";
	ch.Dialog.Filename = "Redmond Soldier_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "5";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Redmond Soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			//Soldier near town gates
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Eng_soldier_8";
	ch.model	= "soldier_eng";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Redmond_town_04";
	ch.location.group = "goto";
	ch.location.locator = "soldier02";
	ch.Dialog.Filename = "Redmond soldier_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "6";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Redmond Soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			//Soldier near prison
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Eng_soldier_33";
	ch.model	= "soldier_eng4";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Redmond_town_04";
	ch.location.group = "goto";
	ch.location.locator = "soldier03";
	ch.Dialog.Filename = "Redmond soldier_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "6";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Redmond Soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			//Soldier near prison
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Eng_soldier_34";
	ch.model	= "soldier_eng3";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Redmond_town_04";
	ch.location.group = "goto";
	ch.location.locator = "soldier04";
	ch.Dialog.Filename = "Redmond soldier_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "6";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Redmond Soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			//Patrol
	ch.name 	= "Soldier";
	ch.lastname 	= " ";
	ch.id		= "Red_patrol_9";
	ch.model	= "soldier_eng5";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Redmond_town_04";
	ch.location.group = "goto";
	ch.location.locator = "goto_7";
	ch.Dialog.Filename = "Patrol_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Patrol";
	n = n + 1;

	makeref(ch,Characters[n]);			//Patrol
	ch.name 	= "Soldier";
	ch.lastname 	= " ";
	ch.id		= "Red_patrol_10";
	ch.model	= "soldier_eng3";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Redmond_town_04";
	ch.location.group = "goto";
	ch.location.locator = "goto_27";
	ch.Dialog.Filename = "Patrol_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetPatrolType(ch);
	LAi_SetLoginTime(ch, 22.0, 5.98333);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Patrol";
	n = n + 1;

	makeref(ch,Characters[n]);			//Matthew Hoskins
	ch.name 	= "Matthew";
	ch.lastname 	= "Hoskins";
	ch.id		= "Matthew Hoskins";
	ch.model	= "man5";
	ch.sound_type = "male_citizen";
	ch.sex = "man";
	ch.location	= "Redmond_town_04";
	ch.location.group = "goto";
	ch.location.locator = "cityzen04";
	ch.Dialog.Filename = "Redmond Citizen_dialog.c";
	ch.greeting = "Gr_Redmond Citizen";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			//Samuel Vallentain
	ch.name 	= "Samuel";
	ch.lastname 	= "Vallentain";
	ch.id		= "Samuel Vallentain";
	ch.model	= "bocman4";
	ch.sound_type = "male_citizen";
	ch.fanatic = "1";
	ch.church = "Redmond_church";
	ch.church.loc = "goto10";
	ch.back.location = "Redmond_town_04";
	ch.back.locator = "cityzen03";
	ch.sex = "man";
	ch.location	= "Redmond_town_04";
	ch.location.group = "goto";
	ch.location.locator = "cityzen03";
	ch.Dialog.Filename = "Redmond Citizen_dialog.c";
	ch.greeting = "Gr_Redmond Citizen";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			//Sarah Fitter
	ch.name 	= "Sarah";
	ch.lastname 	= "Fitter";
	ch.id		= "Sarah Fitter";
	ch.model	= "towngirl3_1";
	ch.sound_type = "female_citizen";
	ch.sex = "woman";
	ch.location	= "Redmond_town_04";
	ch.location.group = "merchant";
	ch.location.locator = "merchant1";
	ch.Dialog.Filename = "Item Trader_dialog.c";
	ch.greeting = "Gr_Woman_English Citizen";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetMerchantType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			//Elias Belt
	ch.name 	= "Elias";
	ch.lastname 	= "Belt";
	ch.id		= "Elias Belt";
	ch.model	= "Chameleon";
	ch.sound_type = "male_citizen";
	ch.sex = "man";
	ch.location	= "Redmond_town_04";
	ch.location.group = "goto";
	ch.location.locator = "cityzen02";
	ch.Dialog.Filename = "Redmond Citizen_dialog.c";
	ch.greeting = "Gr_Redmond Citizen";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			//Patrick Bisset
	ch.name 	= "Patrick";
	ch.lastname 	= "Bisset";
	ch.id		= "Patrick Bisset";
	ch.model	= "corsair3";
	ch.sound_type = "pirate";
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Redmond_town_04";
	ch.location.group = "goto";
	ch.location.locator = "cityzen07";
	ch.Dialog.Filename = "Redmond Citizen_dialog.c";
	ch.greeting = "Gr_Redmond Citizen";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			//William Hammond
	ch.name 	= "William";
	ch.lastname 	= "Hammond";
	ch.id		= "William Hammond";
	ch.model	= "old_man1";
	ch.sound_type = "male_citizen";
	ch.sex = "man";
	ch.location	= "Redmond_town_04";
	ch.location.group = "goto";
	ch.location.locator = "cityzen06";
	ch.Dialog.Filename = "Redmond Citizen_dialog.c";
	ch.greeting = "Gr_Redmond Citizen";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			//Flora Kempster
	ch.name 	= "Flora";
	ch.lastname 	= "Kempster";
	ch.id		= "Flora Kempster";
	ch.model	= "towngirl1_1";
	ch.sound_type = "female_citizen";
	ch.sex = "woman";
	ch.location	= "Redmond_town_04";
	ch.location.group = "goto";
	ch.location.locator = "cityzen08";
	ch.Dialog.Filename = "Redmond Citizen_dialog.c";
	ch.greeting = "Gr_Woman_English Citizen";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetCitizenType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	//Location: Redmond Tavern

	makeref(ch,Characters[n]);			//Morys Biddulph
	ch.name 	= "Morys";
	ch.lastname 	= "Biddulph";
	ch.id		= "Morys Biddulph";
	ch.model	= "capitan1";
	ch.sound_type = "seaman";
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Redmond_Tavern";
	ch.location.group = "sit";
	ch.location.locator = "sit1";
	ch.Dialog.Filename = "Habitue_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.last_theme = "";
	LAi_SetSitType(ch);
	LAi_SetLoginTime(ch, 5.0, 21.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			//Roger Hayes
	ch.name 	= "Roger";
	ch.lastname 	= "Hayes";
	ch.id		= "Roger Hayes";
	ch.model	= "bocman3";
	ch.sound_type = "seaman";
	ch.sex = "man";
	ch.location	= "Redmond_Tavern";
	ch.location.group = "Sit";
	ch.location.locator = "Sit3";
	ch.Dialog.Filename = "Habitue_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.quest.last_theme = "";
	LAi_SetSitType(ch);
	LAi_SetLoginTime(ch, 5.0, 21.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			//Flann Marrow
	ch.name 	= "Flann";
	ch.lastname 	= "Marrow";
	ch.id		= "Flann Marrow";
	ch.model	= "man1_1";
	ch.sound_type = "male_citizen";
	ch.sex = "man";
	ch.location	= "Redmond_Tavern";
	ch.location.group = "Sit";
	ch.location.locator = "Sit3";
	ch.Dialog.Filename = "Habitue_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetSitType(ch);
	LAi_SetLoginTime(ch, 21.1, 4.9);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			//Evan Newson
	ch.name 	= "Evan";
	ch.lastname 	= "Newson";
	ch.id		= "Evan Newson";
	ch.model	= "man2";
	ch.sound_type = "male_citizen";
	ch.sex = "man";
	ch.location	= "Redmond_Tavern";
	ch.location.group = "Sit";
	ch.location.locator = "Sit1";
	ch.Dialog.Filename = "Habitue_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetSitType(ch);
	LAi_SetLoginTime(ch, 21.1, 4.8);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);		// English оффициантка
	ch.name 	= "Simona";
	ch.lastname = "Tolman";
	ch.id		= "Redmond_officiant";
	ch.model	= "towngirl2";
	ch.sound_type = "female_citizen";
	ch.sex = "woman";
	ch.location	= "Redmond_tavern";
	ch.location.group = "goto";
	ch.location.locator = "goto3";
	ch.Dialog.Filename = "Eng_Officiant_dialog.c";
	ch.nation = ENGLAND;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "1";
	ch.quest.sex = 0;
	ch.sex.time = 0;
	LAi_SetWaitressType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	makeref(ch,Characters[n]);			//Charles Windem - трактирщик
	ch.name 	= "Charles";
	ch.lastname 	= "Windem";
	ch.id		= "Charles Windem";
	ch.model	= "old_man1";
	ch.sex = "man";
	ch.location	= "Redmond_Tavern";
	ch.location.group = "merchant";
	ch.location.locator = "goto1";
	ch.Dialog.Filename = "Charles Windem_dialog.c";
	ch.greeting = "Gr_Charles Windem";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.work = "";
	LAi_SetBarmanType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	n = n + 1;

	//Основные персонажи Редмонда:

	makeref(ch,Characters[n]);			//Thomas O'Reily - торговец
	ch.name 	= "Thomas";
	ch.lastname 	= "O'Reily";
	ch.id		= "Thomas O'Reily";
	ch.model	= "man2";
	ch.sex = "man";
	ch.location	= "Redmond_Store";
	ch.location.group = "sit";
	ch.location.locator = "sit1";
	ch.Dialog.Filename = "Thomas O'Reily_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "4";
	ch.skill.Sneak = "1";
	ch.money = "10";
	ch.money.quest = "0";
	ch.quest.first_job = "0";
	ch.quest.contraband = "0";
	ch.quest_begin = "0";
	ch.quest.trade_date = "";
	ch.quest.item_date = "";
	LAi_SetMerchantType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	ch.greeting = "Gr_Thomas O'Reily";
	n = n + 1;

	makeref(ch,Characters[n]);			//Roger Murray - корабел
	ch.name 	= "Roger";
	ch.lastname 	= "Murray";
	ch.id		= "Roger Murray";
	ch.model	= "man1";
	ch.sex = "man";
	ch.location	= "Redmond_Shipyard";
	ch.location.group = "sit";
	ch.location.locator = "sit_1";
	ch.Dialog.Filename = "Roger Murray_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "1";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetHuberType(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	ch.greeting = "Gr_Roger Murray";
	n = n + 1;

	makeref(ch,Characters[n]);			//Robert Christopher Silehard - губернатор
	ch.name 	= "Robert";
	ch.middlename = "Christopher";
	ch.lastname = "Silehard";
	ch.id		= "Robert Christopher Silehard";
	ch.model	= "huber_eng";
	ch.sex = "man";
	ch.location	= "Redmond_Residence";
	ch.location.group = "goto";
	ch.location.locator = "goto8";
	ch.Dialog.Filename = "Robert Christopher Silehard_dialog.c";
	ch.rank 	= 10;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "10";
	ch.skill.Fencing = "7";
	ch.skill.Sailing = "4";
	ch.skill.Accuracy = "6";
	ch.skill.Cannons = "4";
	ch.skill.Grappling = "2";
	ch.skill.Repair = "0";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "10";
	ch.skill.Sneak = "0";
	ch.Ship.Name = "Belette";
	ch.Ship.Type = SHIP_MANOWAR_ENGLAND;
	ch.Ship.Stopped = true;
	ch.Ship.Cannons.Type = CANNON_TYPE_CULVERINE_LBS24;
	ch.money = "100000";
	LAi_SetHuberStayType(ch);
	LAi_SetStayHuberPointWindow(ch, "goto", "goto10");
	LAi_SetStayHuberPointMap(ch, "goto", "goto9");
	LAi_RemoveLoginTime(ch);
	LAi_group_MoveCharacter(ch, "ENGLAND_CITIZENS");
	ch.greeting = "Gr_Robert Christopher Silehard";
	n = n + 1;

	makeref(ch,Characters[n]);			//Soldier in prison
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Eng_soldier_35";
	ch.model	= "soldier_eng6";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Redmond_prison";
	ch.location.group = "goto";
	ch.location.locator = "goto16";
	ch.Dialog.Filename = "Redmond soldier_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "6";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Redmond Soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			//Soldier in prison
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Eng_soldier_36";
	ch.model	= "soldier_eng4";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Redmond_prison";
	ch.location.group = "goto";
	ch.location.locator = "goto14";
	ch.Dialog.Filename = "Redmond soldier_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "6";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetGuardianType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Redmond Soldier";
	n = n + 1;

	makeref(ch,Characters[n]);			//Prison Commendant
	ch.name 	= "Soldier";
	ch.lastname 	= "";
	ch.id		= "Redmond prison commendant";
	ch.model	= "offic_eng";
	ch.sound_type = "soldier";
	LAi_CharacterReincarnation(ch, true, true);
	ch.sex = "man";	
	GiveItem2Character(ch, "Blade1");
	ch.equip.blade = "Blade1";
	GiveItem2Character(ch, "Pistol1");
	ch.equip.gun = "Pistol1";
	ch.location	= "Redmond_prison";
	ch.location.group = "sit";
	ch.location.locator = "sit1";
	ch.Dialog.Filename = "Redmond commendant_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "4";
	ch.skill.Sailing = "1";
	ch.skill.Accuracy = "1";
	ch.skill.Cannons = "1";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "1";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetHuberType(ch);
	LAi_SetLoginTime(ch, 0.0, 24.0);
	LAi_SetHP(ch, 80.0, 80.0);
	LAi_group_MoveCharacter(ch, "ENGLAND_SOLDIERS");
	ch.greeting = "Gr_Redmond Commendant";
	n = n + 1;

	return n;
}