
int CreateTownUsurers(int n)
{
	ref ch;

	makeref(ch,Characters[n]);		//Ростовщик в Редмонде
	ch.name 	= "Robyn";
	ch.lastname 	= "Corrick";
	ch.id		= "Redmond Usurer";
	ch.model	= "Man2";
	ch.sex = "man";
	ch.act.type = "sit";
	ch.location = "Redmond_UsurerHouse";
	ch.location.group = "sit";
	ch.location.locator = "sit1";
	ch.dialog.filename = "Usurer_Dialog.c";
	ch.nation = ENGLAND;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "6";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "4";
	ch.skill.Accuracy = "9";
	ch.skill.Cannons = "5";
	ch.skill.Grappling = "5";
	ch.skill.Repair = "6";
	ch.skill.Defence = "8";
	ch.skill.Commerce = "7";
	ch.skill.Sneak = "8";
	ch.quest.area = "redmond";
	ch.money = "10";
	LAi_SetSitType(ch);
	LAi_SetHP(ch, 80.0, 80.0);
	n = n + 1;

	makeref(ch,Characters[n]);		//Ростовщик в Оксбэе
	ch.name 	= "Diarmuid";
	ch.lastname 	= "Sargent";
	ch.id		= "Oxbay Usurer";
	ch.model	= "Storeman";
	ch.sex = "man";
	ch.act.type = "citizen";
	ch.location = "Oxbay_UsurerHouse";
	ch.location.group = "goto";
	ch.location.locator = "goto1";
	ch.dialog.filename = "Usurer_Dialog.c";
	ch.nation = ENGLAND;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "6";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "4";
	ch.skill.Accuracy = "9";
	ch.skill.Cannons = "5";
	ch.skill.Grappling = "5";
	ch.skill.Repair = "6";
	ch.skill.Defence = "8";
	ch.skill.Commerce = "7";
	ch.skill.Sneak = "8";
	ch.quest.area = "Oxbay";
	ch.money = "10";
	LAi_SetStayType(ch);
	LAi_SetHP(ch, 80.0, 80.0);
	n = n + 1;

	makeref(ch,Characters[n]);		//Ростовщик в Гринфорде
	ch.name 	= "Kermit";
	ch.lastname 	= "Proudfoot";
	ch.id		= "Greenford Usurer";
	ch.model	= "Storeman";
	ch.sex = "man";
	ch.location = "Greenford_UsurerHouse";
	ch.location.group = "sit";
	ch.location.locator = "sit1";
	ch.dialog.filename = "Usurer_Dialog.c";
	ch.nation = ENGLAND;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "6";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "4";
	ch.skill.Accuracy = "9";
	ch.skill.Cannons = "5";
	ch.skill.Grappling = "5";
	ch.skill.Repair = "6";
	ch.skill.Defence = "8";
	ch.skill.Commerce = "7";
	ch.skill.Sneak = "8";
	ch.quest.area = "Greenford";
	ch.money = "10";
	LAi_SetStayType(ch);
	LAi_SetHP(ch, 80.0, 80.0);
	n = n + 1;

	makeref(ch,Characters[n]);			//Ростовщик в Фале де Флер
	ch.name 	= "Mercadier";
	ch.lastname 	= "Nadeau";
	ch.id		= "FF Usurer";
	ch.model	= "Fatman2";
	ch.sex = "man";
	ch.act.type = "merchant";
	ch.location = "FF_UsurerHouse";
	ch.location.group = "goto";
	ch.location.locator = "goto1";
	ch.dialog.filename = "Usurer_Dialog.c";
	ch.nation = FRANCE;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "6";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "4";
	ch.skill.Accuracy = "9";
	ch.skill.Cannons = "5";
	ch.skill.Grappling = "5";
	ch.skill.Repair = "6";
	ch.skill.Defence = "8";
	ch.skill.Commerce = "7";
	ch.skill.Sneak = "8";
	ch.quest.area = "FalaiseDeFleur";
	ch.money = "10";
	LAi_SetStayType(ch);
	LAi_SetHP(ch, 80.0, 80.0);
	n = n + 1;

	makeref(ch,Characters[n]);			// Ростовщик в Консейсао
	ch.name 	= "Feliciano";
	ch.lastname 	= "Pombal";
	ch.id		= "Conceicao Usurer";
	ch.model	= "Chameleon";
	ch.sex = "man";
	ch.act.type = "merchant";
	ch.location = "Conceicao_UsurerHouse";
	ch.location.group = "goto";
	ch.location.locator = "goto1";
	ch.dialog.filename = "Usurer_Dialog.c";
	ch.nation = PORTUGAL;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "6";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "4";
	ch.skill.Accuracy = "9";
	ch.skill.Cannons = "5";
	ch.skill.Grappling = "5";
	ch.skill.Repair = "6";
	ch.skill.Defence = "8";
	ch.skill.Commerce = "7";
	ch.skill.Sneak = "8";
	ch.quest.area = "Conceicao";
	ch.money = "10";
	LAi_SetStayType(ch);
	LAi_SetHP(ch, 80.0, 80.0);
	n = n + 1;

	makeref(ch,Characters[n]);			//Ростовщик в Дувезене
	ch.name 	= "Klaas";
	ch.lastname 	= "Ramaalas";
	ch.id		= "Douwesen Usurer";
	ch.model	= "Searcher";
	ch.sex = "man";
	ch.act.type = "merchant";
	ch.location = "Douwesen_UsurerHouse";
	ch.location.group = "goto";
	ch.location.locator = "goto1";
	ch.dialog.filename = "Usurer_Dialog.c";
	ch.nation = HOLLAND;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "6";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "4";
	ch.skill.Accuracy = "9";
	ch.skill.Cannons = "5";
	ch.skill.Grappling = "5";
	ch.skill.Repair = "6";
	ch.skill.Defence = "8";
	ch.skill.Commerce = "7";
	ch.skill.Sneak = "8";
	ch.quest.area = "Douwesen";
	ch.money = "10";
	LAi_SetStayType(ch);
	LAi_SetHP(ch, 80.0, 80.0);
	n = n + 1;

	makeref(ch,Characters[n]);			// Ростовщик в Исла Муэлье
	ch.name 	= "Silvestre";
	ch.lastname 	= "Nabarro";
	ch.id		= "Muelle Usurer";
	ch.model	= "Old_man1";
	ch.sex = "man";
	ch.act.type = "merchant";
	ch.location = "Muelle_UsurerHouse";
	ch.location.group = "goto";
	ch.location.locator = "goto1";
	ch.dialog.filename = "Usurer_Dialog.c";
	ch.nation = SPAIN;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "6";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "4";
	ch.skill.Accuracy = "9";
	ch.skill.Cannons = "5";
	ch.skill.Grappling = "5";
	ch.skill.Repair = "6";
	ch.skill.Defence = "8";
	ch.skill.Commerce = "7";
	ch.skill.Sneak = "8";
	ch.quest.area = "Muelle";
	ch.money = "10";
	LAi_SetStayType(ch);
	LAi_SetHP(ch, 80.0, 80.0);
	n = n + 1;

	makeref(ch,Characters[n]);			// Ростовщик в Кебрадас Костиллас
	ch.name 	= "Vistremiro";
	ch.lastname 	= "Monteiro";
	ch.id		= "QC Usurer";
	ch.model	= "Black_Corsair";
	ch.sex = "man";
	ch.act.type = "merchant";
	ch.location = "QC_UsurerHouse";
	ch.location.group = "goto";
	ch.location.locator = "goto1";
	ch.dialog.filename = "Usurer_Dialog.c";
	ch.nation = SPAIN;
	ch.rank 	= 1;
	ch.reputation = "None";
	ch.experience = "0";
	ch.skill.Leadership = "6";
	ch.skill.Fencing = "3";
	ch.skill.Sailing = "4";
	ch.skill.Accuracy = "9";
	ch.skill.Cannons = "5";
	ch.skill.Grappling = "5";
	ch.skill.Repair = "6";
	ch.skill.Defence = "8";
	ch.skill.Commerce = "7";
	ch.skill.Sneak = "8";
	ch.quest.area = "QC";
	ch.money = "10";
	LAi_SetStayType(ch);
	LAi_SetHP(ch, 80.0, 80.0);
	n = n + 1;

//-----------------------------------представители контрабандистов в тавернах-------------
//-----------------------------------представители контрабандистов в тавернах-------------
//-----------------------------------представители контрабандистов в тавернах-------------

	makeref(ch,Characters[n]);			// На Редмонде
	ch.name 	= "Smuggler";
	ch.lastname 	= "";
	ch.id		= "Redmond_Smuggler";
	ch.model = "Sailor3";
	ch.sex = "man";
	ch.act.type = "sit";
	ch.sound_type = "pirate";
	ch.act.escape = 0;
	LAi_SetLoginTime(ch, 0.0, 24.0);
	//ch.act.rebirth = 1;
	ch.nation = PIRATE;
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Redmond_tavern";
	ch.location.group = "Sit";
	ch.location.locator = "Sit7";
	ch.Dialog.Filename = "Smuggler Agent_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "22";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "4";
	ch.skill.Sailing = "5";
	ch.skill.Accuracy = "4";
	ch.skill.Cannons = "6";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "2";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetSitType(ch);
	LAi_SetHP(ch, 80.0, 80.0);
	ch.greeting = "Gr_Smuggler Agent";
	n = n + 1;

	makeref(ch,Characters[n]);			// На Оксбэе
	ch.name 	= "Smuggler";
	ch.lastname 	= "";
	ch.id		= "Oxbay_Smuggler";
	ch.model = "Man1_2";
	ch.sex = "man";
	ch.act.type = "sit";
	ch.sound_type = "pirate";
	ch.act.escape = 0;
	LAi_SetLoginTime(ch, 0.0, 24.0);
	//ch.act.rebirth = 1;
	ch.nation = PIRATE;
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Oxbay_tavern";
	ch.location.group = "Sit";
	ch.location.locator = "Sit7";
	ch.Dialog.Filename = "Smuggler Agent_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "22";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "4";
	ch.skill.Sailing = "5";
	ch.skill.Accuracy = "4";
	ch.skill.Cannons = "6";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "2";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetSitType(ch);
	LAi_SetHP(ch, 80.0, 80.0);
	ch.greeting = "Gr_Smuggler Agent";
	n = n + 1;

	makeref(ch,Characters[n]);			// В Гринфорде
	ch.name 	= "Smuggler";
	ch.lastname 	= "";
	ch.id		= "Greenford_Smuggler";
	ch.model = "sailor6";
	ch.sex = "man";
	ch.act.type = "sit";
	ch.sound_type = "pirate";
	ch.act.escape = 0;
	LAi_SetLoginTime(ch, 0.0, 24.0);
	//ch.act.rebirth = 1;
	ch.nation = PIRATE;
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "greenford_tavern";
	ch.location.group = "Sit";
	ch.location.locator = "Sit8";
	ch.Dialog.Filename = "Smuggler Agent_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "22";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "4";
	ch.skill.Sailing = "5";
	ch.skill.Accuracy = "4";
	ch.skill.Cannons = "6";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "2";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetSitType(ch);
	LAi_SetHP(ch, 80.0, 80.0);
	ch.greeting = "Gr_Smuggler Agent";
	n = n + 1;

	makeref(ch,Characters[n]);			// На Фале Де Флер
	ch.name 	= "Smuggler";
	ch.lastname 	= "";
	ch.id		= "FF_Smuggler";
	ch.model = "sailor5";
	ch.sex = "man";
	ch.act.type = "sit";
	ch.sound_type = "pirate";
	ch.act.escape = 0;
	LAi_SetLoginTime(ch, 0.0, 24.0);
	//ch.act.rebirth = 1;
	ch.nation = PIRATE;
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Falaise_de_Fleur_tavern";
	ch.location.group = "Sit";
	ch.location.locator = "Sit6";
	ch.Dialog.Filename = "Smuggler Agent_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "22";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "4";
	ch.skill.Sailing = "5";
	ch.skill.Accuracy = "4";
	ch.skill.Cannons = "6";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "2";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetSitType(ch);
	LAi_SetHP(ch, 80.0, 80.0);
	ch.greeting = "Gr_Smuggler Agent";
	n = n + 1;

	makeref(ch,Characters[n]);			// На Conceicao
	ch.name 	= "Smuggler";
	ch.lastname 	= "";
	ch.id		= "Conceicao_Smuggler";
	ch.model = "Old_man2";
	ch.sex = "man";
	ch.act.type = "sit";
	ch.sound_type = "pirate";
	ch.act.escape = 0;
	LAi_SetLoginTime(ch, 0.0, 24.0);
	//ch.act.rebirth = 1;
	ch.nation = PIRATE;
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Conceicao_tavern";
	ch.location.group = "Sit";
	ch.location.locator = "Sit6";
	ch.Dialog.Filename = "Smuggler Agent_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "22";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "4";
	ch.skill.Sailing = "5";
	ch.skill.Accuracy = "4";
	ch.skill.Cannons = "6";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "2";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetSitType(ch);
	LAi_SetHP(ch, 80.0, 80.0);
	ch.greeting = "Gr_Smuggler Agent";
	n = n + 1;

	makeref(ch,Characters[n]);			// На Douwesen
	ch.name 	= "Smuggler";
	ch.lastname 	= "";
	ch.id		= "Douwesen_Smuggler";
	ch.model = "Man3_1";
	ch.sex = "man";
	ch.act.type = "sit";
	ch.sound_type = "pirate";
	ch.act.escape = 0;
	LAi_SetLoginTime(ch, 0.0, 24.0);
	//ch.act.rebirth = 1;
	ch.nation = PIRATE;
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Douwesen_tavern";
	ch.location.group = "Sit";
	ch.location.locator = "Sit6";
	ch.Dialog.Filename = "Smuggler Agent_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "22";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "4";
	ch.skill.Sailing = "5";
	ch.skill.Accuracy = "4";
	ch.skill.Cannons = "6";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "2";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetSitType(ch);
	LAi_SetHP(ch, 80.0, 80.0);
	ch.greeting = "Gr_Smuggler Agent";
	n = n + 1;

	makeref(ch,Characters[n]);			// На Isla Muelle
	ch.name 	= "Smuggler";
	ch.lastname 	= "";
	ch.id		= "Muelle_Smuggler";
	ch.model = "Korsar1";
	ch.sex = "man";
	ch.act.type = "sit";
	ch.sound_type = "pirate";
	ch.act.escape = 0;
	LAi_SetLoginTime(ch, 0.0, 24.0);
	//ch.act.rebirth = 1;
	ch.nation = PIRATE;
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Muelle_tavern";
	ch.location.group = "Sit";
	ch.location.locator = "Sit1";
	ch.Dialog.Filename = "Smuggler Agent_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "22";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "4";
	ch.skill.Sailing = "5";
	ch.skill.Accuracy = "4";
	ch.skill.Cannons = "6";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "2";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetSitType(ch);
	LAi_SetHP(ch, 80.0, 80.0);
	ch.greeting = "Gr_Smuggler Agent";
	n = n + 1;

//---------------------------дипломаты, примиряющие игрока с разными странами-------------
//---------------------------дипломаты, примиряющие игрока с разными странами-------------
//---------------------------дипломаты, примиряющие игрока с разными странами-------------

	makeref(ch,Characters[n]);			// На Quebradas Costillas
	ch.name 	= "Diplomat";
	ch.lastname 	= "";
	ch.id		= "QC_Diplomat";
	ch.model = "sailor4";
	ch.sex = "man";
	ch.act.type = "sit";
	ch.sound_type = "pirate";
	ch.act.escape = 0;
	LAi_SetLoginTime(ch, 0.0, 24.0);
	//ch.act.rebirth = 1;
	ch.nation = PIRATE;
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "QC_tavern";
	ch.location.group = "Sit";
	ch.location.locator = "Sit6";
	ch.Dialog.Filename = "RelationAgent_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "22";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "4";
	ch.skill.Sailing = "5";
	ch.skill.Accuracy = "4";
	ch.skill.Cannons = "6";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "2";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetSitType(ch);
	LAi_SetHP(ch, 80.0, 80.0);
	n = n + 1;


	makeref(ch,Characters[n]);			// На Conceicao
	ch.name 	= "Diplomat";
	ch.lastname 	= "";
	ch.id		= "Conceicao_Diplomat";
	ch.model = "old_man2";
	ch.sex = "man";
	ch.act.type = "sit";
	ch.sound_type = "pirate";
	ch.act.escape = 0;
	LAi_SetLoginTime(ch, 0.0, 24.0);
	//ch.act.rebirth = 1;
	ch.nation = PIRATE;
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "Smugglers_tavern";
	ch.location.group = "Sit";
	ch.location.locator = "Sit8";
	ch.Dialog.Filename = "RelationAgent_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "22";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "4";
	ch.skill.Sailing = "5";
	ch.skill.Accuracy = "4";
	ch.skill.Cannons = "6";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "2";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetSitType(ch);
	LAi_SetHP(ch, 80.0, 80.0);
	n = n + 1;


	makeref(ch,Characters[n]);			// На Douwesen
	ch.name 	= "Diplomat";
	ch.lastname 	= "";
	ch.id		= "Douwesen_Diplomat";
	ch.model = "Man6_1";
	ch.sex = "man";
	ch.act.type = "sit";
	ch.sound_type = "pirate";
	ch.act.escape = 0;
	LAi_SetLoginTime(ch, 0.0, 24.0);
	//ch.act.rebirth = 1;
	ch.nation = PIRATE;
	GiveItem2Character(ch, BLADE_SABER);
	ch.equip.blade = BLADE_SABER;
	ch.location	= "pirate_tavern";
	ch.location.group = "Sit";
	ch.location.locator = "Sit6";
	ch.Dialog.Filename = "RelationAgent_dialog.c";
	ch.rank 	= 1;
	ch.reputation = "22";
	ch.experience = "0";
	ch.skill.Leadership = "1";
	ch.skill.Fencing = "4";
	ch.skill.Sailing = "5";
	ch.skill.Accuracy = "4";
	ch.skill.Cannons = "6";
	ch.skill.Grappling = "1";
	ch.skill.Repair = "1";
	ch.skill.Defence = "2";
	ch.skill.Commerce = "1";
	ch.skill.Sneak = "1";
	ch.money = "10";
	LAi_SetSitType(ch);
	LAi_SetHP(ch, 80.0, 80.0);
	n = n + 1;

	return n;
}