string DLG_TEXT[50] = {
"Do you have merchandise to sell, or do you just need some personal items, captain?",
"I'd like to sell the cargo I've brought.",
"I'd like to buy a few things for myself.",
"We won't trade at all. Have a nice day.",
"Hello, ",
". My humble shop is at your service.",
"Thank you, my name is ",
".",
"Why, hello, my dear sir! Pleased to see you. Shall we trade?",
"What goods have you brought us this time, captain?",
"Ah, captain! What can I do for you?",
"Let's see what you've got.",
"Right now, I'd like to talk.",
"Farewell.",
"Very pleased to meet you, sir. I am ",
". I hope this will be the beginning of a strong business relationship.",
"Well, ",
", let's see what you have for sale.",
"I'd like to talk to you, ",
".",
"Goodbye.",
"Always a pleasure to chat with you, captain.",
"I'm listening.",
"I was asked to deliver some cargo to you.",
"Would you, perchance, be in need of a captain, sir? I have an excellent ship, and I can deliver any cargo, anywhere you like.",
"I've got no time for talk right now.",
"No, I don't need your services. At least as long as you're sinking French ships.",
"In that case, goodbye.",
"I'm sorry, but I don't have anything for you at the moment.",
"I'll come back later, then.",
"I'm sorry, but your ship doesn't have the capacity for the assignment I have in mind.",
"I'll come back later, then.",
"Oh! I was just going to ask you to do me a favor. Thing is, I need some cargo delivered to ",
", and as soon as possible. If you manage to do it in a month's time, you'll receive ",
" gold when you arrive. How do you like this offer?",
"I definitely like it.",
"I can't accept it.",
"I already told you today that I don't have anything for you.",
"Oh, sorry.",
"You've remembered about your assignment a bit too late, don't you think? I've already received everything I needed. Goodbye.",
"Farewell.",
"Oh! I've been waiting for it for a long time. Here is your reward, young man.",
"Always welcome.",
"As you wish, ",
".",
"Let's see what you have on hand.",
"Thanks for your help. I'll see you soon.",
"Alas, ",
", the French have confiscated the better part of my goods and ammunition, and forbade me to sell the rest until the war ends.",
"Damn my luck!",

};