string DLG_TEXT[46] = {
"What do you want?",
"Nothing. Sorry to bother you.",
"Captain. You're here before me, and ",
"Mateus Santos",
" is still alive and well. You disappoint me.",
"Not for long. Believe me, I'll take care of him.",
"Captain, what are you doing here? As far as I know, ",
"Mateus Santos",
" is still alive.",
"Yes, well, the wind has changed, my friend. ",
"Mateus Santos",
" has made me a...better offer. You may pray before you die, but make it quick. I'm a busy man.",
"Yes, and you misled me. The job turned out to be anything but simple. This ",
"Mateus Santos",
" is no easy mark. In fact, he offered me good money in exchange for your lying hide.",
"Captain, could you spare me a moment? I've got a job that calls for a man of your unique abilities and...reputation.",
"I'm listening.",
"Forget it. I'm not interested in your job.",
"As you wish. But I never thought I'd see the day when a man would refuse good money for such an easy task.",
"Easy money? You have my attention.",
"Are you still talking? Enough, already!",
"Oh, it's easy enough, if you've got the stomach for it. And I suspect you do.",
"Don't speak in code, man! Tell me whose head you want and how much you'll pay.",
"Oh, I get it now. An easy job, if you don't mind blood money. Sorry, but that's not my line of work. So long.",
"This particular head is worth 1500 gold to me. It rests on the shoulders of  ",
"Mateus Santos",
"Mateus Santos",
" of Isla Muelle. His house is next to the shipyard, just to the right.",
"Consider it done. Where do I bring the trophy?",
"You must be joking. I don't take a breath for that kind of money. Make a better offer or forget it.",
"I'll wait for you on the shore, near the smugglers' camp.",
"Fine. You won't wait for long.",
"Captain, I'm begging you - spare my life! The 1500 gold I promised you is all I have. Take it, but please don't kill me!",
"Sorry, friend. Business is business, and ",
"Mateus Santos",
" pays more.",
"Well...I always have been a sucker for coin. Give me the money and go.",
"I don't want your gold, you fool. Just stop your blubbering and run before I change my mind!",
"It's nothing compared to my life. Take it, and I'll go.",
"Just do it, and make it fast!",
"You pathetic fool. I can't believe you fell for that! You're too stupid to live!",
"You'd let me go, just like that? I...I can't believe it!",
"Learn to believe it. And do it somewhere else, before I change my mind.",
"Yes, it is too good to be true, isn't it? Perhaps that's because I lied. Say your prayers, and make them quick!",
"So that's the kind of man you are? Well, I may not be the finest swordsman, but you'll find a man fighting for his life is no small challenge. En garde!",
"...",

};