string DLG_TEXT[25] = {
"Shall we cut someone into pieces, captain?",
"Certainly. Into tiny pieces...",
"Let's see. You've a sharp sword and a hard look in your eye. I'm guessing ",
"Mateus Santos",
" has sent you.",
"That's right. I suppose you also know why.",
"I do, indeed. But you don't seem to know so much. You see, I worked for ",
"Mateus Santos",
", too, and not so long ago. I was very good at my job. Perhaps too good. ",
"Mateus Santos",
" came to fear me. And a man like him knows only one way to deal with fear: to destroy its source.",
"That's a fascinating story. What does it have to do with me?",
"Oh, it has everything to do with you, my friend. He sent you for my head, because he fears me. If you succeed in your task, he will fear you as well. And your days will be numbered. The life of an assassin is a short one, especially with an employer like him.",
"I see. And what advice would you offer a fellow assassin?",
"Only this: Leave while you still can, or this mission could very well be your last.",
"You may be right. But the price on your head is very large. Someone is going to claim it, and it might as well be me!",
"Perhaps you're right. I've no stomach for killing, and there's little point in killing you.",
"I'm glad you see reason. Of course, if you don't claim the price on my head, someone else will. No matter how I move from place to place, ",
"Mateus Santos",
"' men always find me. One of these days, my luck will run out.",
"I'm sure you're right, but I can't help you. I can only wish you luck.",
"You know, you're right. Someone's bound to catch up with you sooner or later, and I can't pass up the chance to cross swords with the best fencer in the archipelago! En garde!",
"I might be able to help you on that score, if you don't mind a little honest work. There's always a place on my ship for the best swordsman in the archipelago.",
"I like the way you think, captain. My sword is yours.",
"I'm pleased to hear it. Welcome to my crew.",

};