string DLG_TEXT[27] = {
", friend. I'm",
", I run the local shipyard.",
"Pleased to meet you. I'm ",
", the captain of the '",
"'.",
", ",
". So, what can I do for you, ",
"?",
"I'm just looking to plug up a couple of holes and patch my sails. No questions asked.",
"At the moment, I'm more interested in information.",
"No, I'm just killing time. I thought I might kill some of yours while I'm at it.",
"Well, if you're a captain, my shipyard is at your service.",
"Excellent, ",
". Let's have a look at my ship and see what needs fixing.",
"I appreciate it. At the moment, though, I'd just like to ask you some questions.",
"Maybe next time. I don't need your services right now.",
"What exactly are you interested in, ",
"?",
"Nothting at the moment...",
"Is there anything else I can do for you, ",
"?",
"If you can slap a couple of patches on my tub, I'll be on my way!",
"Thanks, that's it. Farewell!",
"What exactly do you need?",
"My ship is in need of repair. Or maybe I'll just buy a new one if the price is right.",
"I'm feeling the need for a little more firepower. Maybe you can help.",
"I'm fine, thanks.",

};