string DLG_TEXT[232] = {      
"Greetings, stranger, take my humble advice.",
"Yes, with pleasure.",
"I don't need your advice.",
"Greetings, wayfarer. Where are you going?",
"Oh, just off on my own affairs.",
"It's none of your business.",
"Good day, stranger. How are you doing?",
"Fine, thank you.",
"I've got no time to talk to you.",
"Hello. I haven't seen you here before. Are you from the city?",
"Yes, I've just come from there.",
"I've got no time to talk to you.",
"Greetings, foreigner. It's good to see you here.",
"Hello.",
"Excuse me, but I can't talk to you right now.",
"Greetings, sailor. Do you want to hear good advice?",
"Good day. Speak out.",
"I've got no time to waste.",
"Good day, stranger. I've got some goods you may be interested in.",
"So let's bargain.",
"I've got no time to talk to you.",
"Good day, stranger. You look tired. I can offer you a single magical remedy from all diseases... and for a limited time only, at the bargain price of 200 gold!",
"Give me your swill.",
"I never believed in magical potions.",
"Good day, sailor. I'm in reduced circumstances, won't you help me?",
"Hmm, why should I...",
"That's your problem.",
"Sir, won't you help a poor sufferer with a couple coins?",
"Of course, the Church teaches us to help our neighbor.",
"Walk away, poor man, and don't bother me any more.",
"My sir, don't leave me in such poverty! Spare me a coin, please, so I can buy food.",
"Don't worry, my poor fellow. Here are 10 coins for you.",
"Walk away, poor man, and don't try to ask any more.",
"Good day. As I see you're a bold fellow, obviously you are fighting a lot?",
"Yes, of course.",
"That's my business. Goodbye.",
"Greetings. Not often do I encounter such respectable persons here. You must be a captain?",
"Yes, what can I do for you?",
"You know I'm in hurry. Goodbye.",
"Good day. You are walking here without any pressing business?",
"Generally, yes. I'll be glad to talk to you.",
"No, I'm busy.",
"Listen, stranger - don't travel here at night. They say that some dead men walk here at these hours.",
"Thank you for your advice.",
"I advise you not to walk here if you've got any problems with the law. There are a lot of soldiers here. Perhaps you'd better sail away from this island.",
"That's interesting.",
"I'm not interested in this kind of advice. Goodbye.",
"But be warned, when you sail here next time, they may not be very glad to see you again.",
"All right, I'll remember.",
"I know a good way to get cured if you've got some disease. You can buy a bottle from the trader in the city.",
"Yes, and besides that?",
"I've got no time to talk to you.",
"And if you rest for some time in a tavern bed, it will cure you, too.",
"Thank you.",
"You know, when I need the most recent information, I go and talk to a tavern owner. He can answer nearly all your questions.",
"Great advice. I'll definitely follow it.",
"As I can see, you are a fighting sea captain. Remember - take more officers. Sometimes without their help, you can't survive.",
"Yes, of course.",
"I can see by your bearing that you are a sea captain. If you need a ship - buy it in our shipyard. If they don't have the exact ship you're looking for, wait a couple of days, and perhaps one will appear.",
"God advice, thank you.",
"Sometimes you may meet people that have traveled much around the world. You may ask for their help, and they may increase your skill in some area. I speak from experience - their knowledge may be invaluable.",
"Not bad advice, thank you.",
"If you will give me twenty coins, I will tell everyone how kind you are. Don't be concerned that I'm poor. I've many friends, and they will always be glad to see you here.",
"Waste money just for some beggar to talk around about me? Well, no thanks.",
"Yes? All right, twenty gold is not so much to give to a man in such need.",
"I'm grateful for what you have done. I offer you such thanks as I have. Drink that remedy - it will cure you.",
"Thank you, too.",
"Thank you. I've little to show my gratitude, but at least take this item. Maybe you will find a good use for it.",
"I will take it with pleasure.",
"Thank you, good man.",
"Don't mention it.",
"Captain, will you take me aboard your ship? I've long dreamed of exciting naval battles and long ocean voyages.",
"Of course. You will be my officer.",
"No, I don't need fresh sailors.",
"Pay me, and I will show you a couple of tricks to beat anyone in a hand-to-hand fight. Or would you like to learn some defensive moves?",
"I don't need your advice. I know this all very well, and can even teach you.",
"Show me your defensive moves.",
"I don't need your advice. I know this all very well, and can even teach you.",
"Show me your offensive moves.",
"Thank you, but I don't need any help just now.",
"Some time ago I was a sailor, too...a famous adventurer. I can tell you a lot about managing the crew on your ship.",
"I don't need your advice. I know this all very well, and can even teach you.",
"Yes, I'd like to know more about it.",
"Thank you, but I don't need any help just now.",
"I'm a sailor, too...a navigator. For a few coins, I will share my secrets that will help you better guide your ship.",
"I don't need your advice. I know this all very well, and can even teach you.",
"Yes, I'd like to know more about maneuvering.",
"Thank you, but I don't need any help just now.",
"I'm a gunner on a British warship. With great pleasure, I can teach you to calculate the trajectory of a cannon ball, and to hit your target every time.",
"I don't need your advice. I know this all very well, and can even teach you.",
"Tell me, and I will pay as much as you ask.",
"Thank you, but I don't need any help just now.",
"I'm a gunner on a British warship. I can tell you how to reduce your cannons' reload time.",
"I don't need your advice. I know this all very well, and can even teach you.",
"Tell me, and I will pay as much as you ask.",
"Thank you, but I don't need any help just now.",
"I'm a gunner on a British warship. I can tell you many stories about the art of grappling.",
"I don't need your advice. I know this all very well, and can even teach you.",
"Tell me, and I will pay as much as you ask.",
"Thank you, but I don't need any help just now.",
"I'm working in the shipyard, and I know all about repairing and building ships. If you'll pay me, I will teach your crew to repair the ship faster.",
"I don't need your advice. I know this all very well, and can even teach you.",
"Tell me, and I will pay as much as you ask.",
"Thank you, but I don't need any help just now.",
"I'm a trader. I can tell you some commercial tricks that will help you increase your profits from all your transactions.",
"I don't need your advice. I know this all very well, and can even teach you.",
"Tell me, and I will pay as much as you ask.",
"Thank you, but I don't need any help just now.",
"So, are you ready to pay me ",
"?",
"It seems that I haven't enough money.",
"I will pay you. Tell me your secrets.",
"No, it's too much.",
"So, are you ready to pay me ",
" for my secrets of fencing?",
"It seems that I haven't enough money.",
"I will pay you. Tell me your secrets.",
"No, it's too much.",
"So, are you ready to pay me ",
"?",
"It seems that I haven't enough money.",
"I will pay you. Tell me your secrets.",
"No, it's too much.",
"So, are you ready to pay me ",
" for the secrets of defense?",
"It seems that I haven't enough money.",
"I will pay you. Tell me your secrets.",
"No, it's too much.",
"So, are you ready to pay me ",
"?",
"It seems that I haven't enough money.",
"I will pay you. Tell me your secrets.",
"No, it's too much.",
"So, are you ready to pay me ",
" for my lessons in crew management?",
"It seems that I haven't enough money.",
"I will pay you. Tell me your secrets.",
"No, it's too much.",
"So, are you ready to pay me ",
"?",
"It seems that I haven't enough money.",
"I will pay you. Tell me your secrets.",
"No, it's too much.",
"So, are you ready to pay me ",
" for my secrets of maneuvering?",
"It seems that I haven't enough money.",
"I will pay you. Tell me your secrets.",
"No, it's too much.",
"So, are you ready to pay me ",
"?",
"It seems that I haven't enough money.",
"I will pay you. Tell me your secrets.",
"No, it's too much.",
"So, are you ready to pay me ",
" for lessons about cannon accuracy?",
"It seems that I haven't enough money.",
"I will pay you. Tell me your secrets.",
"No, it's too much.",
"So, are you ready to pay me ",
"?", 
"It seems that I haven't enough money.",
"I will pay you. Tell me your secrets.",
"No, it's too much.",
"So, are you ready to pay me ",
" for the secrets of cannons reloading?",
"It seems that I haven't enough money.",
"I will pay you. Tell me your secrets.",
"No, it's too much.",
"So, are you ready to pay me ",
"?",
"It seems that I haven't enough money.",
"I will pay you. Tell me your secrets.",
"No, it's too much.",
"So, are you ready to pay me ",
" for advice about grappling?",
"It seems that I haven't enough money.",
"I will pay you. Tell me your secrets.",
"No, it's too much.",
"So, are you ready to pay me ",
"?",
"It seems that I haven't enough money.",
"I will pay you. Tell me your secrets.",
"No, it's too much.",
"So, are you ready to pay me ",
" for my secrets of repair?",
"It seems that I haven't enough money.",
"I will pay you. Tell me your secrets.",
"No, it's too much.",
"So, are you ready to pay me ",
"?",
"It seems that I haven't enough money.",
"I will pay you. Tell me your secrets.",
"No, it's too much.",
"So, are you ready to pay me ",
" for advice in commerce?",
"It seems that I haven't enough money.",
"I will pay you. Tell me your secrets.",
"No, it's too much.",
"Thank you, you are so kind.",
"Don't mention it.",
"Would you like to buy more remedies?",
"Yes, I'd like to buy more.",
"No, excuse me for interrupting.",
"So you want to bargain?",
"Yes, I'd like to purchase something.",
"No, excuse me for interrupting.",
"What do you need? I thought we had covered it all.",
"No, nothing.",
"What orders, captain.",
"Nothing.",
"Do you want to hear some advice?",
"Yes, I'm interested in hearing what you have to say.",
"No, excuse me for interrupting.",
"Listen stranger - don't travel here at night. They say that dead men walk here at this hour.",
"Thank you for your advice.",
"I advise you not to walk here if you've got any problems with the law. There are lots of soldiers here. Perhaps you'd better sail away from this island.",
"That's interesting.",
"I'm not interested in this kind of advice. Goodbye.",
"But be warned. When you sail here again, they may not be very glad to see you again.",
"And besides...",
"I've got no time to talk to you.",
"You know, if I need any recent information, I go talk to a tavern owner. He can answer nearly all your questions.",
"Great advice. I'll definitely follow it.",
"As I can see, you are a fighting sea captain. Remember - take more officers. Sometimes without their help, you can't survive.",
"Yes, of course.",
"I can see by your bearing that you are a sea captain. If you need a ship - buy it in our shipyard. If you don't find the exact ship you want, wait for a couple of days, and perhaps one will appear.",
"Good advice. Thank you.",
"Sometimes you may meet people that have traveled far across the world. You might ask their help, and they might increase your skill in some area. I can assure you - their knowledge is priceless.",
"Not bad advice. Thank you.",

};
