string DLG_TEXT[38] = {       
"Maybe you need an officer, captain?",
"An officer? And what can you do?",
"No, I have enough officers for now.",
"Well, people says I'm a good ",
". Hire me for your ship, captain, and you'll see for yourself.",
"How much do you ask?",
"Alas, I already have a ",
".",
"Did you change your mind, captain? Decide that it might be useful to hire a new ",
"?",
"Yes, perhaps. How much do you want?",
"You're wrong. Goodbye!",
"I think we'll agree on ",
" gold.",
"Isn't that too much for you?",
"I agree. Consider yourself hired.",
"You aren't worth that much. Farewell.",
"All right. I think then that I might agree to ",
" gold. How is that?",
"That's better. I welcome you to my crew.",
"I still think that is too much. Farewell.",
"Unfortunately, captain, I'm sure I'm worth what I'm asking. If it's too expensive for you - find someone else who will ask less.",
"Well... You're hired.",
"That's just what I'll do. Goodbye.",
"Thank you, captain. You won't regret that gold when you'll see me in action.",
"I hope so.",
"Hey, it looks like you're out of cash! Sorry, captain, but I don't work for credit.",
"Damn!",
"Let me finish my drink first, captain. But rest assured - I'll be aboard before we sail.",
"All right. If I have to wait for you - you be scrubbing the decks. Alone!",
"At your service, captain? Any orders?",
"No, stand at ease.",
"You're fired. I don't need your services!",
"As you say, captain! But look - if you fire me, I will never return to your ship. So, you decide.",
"Well. I have changed my mind. I still need you.",
"Great! Get lost!",
"I told you, captain, I won't return. I have my own pride.",
"And I don't need you, either!",

};