string DLG_TEXT[44] = {
"Stop! Drop your weapons! Stand and deliver, or die!",
"Hey, traveler! Slow down! We wanna take a look at your purse!",
"Halt, you! Pay the toll if you want to pass!",
"What is this nonsense?",
"What is it?",
"What do you mean?",
"Brigands! Well, crime must be punished. To arms!",
"I can't stomach common highwaymen, especially untidy ones. En garde!",
"I'll cut your heart out for your impudence!",
"Oh, he doesn't get it! It's simple: You give us all your gold, and we let you live!",
"Haven't you heard of 'traveling expenses'? Well, that's us. Now part with your gold, or part with your head!",
"I'll translate for the stupid sailors: Give us all your money, matey! We love the doubloons and pieces of eight!",
"You mangy curs! I've got only ",
" gold.",
"I won't surrender my gold without a fight!",
"Hey, don't get excited! I was just kidding. Go on, now!",
"In that case, we've changed our minds. You can go.",
"You're a brave man, so we'll let you go! But don't let us catch you again.",
"Well, so long, then!",
"You should quit this foul business. You're not very good at it. Goodbye!",
"You've made a wise decision. Goodbye!",
"It's too late to back out now - you've got an appointment with your maker!",
"Turning coward, lads? But I can't let you go now!",
"I'm not going anywhere until I finish this.",
"All right. You had your chance. Now you'll die!",
"Okay, now you've made me mad. Die!",
"What?! We'll have your guts for garters!",
"Try it!",
"All right! Give 'em to me, and you can go!",
"Well, today it's enough to buy you your life. You can go.",
"Let me give you some free advice - if you're such a easy mark, you shouldn't be wandering around the jungle! Stay in the port and drink your rum. You'll live longer.",
"Blast you all!",
"You look to me like a richer man than that. But that's okay. When we're finished with you, we'll turn you upside down and see what shakes out!",
"Blast!",
"You again?! You should be running as if the devil's chasing you! Otherwise, we might change our minds about letting you go.",
"You've come to share more gold with us? How very kind of you!",
"I'll only say this once: get out of my sight before I cut you down!",
"Yes, yes! I'm just leaving.",
"I don't want any more trouble from you terrible ruffians - so I've decided to get rid of you!",
"What do you want from us? We let you go!",
"Leave us alone, lad. We've got our business; you've got yours. Let's leave well enough alone.",
"Get lost, lad! Do you really want to part with your money?",
"All right. I'm going.",
"I've decided to punish you for your evil deeds!",

};
