string DLG_TEXT[38] = {
"Can I help you, ",
"?",
"Ah, it's you, ",
".",
"I'd be glad to have a chat with you if I weren't so busy. A good day for the tavern isn't always a good day for talking!",
"...",
"Oh, please, captain, don't start a drunken spree here! You can't imagine how hard is cleaning up afterwards!",
"Ahem...I wasn't thinking of any such thing.",
"Oh, captain! Wouldn't you like to sample my charms? I don't like to boast, but...",
"Sorry, babe, I'm in a hurry now. How about next time?",
"If you want to order a drink - talk to the owner. He is standing at the bar.",
"Thanks for advice.",
"If you want to have a rest and replenish your health - rent a room for a night. Mind you, sleeping in the common hall won't help you recover.",
"Thanks, that's good to know.",
"Yes? What can I do for you?",
"I wanted to talk to you about ",
"Father Jerald",
"Father Jerald",
", the local priest.",
"Some priest! He won't stop making advances. Can you imagine? I complained to everyone, but no one believes me.\nHe even wrote me love letters, if you please!",
"Are these the letters?",
"Yes, they are. You must have gotten them from ",
"Gilbert Ballester",
"Gilbert Ballester",
". So are you here because of his complaint?",
"How do you know he lodged a complaint?",
"Well, he told me about it when I brought him these letters.",
"All right. Thanks for your time. I'll let you get back to work.",
"Are you awake?",
"Ohhh...",
"Are you all right? How's your head?",
"Where the hell am I?",
"Don't you remember? You were robbed!",
"What? Oh...my head.... Who dared...?",
"How should I know? They came, threatened me, went through your pockets, and left.",
"All right. What's lost is lost.",
"Hey, Raymond! Is everything cancelled now? Do I have to return the money?!",
"...",

};