string DLG_TEXT[29] = {
"Cough-cough...blasted weather! My name is ",
", and I am the best ship-builder in these islands.",
"I beg to differ - I think the weather is wonderful. My name is ",
".",
"Enough of your moaning! My name is ",
". I assume you've heard of me.",
"Oh, it's you again, with your problems...cough-cough!",
"You may not have your health, but your memory is fine. Now let's get down to business.",
"That's right, it's me again, and you're as tiresome as ever. Let's just talk business.",
"Sorry to bother you. I should go.",
"You know, I've heard enough of your complaints about life. Goodbye.",
"You young people are so disrespectful these days! You've got passion and strength, what else do you need?",
"You must've been young once, yourself. Have a little patience.",
"Yes, and I guess your youth passed away so long ago, you can't even remember it.",
"Show some respect for your elders, cub!",
"Please don't raise your voice to me again. Can we just get down to business?",
"Watch your shriveled tongue, old man, or I'll put you out of your misery! If you're smart, you'll close your mouth and think about business.",
"I'm sorry. I can see there's no point in talking to you.",
"That's enough idle talk for me! Goodbye.",
"Yes, yes - all right! So what do you want from me, ",
"?",
"I'd like to use your shipyard's services.",
"I need the services of your shipyard. ",
"Sorry - I've got to go.",
"I've got urgent business elsewhere. I'll be going now.",
"What exactly do you need?",
"I need to repair my ship - although I might consider just scrapping it and buying a new one.",
"I need to install new guns on my ship.",
"Nothing, thanks.",

};