string DLG_TEXT[134] = {
", my son! How can this humble servant of God help you?",
"I'm ",
", captain and owner of the ship '",
"'.",
"Welcome to the house of God, ",
"my son. I'm glad to see a sailor who doesn't neglect his soul.",
"Hello, ",
". So - are you here for confession?",
"My son, I'm glad to see you and am ready to take your confession if you would freely give it. The Lord knows that sin is unavoidable in earthly life.",
", I'd like to give a gift to the Church.",
"I need to talk to you, father.",
"Thank you. Maybe next time.",
"I'm pleased to welcome a new sheep to our flock",
".",
"Then please accept my gift.",
"Can I talk with you, father?",
"Thank you, father, but I must go.",
"Is this concerning your faith, my son?",
"Maybe. I can't help but notice that you seem worried about something. Can I help you somehow?",
"This is concerning the business you entrusted me with.",
"Possibly. I can see in your face that something disturbs you. Maybe I could help.",
"I have a letter for you.",
"Who would have thought that ",
"Father Gareth",
" could serve the Prince of Darkness? Who could have thought...",
"But now I know who is to blame for my recent troubles. It was he who reported all my movements to the monks!",
"I need permission to free a prisoner being held in Oxbay.",
"I've managed to acquire the permission you asked for. Here it is - and please remember my faith in you.",
"Don't worry - I'll do it right.",
"No. Let's talk about something else.",
"There's more - my men and I have destroyed the sect.",
"No. Thing is, there's a man who'd like to donate a certain amount of gold to your church. I'm fulfilling his request.",
"Um... No. Let's change the subject, all right?",
"Oh, thank God! You did it! I'll order to perform a service to celebrate this wonderful feat!",
"Now, if you'll excuse me, I must go to Douwesen, to return the missing children.",
"I'm afraid this is outside my realm...",
"I don't believe it. This prisoner is one of those you've asked me to destroy.",
"But if that's so, then why free him?",
"I'll need to gain his trust. He knows where their lair is, and he'll be much more likely to tell me if he believes I'm on his side.",
"I understand. Yes, I'll see what I can do. Wait here.",
"All right.",
"Monks? Those are no monks - they're the servants of the devil!",
"As you say, father. But they all wore the robes of a monk.",
"Yes, of course. But first we must find the lair of these devils. I think it would be wise for you to travel to Isla Muelle and ask some questions there.",
"Then bless me, father.",
"May God be with you, my son",
"I won't fail you.",
"There's something else. I'd like to introduce someone...",
"Yes?",
"But we're wasting time. Do you accept my offer?",
"As I recall, you offered me 15000 gold pieces for the sect's demise. Correct?",
"Aha! I was wondering if ",
"Padre Domingues",
" had managed to send it.",
"What do you mean?",
"Of course - you probably don't know yet. The man who gave you this letter was kidnapped! I'm afraid my worst fears have come to pass.",
"How do you mean?",
"Several years ago, a animist lair was destroyed in Italy. Unfortunately, the head of that order managed to escape, and he settled here in the archipelago\nNow, judging by the disappearances of children and a ranking priest, he's active again and intends to conduct a certain ancient ritual. We must stop him!",
"And what is my part in all of this?",
"I need you to serve as the swift sword of God, acting out His vengeance. But I understand that you are a man of business, so I offer you 15000 gold pieces for your service to the Church.",
"That's not bad...",
"Ah, it's you. I'm glad to see you still visit the house of God. And it's a blessing from the Lord that you're here now. I need your help.",
"I'm listening, father.",
"I'm afraid your ill fame prevents me from asking for your aid in matters of the Church.",
"Frankly, that doesn't worry me too much.",
"This business is urgent and more complex that it may sound.",
"Perhaps you'll be kind enough to give me the details?",
"Some children were abducted from the Dutch colony...",
"I know something of that - although all I've heard is that the children were loaded onto the black frigate 'Mefisto,' and then she vanished in an unknown direction.",
"I didn't know about that. I think your news might explain some things\nBut let's get to our business: I want you to deliver a message to Isla Muelle and hand it to a man named ",
"Padre Domingues",
"Padre Domingues",
".\n He is a ranking priest of the Church in Spain. He'll give you further directions, if necessary.",
"That seems very simple. What makes it so complex?",
"The last man who agreed to carry my message was found dead today on the threshold of his home\nAll he was able to say with his last breath was something about men in red cassocks, armed with daggers.\nIt would seem that someone is willing to kill to be sure this letter isn't delivered.",
"So someone may try to kill me as well.",
"I'm afraid that's true. I'll understand if you refuse.",
"Oh, the money's far too good to refuse, father.",
"Excellent. Here's the letter. Remember, you must give it to ",
"Padre Domingues",
", and only to him. And you'll find him on Isla Muelle.",
"All right. This shouldn't take long.",
"What did you manage to find out?",
"Father Jerald",
"Father Jerald",
" is guilty of the crimes he's accused of.",
"Father Jerald",
"Father Jerald",
" is innocent of the crimes he's accused of.",
"Do you have proof of that?",
"I do. These letters appear to smear the priest's reputation - but in fact they were written by his assistant.",
"What a cruel deception! I'll resolve this immediately. You've done an excellent job in the service of the Church. I'm pleased to give you your reward\nPlease, keep visiting me from time to time - I'm sure I'll need your services again later.",
"Thank you, father.",
"Do you have evidence of this?",
"Yes. These letters tell the whole story.",
"I see. I had hoped it wasn't true. But you've done your job. Here is your reward\nPlease, keep visiting me from time to time - I'm sure I'll need your services again later.",
"Thank you.",
"You see, I need help in a serious matter, and I would prefer to find that help outside the Church.",
"Some people would say I'm very much outside the Church, father. But tell me what troubles you, and perhaps I can help.",
"I'm afraid your reputation doesn't allow me to accept your help.",
"Fair enough.",
"All right. I sense that I can trust you. But let me hear you swear that no one will learn of this conversation.",
"You may consider yourself in my confessional, father.",
"Fine. Then listen: rumors have reached me that one of my brothers in faith has forgotten his vows to the Lord and is mired in sin.\nUnfortunately, I can't leave my flock to check on these rumors myself, and it will only arouse suspicion if I send someone else from our brotherhood\nBesides, only I alone can challenge him to such a conversation, and look into his soul to see if he's telling me the truth...",
"So...you're asking me to gather evidence against one of your fellow priests?",
"Not at all! No, I simply want to know whether or not he is guilty of the sins he's accused of\nIf he's innocent, then I want to know who has blackened his reputation.",
"All right, father. Give me his name, and I'll see what I can find out.",
"He serves the Church in Greenford. His name is ",
"Father Jerald",
"Father Jerald",
". It should be easy enough to find him once you get there.",
"I'll return as soon as possible, father.",
"May God guide you to the truth, my son. Come here and accept my blessing.",
"That's all right, father. I'm sure everything will be fine.",
"As you wish. But it's my duty to tell you that such disregard for your faith is unwise.",
"I know. Accept my gift to the Holy Church.",
"I'm sorry, father, but I have to go.",
"Of course, my son. How much do you want to give to the Holy Church?",
"I'm sorry, father, but I've just realized I can't make a donation at the moment.",
"I'm afraid 100 gold pieces is all I can afford just now.",
"I should think the Lord would look kindly on 1000 gold pieces.",
"I'm doing well these days, so I'll give 5000 gold pieces.",
"It's your decision, my son. It's never too late to change - and keep in mind that all will be taken into account at the time of your death.",
"My death is still a long way off, God willing! Let's talk about something else.",
"Sorry, father. I've got to go.",
"I thank you for your gift in the name of the Holy Church, my son.",
"I need to talk to you, father.",
"I'm sorry, father, but I must be on my way.",
"I thank you for your gift in the name of the Holy Church, my son.",
"I need to talk to you, father.",
"I'm sorry, father, but I must be on my way.",
"I thank you for your gift in the name of the Holy Church, my son.",
"I need to talk to you, father.",
"I'm sorry, father, but I must be on my way.",

};