string DLG_TEXT[56] = {       
"! Let me show you the town only for one gold piece!",
"Who are you?",
"I'm not a tourist, and I don't need a guide!",
"My name is ",
", ",
". I'm a sailor from the 'Oiseau.' We're waiting here for an escort ship.",
"I see. Let me ask you a couple of questions.",
"All right. You can go, sailor.",
"Yes, ",
" captain. I understand.",
"You can go.",
"Yes, I have ",
"! But information costs a little bit more!",
"How much do you want?",
"Five gold pieces, ",
".",
"All right. Take your money.",
"I don't have that kind of money now.",
"I'm not going to pay you to answer questions!",
"Thank you, ",
". Now what did you want to know?",
"You said you were from the 'Oiseau'...",
"I'm sorry, ",
". but I'll wait until you bring the money ",
"It's a deal.",
"Yes, sir, ",
". It's my third year of sailing on her.",
"And you're waiting for an escort ship to arrive?",
"Where is your ship headed?",
"No, ",
", it's already in port. It's being loaded with provisions and ammunition now, but we'll put to sea any day.",
"What kind of ship is this?",
"Where is the captain of this ship?",
"That's everything I wanted to know. You can go.",
"Alas, ",
", I don't know. We sailors weren't told. It's probably a secret. Military business, maybe.",
"And you're waiting for an escort ship?",
"That's everything I wanted to know. Thanks.",
"It's a brig called 'Le Requin.' It's not part of the French king's fleet. The captain is a civilian who was recently hired to guard our ship.",
"Where's the captain of this ship?",
"That's all I need. You can go.",
"I don't know, ",
". But you can ask at the tavern. I know he was there earlier, and he may still be.",
"And what's the name of 'Le Requin's captain?",
"Amiel Berangere",
"Amiel Berangere",
", ",
".",
"Thank you, ",
".",
"Hello again, ",
". You need ex Ksurso...Vorsa...again. Unfortunately, I don't remember what you called me that time, sir.",
"Hello again, ",
". I think you said you didn't need my services, correct?",
"No, but I do have a question.",
"You're right. Goodbye, sailor.",

};