string DLG_TEXT[42] = {
"I'm pleased to meet you, ",
". My name is ",
", and I am at your service.",
"My name is ",
", ship's captain.",
"Good to see you again, ",
".",
"You?! I'd hoped I'd never see you again.",
"And a good day to you, too, ",
".",
"No way.",
"Would you like to see my goods?",
"Sure. Show me what you've got.",
"Later. Let's talk first.",
"Maybe next time.",
"Do you have merchandise to sell, or do you just need some personal items, captain?, ",
"I'd like to sell the cargo I've brought.",
"I'd like to buy a few things for myself.",
"We won't trade at all. Goodbye.",
"I'm listening.",
"I was asked to deliver some cargo to you.",
"Surely you must have some job you'd like done. I'd be happy to lend you my services for a fee.",
"I'm sorry, but I've lost interest in our conversation.",
"No, I don't need your services...and I won't need your services so long as you're sinking Holland's ships.",
"In that case, goodbye.",
"I'm sorry, but I don't have anything for you at the moment.",
"I'll come back later, then.",
"I'm sorry, but your ship lacks the capacity for the task I have in mind.",
"I'll come back later, then.",
"Oh! I was just going to ask you to do me a favor. The thing is, I need some cargo delivered to ",
", and as soon as possible. If you manage to do it in a month's time, you'll receive ",
" gold when you arrive. How do you like this offer?",
"I definitely like it.",
"I can't accept it.",
"I already told you today that I don't have anything for you.",
"Oh, sorry.",
"You've remembered about your assignment a bit too late, don't you think? I've already received everything I need. Goodbye.",
"Farewell.",
"Oh! I've been waiting for this. Here is your reward, young man.",
"Always welcome.",
"I'm sorry. I have nothing for you now.",
"That's a pity. Perhaps you'll answer some questions, then.",

};