string DLG_TEXT[44] = {
"What business brings you here?",
"Governor ",
"Robert Christopher Silehard",
"Robert Christopher Silehard",
" has entrusted me to deliver this letter to you and take custody of a prisoner.",
"Governor ",
"Robert Christopher Silehard",
" sent me to retrieve the sacred Incan idol for him.",
"I'm carrying orders to free one of your prisoners.",
"I need to talk to a prisoner.",
"Go on, then. Talk to him.",
"Good.",
"I'm just passing by.",
"Well, generally we don't allow visitors...",
"But this is vital State business!",
"What business? What are you talking about?",
"You must have heard about the child kidnappings and other strange things going on throughout the archipelago. Well, I believe your prisoner can help me get to the bottom of it all!",
"Please - I need to talk to this man!",
"All right. It can't hurt for you to talk to him, I suppose. We hang him in the afternoon anyway.",
"Good. Thank you.",
"You're wasting your time. Although...if you could do me a favor...",
"What favor?",
"My son is getting married soon. I'd like him to have a proper wedding. So, if you want to talk to the prisoner, it'll cost you 5000 gold.",
"Here's your money.",
"I don't think that's going to happen. Can I offer another solution?",
"You tire me. Please leave. You won't be talking to anyone!",
"I'm sorry it's come to this, but I'm afraid you leave me no choice...",
"All right. But I'll be back.",
"What the...",
"You will escort me to the prisoner now, or I'll run you through!",
"You'll pay for this!",
"Probably, but not today. Today, you're my prisoner, and I want to talk to yours.",
"All right! You can talk to him.",
"...",
"Let me see that. Hmm...the Teacher himself, is it? All right, you can take him.",
"Good.",
"All right. But let me see the orders first.",
"Are you serious? You know I work directly for the governor, and you ask me to show you some slip of paper?!",
"I'm sorry, but I've got orders of my own. I'm to send the idol via warship to Redmond, and I'm to arrest anyone who tries to take it without the proper documents. Guards!",
"Blast!",
"I'm afraid I can't give you the prisoner at the moment.",
"What do you mean you can't give him to me?",
"Tell the Governor that the prisoner...escaped last night, and we still can't find him.",
"Oh, you can be sure I'll tell him. And if I were you, I'd find that scoundrel!",

};