string DLG_TEXT[98] = {
"Oi, lad, you look like an experienced sea dog! Buy me a cup o' rum, will ya?",
"I'm not feeling particularly charitable at the moment.",
"Sure. And I'll join you.",
"Hey! Do you wanna play some dice? I recently came back from a very successful expedition, so I've got money to lose!",
"Really? You don't look like it.",
"Don't distract me from my drink!",
"...",
"Don't even look my way! You've got a reputation as the best dice player on these islands. I'm not risking it.",
"Fair enough.",
"They say you're a fine dice player. Want to play a bit?",
"Why not? Let's play.",
"Not right now.",
"Hey, lad! You wanna shoot some dice?",
"Oh! Glad to see you, ",
". Do you want to play some dice? Roll the old bones?",
"All right, sure. Let's play.",
"Maybe some other time.",
"I've already lost a fortune, but I still got something to bet!",
"And what would that be? Your moth-eaten coat?",
"No, no, no - I've still got some loot left. Look here!",
"All right - let's see what you're hiding.",
"Well...I can't show you here. I've rented a room nearby, though. Let's go there.",
"No, thanks. Some other time.",
"Okay. I'm probably going to regret this, but you've got me curious. Let's take a walk. ",
"Innkeeper! Keep this table free until we get back!",
"Nobody's going to take it. Let's go.",
"See that beauty? I'll put her up if you'll give me a chance to win some of your money.",
"Well, she is beautiful...",
"Too right, she is! But a game's a game.",
"All right. Let's play.",
"How dare you make such a wager?!",
"Ah, forget it! We play by the standard rules! 100 gold pieces a round!",
"Fine, but let's do it here. You have the dice?",
"I do. I'll roll first... ",
"!!!",
"My turn. I got... ",
"! You lose, lad!",
"Blast it! What happened to my luck? All right, take the girl and go!",
"With pleasure.",
"What?",
"You filthy pig! You don't deserve to live!",
"Are you trying to trick me? Well, it won't work!",
"Are you looking for trouble? You've found it!",
"Let's do it! I bet 100 gold pieces.",
"I'll back that up. Throw your dice.",
"I won't play.",
"Enough! I'm not playing with you anymore.",
"As you wish. I'll go find someone else to play with.",
"! I've seen better throws. Your turn.",
"! Not the best throw, but we'll see how you do.",
"! Not bad, not bad! You'll need to do better, though.",
"! I'm hot today!",
"Gimme the dice.",
"! ",
"You've lost, lad!",
"Take it. But I bet I'll win this time!",
"All right, you win. But I'm not playing anymore.",
"! ",
"You won! Dash it all! All right, one more time.",
"Try it, you won't win anyway.",
"Not this time.",
"Hmm. A draw. I hate draws. Once more?",
"Sure. Throw the dice.",
"No, I don't want to push my luck.",
"Now, this I like! So, will ya buy me a cup o' rum?",
"Certainly. Innkeeper! Rum!",
"You're a true friend! Cheers to us!",
"Whoa. Strong stuff!",
"To your health, and your generosity!",
"Cough-cough-cough.... That's smooth! Well, I've got to be moving on. See you around.",
"Let's have one more cup.",
"Twist my arm! Okay, why not?",
"Innkeeper! More rum!",
"You...you're trying to get me drunk and steal my money!",
"Settle down! I'm your friend, remember?",
"Shut up, rat, before I run you through!",
"Listen, you're a good man. Maybe you can help me with...a certain situation?",
"No. I have to be going.",
"Of course! We're friends, right?",
"...And then I grabbed the blade of his sword and...",
"...and she says to me, she says...",
"Cheers! Ah, who's this?!",
"Huh? What? Where?",
"The thing is, you see, one of the soldiers insulted me...yeah!",
"Soldiers? No, no. I think I'll pass.",
"Insulted?! Where is he? Lead me to him!",
"You're not my friend! No! You want...to...you want to kill me! That's right - to kill me!",
"All right, I see you've had enough for today. So long!",
"What? I don't want to kill you! Stop saying that, or I'll cut your head off!",
"Help! Get him off me!",
"Relax, this won't hurt!",
"Argh! I'll butcher you like a pig!",
"We'll see about that!",
"You're so stubborn! Come here, or I'll complain to your master and you'll be out in the street!",
"You're drunk, you pig! You're lucky I don't want to get my hands dirty by teaching you a lesson!",
"What?! It's me who's going to throw you out!",
"Where did you get a sword? I'll show you!",
"The only thing you can show anyone is how to make a fool of yourself! Get up out of that chair, and we'll see if you can handle me!",

};