string DLG_TEXT[30] = {
"Hello. I am an officer ",
" of His Majesty of France.",
"My name is ",
".",
"Did you approach me for a friendly chat, or do you have some actual business with me? ",
"I thought we might chat for a bit.",
"I'm here on business, officer. Rather important business.",
"I'm afraid I must disappoint you, then, ",
". I have no time for idle talk.",
"I'm sorry.",
"What kind of business?",
"It's concerning a merchant named ",
"Patric Cardone",
"Patric Cardone",
".",
"The man whose Indian relics were stolen.",
"That's right.",
"And what does that have to do with me?",
"Do you know where ",
"Lucien Bescanceny",
"Lucien Bescanceny",
" lives?",
"Of course I do. He's made quite a name for himself with his illegal activities.",
"Indeed. And if you'll pay him a visit, you'll find he has a lot of interesting information about the statuettes that disappeared.",
"What makes you think he would talk to me?",
"Maybe he won't. If he refuses, then search his room. You'll find the statuettes in there.",
"How can you be so sure?",
"I've already been to his place. He confessed everything.",
"All right, I'll go and talk to him. But if this is some sort of scam...",
"It's no scam, officer. You'll see.",

};