string DLG_TEXT[29] = {       
"I'm told you've gone to great lengths to request an audience. My name is ",
". Now, if you please, tell me the purpose of your visit, ",
".",
"My name is ",
".",
"Ah, it's you again. What brings you here this time? ",
"I'd like to talk to you about some business.",
"I'm sorry, but there are things that I have to do.",
"So, why do you distract me from the very important affairs of state?",
"I'd like to talk to you about a small piece of business.",
"I'm just here to pay my respects, sir. Nothing more.",
"In that case, please leave my study and let me get back to more important matters.",
"Yes, of course. Sorry I disturbed you.",
"I'm listening, ",
".",
"I'm here to get my reward for the death of Dirty Garry.",
"I'm sorry, but I don't have anything to talk about right now",
"Oh, I've heard about what you've done. From the face of all colony I will show you our appreciation.",
"That's right, I'd like to see a reward.",
"You're such a joker. Ha ha. Here is your money.", 
"Thank you, I'm your humble servant.",
"So, about the bet you made...after getting the approval of our tax department I see we've got...let me look...six thousand.",
"What?! The deal was 10 thousand!",
"I can't help you. In the future, try to be more calm.",
"Whatever you say, sir. Dirty swine...",
", are you aware that you stand accused of murder? You were seen near the victim's body. What do you say in response to this charge?",
"It has nothing to do with me. The man was already dead when I entered the room! I was told he was only injured, and that he might have some important information for me.",
", I've just been told that a man was captured as he attempted to leave town with a blood-stained knife in his possession. He confessed to the murder you were accused of. You may go free immediately.",
"Thank you. I knew I could trust in justice here on Conceicao.",

};