string DLG_TEXT[84] = {
"Who are you,",
"?",
"I'm ",
", captain of the '",
"'.",
"My name is ",
", and I am, of course, the governor of this colony.",
"Happy to make your acquaintance, sir.",
"Oh, I've heard a lot about you, ",
". They say you're quite a good captain, and that you've become well-known.",
"I'm pleased to hear that, sir.",
"So what can I do for you, ",
"?",
"I'm looking for work. Would you happen to have use for my services?",
"I'm afraid I have to refuse the assignment you gave me, sir. That English warship is too much for me to handle.",
"I've just come to talk for a moment.",
"Talk? What do you take me for, ",
"? I'm an officer of the state. I don't have time for idle chatter!",
"I beg your pardon, sir. I'll go.",
"In case you're not aware, my country is at war with England. I don't see how you can help me, ",
".",
"That's a pity, sir.",
"Yes, I think I can find you an assignment.",
"Excellent! What will it be?",
"I heard about your defeat of the English warship. Congratulations, ",
". It was a brilliant victory!",
"I'm happy to serve you and France, sir.",
"I can't say I'm happy to see you, but I don't suppose I have any choice - you've got some very influential friends.",
"Thank you, sir.",
"So, one of the most wanted men in the archipelago appears right in front of me? Guards!!!",
"Call off your men at once, or a certain lady by the name of ",
"Virginie d'Espivant",
" will die. I don't believe her father will be happy to learn you could have prevented her death.",
"I'm listening. What do you want?",
"On my ship I have a lady named ",
"Virginie d'Espivant",
"...",
"You've found her?! Thank God! But, tell me captain - is she a prisoner on your ship?",
"Exactly, sir. Although it was pure coincidence that I found her.",
"Of course not! On the contrary, she's my honored guest.",
"I'm pleased to hear that. How did you find her?",
"It's a long story, sir. I'm sure ",
"Virginie d'Espivant",
" will tell you herself, if she deems it necessary.",
"Yes, of course. I won't delay you anymore. Accept this money with my deepest thanks, and I'll arrange for the girl to be escorted from the port when you deliver her to the shore.",
"Certainly, sir.",
"So you're holding her there for ransom?",
"Yes. And I'd like it noted that she got there by pure coincidence.",
"It's noted. Now, what do you want for her freedom?",
"Money. And unhindered passage back to my ship, of course.",
"How much?",
" I think 7000 gold will be enough.",
"What? Are you out of your mind?!",
"Do you really think this is an appropriate time for haggling, sir?",
"All right. Here's the money. And you have my guarantee of safe passage to your ship. Let the girl go.",
"Your guarantee? I'm told you're a man of your word, but I'm not going to risk my neck to find out. You'll get the girl when I've put to sea.",
"Very well. But be warned: cross me, and I'll order every available ship to bring me your head!",
"Agreed.",
"I see. Well, I am forced to say this - I had to forgive you all of your crimes against my country...",
"Such an honor, sir!",
"Mind your sarcasm! If I had my way, you'd be hanging in the town square. You have the young lady you saved to thank for my generosity.",
"My gratitude is infinite, sir!",
"I'm sure. Moreover, I'm ordered to pay you a reward. Here it is. And now, please do me one favor: leave.",
"With pleasure, sir.",
"An English warship is blocking trade routes in our waters, and our fleet is busy elsewhere with an important operation.",
"You want me to sink that ship, sir?",
"I think I know what you're going to ask of me, but I must refuse.",
"That's right, ",
". I'll pay you 5000 gold to sink the warship.",
"Agreed. I'll take the mission.",
"No. That's not near enough money to persuade me to fight an English warship. I'm forced to refuse your offer unless you'll raise the reward.",
"Excellent. I wish you luck, ",
".",
"Have no doubt, sir. I'll handle this mission.",
"I'll not barter with you like some petty trader! I'm a nobleman. Take the mission or get out of my sight!",
"All right. I'll sink the warship, sir.",
"You'll have a hard time finding a captain willing to do your dirty work for such meager rewards!",
"Here, take your reward, and don't stray too far. I may have more assignments for you later.",
"Of course, sir. I'll let you get back to your work. Goodbye.",
"I must say I'm disappointed to find that you're such a coward.",
"Say what you will, sir. But I value my life more than your gold.",
"Take that back, sir! I'll do it, but don't insult me again!",
"You disgust me. Leave my office at once!",
"As you wish, sir.",

};
