string DLG_TEXT[45] = {
", dear visitor! I'm ",
", owner of the local shipyard.",
"And I'm ",
", captain of the ship '",
".'",
", ",
". Do you need my shipyard's services, ",
"?",
"As a matter of fact, I do need you to patch up a couple of shell-holes and mend some sails.",
"Right now, I just need to talk to you.",
"No, I just thought I'd stop by.",
"Well, I'm very pleased to meet you. If you are a captain, then my shipyard is always at your service.",
"Perfect, ",
". Let's get started on those repairs.",
"Thanks. But first, let's talk.",
"Next time, perhaps. I've got to be on my way.",
"What exactly are you interested in, ",
"?",
"No, I don't believe I do.",
"I see. Do you need anything else, ",
"?",
"I'd like to put a couple of patches on the old wash-tub that brought me here!",
"That's all, thanks. Farewell!",
"What exactly do you need?",
"I need to repair my ship - although I might consider just scrapping it and buying a new one.",
"I need to install new guns on my ship.",
"Nothing, thanks.",
"How can I help you, captain?",
".",
"I need to talk with Florens Clauss.",
"How can I help you, sir?",
"I need to talk with Florens Clauss.",
"Clauss? He owes me 5000 gold. If you're willing to pay off his debt, you can talk with him as much as you like.",
"Fine. I'll cover his debt.",
"I'm afraid I don't have that kind of money.",
"You're too late. Clauss's debt was paid by one of the local pirates who lives near the city. I'd advise you not to seek them out - they don't care for strangers.",
"So the pirates have Clauss now. I see....",
"Do you need my shipyard's services?",
"Nice to meet you.",
"Do you need my shipyard's services?",
"Perfect, ",
". Let's get started on that repair.",
"Thanks. But first, let's talk.",
"I have changed my mind. I'll give you 5000 gold to pay Clauss's debt.",
"Maybe next time. I've got to go.",

};
