string DLG_TEXT[33] = {
"Do you have some goods to deal, or do you just want to buy some gear?",
"I want to sell some goods I've brought.",
"I'm looking to buy some gear.",
"Neither. Farewell!",
"Hello, ",
". My shop is at your service.",
"Thanks. My name is ",
".",
", ",
". It's nice to see you. Are you ready to make a deal ",
"?",
"Well, what goods have you brought to Redmond this time, Captain ",
"? Or maybe you didn't come here to trade.",
"Oh, captain! Glad to see you.",
"Let's see what you've brought for sale.",
"Right now, I'd like to talk.",
"Farewell.",
"I'm glad to meet you, sir. I am ",
". I hope we can do business.",
"Well, ",
", let's see what you've brought for sale.",
"I'd like to talk to you, ",
".",
"Goodbye.",
"Talk? Sure, it's a pleasure to chat with you, captain.",
"Actually, I'm not in the mood to chat right now. Sorry.",
"As you wish, ",
".",
"Let me take a look at your goods.",
"I've got to be going. I'll see you soon.",
"Alas, ",
", the French have confiscated the better part of my goods and ammunition, and they've forbidden me to sell the rest until the war ends.",
"Well, that's bad luck for both of us....",

};
