string DLG_TEXT[249] = {
"Greetings, captain! I'm your boatswain ",
".",
"Yes, I know.",
"Yesterday you asked me to remind you of some things that you planned for today.",
"Really? Alright, go on then.",
"I remember everything just fine. Thanks.",
"First of all, take your personal equipment. Remember, you should always have your blade, pistol and spyglass with you. Who knows what can happen in these colonies.",
"Where did I put it?",
"Your sword is here, on the chest. And all other stuff is inside your wardrobe. Just come close to it and you'll see the Hand Icon in the top left corner of the screen\nThis means you can do something here. When you see the icon, just press the 'Open Command Icon Menu' button, select the command 'Take' from the icon list and then press the 'Action' button.",
"I see.",
"If you use a box or a chest in this manner, you'll see an interface which will allow you to take items from the container or put them in it\nNow, go take your possessions, captain, and talk to me again when you're done.",
"Alright, hold on.",
"Haven't you forgotten something, captain? It looks like you haven't taken all of your possessions yet.",
"Oh yeah, how could I forget!",
"Great! Now you should equip your weapons and spyglass. To do that press the 'Open Player Status Screen' key and then select Items from the menu. Press the 'Action' key. Then select the item you want to equip\nNote that your blade should be equipped before your pistol. Also not all items can be equipped. Now equip your sword, pistol and spyglass, then talk to me again.",
"Just a second...",
"Great. By the way, sir, I could teach you a bit about swordplay, if you'd like. Just ask me.",
"I guess I could use some training. Teach me.",
"Some other time. Let's continue with today's schedule.",
"I'm getting tired of this. That's enough.",
"Sir, please equip your weapon. You never know when you'll have to fight here.",
"I'll do it now.",
"Great. By the way, sir, I could teach you a bit about swordplay, if you'd like. Just ask me.",
"I guess I could use some training. Teach me.",
"Some other time. Let's continue with today's schedule.",
"I'm getting tired of this. That's enough.",
"Hey, cap, you forgot about your pistol. It should also be equipped.",
"Oh yeah, how could I forget that!",
"Sir, your pistol is only a secondary weapon - you should equip a blade too.",
"Alright.",
"No problem, sir. Pay attention, please. In the bottom left corner you'll see your character icon. The red bar above it is your health. The blue bar represents the loading status of your gun. And the circle above those bars shows how many shots you have left in your pistol.",
"I understand.",
"Good. Now follow me, sir. We need some space for our exercises.",
"Lead on.",
"Now, sir, draw your sword with the 'Draw/Sheathe Sword' key. First you should get familiar with the controls, so I won't be attacking you. Use the 'Action' key to attack and the 'Fire Pistol' key to fire your pistol.",
"Let me try.",
"Just a second. To quickly gain some distance between you and the enemy,  you can jump backwards by pressing the 'Dodge' key. Note that you can't talk to anyone with your weapon drawn. So before talking, sheathe your weapon by pressing the 'Draw/Sheathe Sword' key again.",
"I got it. Now let me try.",
"Well, are you sure that you understood everything so far?",
"Yeah, piece of cake!",
"No, I think I'll try it again.",
"I'm sick of this tutorial. Let me out of here.",
"Alright, that's enough, sir. Are you ready for some real action?",
"Sure, bring it on!",
"Not yet. Let me practice some more.",
"I'm sick of this tutorial. Let me out of here.",
"No problem, captain.",
"Thanks.",
"I'll fight back this time. Be careful, captain, and don't forget that you can block incoming blows with the 'Block' key - if you rush into combat without thinking, you'll soon be feeding the vultures.",
"I got it. Let's start.",
"Not bad, captain, not bad! Mind that if you've been wounded in a fight you can recover some health by using herbal potions. To do that you should press the 'Open Command Icon Menu' key and select the Use icon. Then press the 'Action' key, select Potion from the item list, and push the 'Action' key again.",
"I see. What's next?",
"I want to train some more. Let's fight again.",
"Enough of these lessons. You're dismissed.",
"Hm...Looks like you need some more practice...Mind that if you've been wounded in a fight you can recover some health using potions. To do that you should press the 'Open Command Icon Menu' key  and select the Use icon. Then press the 'Action' key and select Potion from the item list, and push the 'Action' key again. Now, let's try it again.",
"If you say so. Let's start again.",
"I'll improve my skills later. What's next?",
"Enough of these confounded lessons. Dismissed.",
"Always ready, cap'n!",
"Prepare yourself.",
"That's much better, sir. Now I can let you go onshore without any worries.",
"What's next?",
"I still think I need some more practice.",
"Enough of lessons. Dismissed.",
"Nah...I guess, it will take some more time to teach you proper fencing. Maybe you should spend a couple of days onboard taking training.",
"Can we try once more?",
"I'll get better later. What's next?",
"Enough of these lessons. You're dismissed.",
"Fine. Before we leave our ship let me tell you about your skills and abilities. Since a skilled captain always has a better chance of survival in this cruel world, you should wisely evolve your character\nFor fighting enemies and completing quests, your character gains experience points. When he obtains enough experience, your character gets a new rank and additional skill and ability points. By spending these points on different skills and abilities, you can improve various parameters of your character\nTo get all the information about your character press the 'Open Player Status Screen' key and then select Character View from the menu. There you'll see your character's rank, reputation, money, skills and Hit Points. Now you have some skill and ability points\nYou can distribute them right now or later.",
"How can I distribute Skill and Ability points?",
"Can I get a description of the different skills?",
"Forget about those skill points - let's continue with something else.",
"If you want to do it now - open the Character View screen, then select the desired skill and press 'Action' key to increase its value\nTo get an Ability you should select the Ability icon at the bottom of the screen and press 'Action' key. Then you'll see a list of all the abilities. Select the one you wish to learn and press the 'Action' key again to read the ability description. To learn an Ability press the 'Action' key a third time\nSome abilities cannot be learned until you have learned their prerequisite ones.",
"I'll do that now.",
"Forget about those points - let's continue with something else.",
"Can I get a description of the different skills?",
"Talk to me when you're finished and we will continue.",
"Alright.",
"Need some advice on how you should distribute your skill points? Put some in Melee Combat and some in Accuracy to start with\nBut there is no rush with that - you can always do it later if you want.",
"I'll do it now.",
"Forget about those points - let's continue with something else.",
"Can I get a description of the different skills?",
"Sure. Which one is of interest for you?",
"Leadership.",
"Melee Combat.",
"Sailing.",
"Accuracy.",
"Cannons.",
"Grappling.",
"Repair.",
"Defense.",
"Commerce.",
"Luck.",
"This skill allows you to control your people better. It you have a strong will your people will never surrender in a fight. And vice versa - seeing you so confident and strong your enemies will be terrorized and will surrender sooner. This skill also is required to captain a sailing ship.",
"Thanks. What about the others?",
"That's enough. Tell me about something else.",
"I think I'll distribute my points now.",
"The damage you inflict in a fight with your blade depends on this skill. Also it affects the chance of piercing enemy blocks and successfully blocking enemy attacks.",
"Thanks. What about the others?",
"That's enough. Tell me about something else.",
"I think I'll distribute my points now.",
"This skill shows how good you are at steering your vessel. If this skill is high, your ship will be faster and more agile than your enemy.",
"Thanks. What about the others?",
"That's enough. Tell me about something else.",
"I think I'll distribute my points now.",
"Good aiming can help you win a sea battle even against an overwhelming enemy. This skill represents how accurately your cannoneers can fire bombs and balls. Remember, firing manually from the deck always gives you better accuracy.",
"Thanks. What about the others?",
"That's enough. Tell me about something else.",
"I think I'll distribute my points now.",
"This skill is related to Accuracy and is also important for naval battles. The higher this skill, the shorter it takes to reload the cannons, and the faster they fire salvo.",
"Thanks. What about the others?",
"That's enough. Tell me about something else.",
"I think I'll distribute my points now.",
"This skill is the most important for any pirate. It shows how far you can throw boarding hooks to catch an enemy ship and swarm it with your troops.",
"Thanks. What about the others?",
"That's enough. Tell me about something else.",
"I think I'll distribute my points now.",
"This skill allows to repair your ship right in the open sea. The higher the skill, the higher the percentage of damage you can repair. Also, you'll need to have some planks and sailcloth onboard your ship to repair it.",
"Thanks. What about the others?",
"That's enough. Tell me about something else.",
"I think I'll distribute my points now.",
"The Commerce skill is essential for traders and merchants. With a high Commerce you get better prices in stores and sometimes you can even get a discount when hiring an officer.",
"Thanks. What about the others?",
"That's enough. Tell me about something else.",
"I think I'll distribute my points now.",
"What can I say - luck is luck! Whether you gamble or fight - luck is always welcome. High Luck is beneficial for all activities, especially if you're smuggling or playing dice!",
"Thanks. What about the others?",
"That's enough. Tell me about something else.",
"I think I'll distribute my points now.",
"Crew is the most fragile part of the ship and the most important. Without enough crew any ship becomes uncontrollable and awkward. Defense skill helps you protect your crew from enemy cannon fire. It also decreases losses of crew in sea battles.",
"Thanks. What about the others?",
"That's enough. Tell me about something else.",
"I think I'll distribute my points now.",
"Now I remind you about that business we planned for today.",
"Go on.",
"Firstly, we delivered a load of chocolate and leather to Oxbay - now we should sell it to the local trader. If needed I'll guide you to his store later\nAlso, our ship took some damage in that last storm - it need to be repaired. The local shipyard should easily handle the repairs. I can lead you there too if you want\nNext, we need to hire some new crewmembers to replace those who were washed away by the storm. Talk to the local tavern keeper about hiring more crew.",
"Is that all?",
"Almost. Your spyglass is old and scratched. Maybe you could use a new one? It should be available for sale somewhere in town.",
"Let's go.",
"If you want to buy a new spyglass you can do it right now. I see some traders under their tents.",
"Fine, let's do it.",
"I can do it later. Let's continue with something else.",
"You can go. I'll find my way around.",
"As you wish, captain. Follow me.",
"...",
"Talk to one of those men under the tents. They are selling different goods. You'll should be able to buy a new spyglass from them. Ask them for what they have on offer. You'll then see a list of items\nFirst you'll see the items that you have and then those that are available for purchase. Select the desired item and then press the 'Action' key. Using side arrows select the quantity you want to buy. Then press the 'Action' key twice to confirm your purchase.",
"Alright.",
"You've got it. Great. Now let's sell the goods we brought to the island.",
"Alright. Where we can do that?",
"I'll do it myself. Return to the ship.",
"Hey, where is that spyglass, cap? I don't see it!",
"I'll buy it now.",
"I decided not to buy it. Let's continue.",
"I'm getting bored. Go away!",
"As you say. Now let's sell the goods we brought to the island.",
"Alright. Where we can do that?",
"I'll do it myself. Return to the ship.",
"The local store should be inside the town walls. Follow me to the gates and when you see the Open Lock icon in top left corner of the screen, press the 'Action' key to go to the next location.",
"Alright.",
"I think I know where the store is. You have some goods onboard that you should sell to get money to pay for ship repairs and crew replenishment. To see what goods you have onboard you should press the 'Open Player Status Screen' key and then select Ship Cargo\nThen choose a ship from your squadron to view. You'll see a list of goods that your ship has onboard. You can scroll it right or left. You can also see the amount of ammo you have left on your ship.",
"Thanks for the info. Shall we go now?",
"I don't need your help anymore.",
"Follow me. I'll show you the right door and then you'll be on your own. But if you have any questions - just ask me.",
"Let's go.",
"Now you go talk to the merchant, captain. Sell your chocolate and leather but don't buy anything - we need money to fix up our ship and hire more crew. Do you need more details on trading?",
"Yeah, that would be useful.",
"Nah, I can handle it.",
"It's very simple, captain. Talk to the trader and tell him that you want to sell the goods you've brought. Then select a ship that will be used for trading. After that you'll see a list goods. Select a good you want to sell or buy and press the 'Action' key. Then select the Buy or Sell button and choose the desired quantity that you wish to buy or sell. Then press the 'Action' key again to confirm the transaction.",
"Thanks for the explanation.",
"I'll wait for you outside the store. By the way - if you haven't assigned your skill points yet you can put them in your Commerce skill to get more profit from your transactions.",
"Alright, thanks.",
"You should sell all the goods you have. But that's alright for now - next I'll show you how you can hire crew for your ship. This can be done in a tavern.",
"Fine.",
"I'll find it myself. You're free to go.",
"Now that we have money we can go and hire some crewmembers. For that, let's go to the tavern.",
"Alright.",
"I'll find it myself. You're free to go.",
"Follow me. I'll lead you to the tavern.",
"Well, what else can I do?",
"Aye, captain. Here you can hire crew. Also, sometimes you can find a good officer for your ship at a tavern - talk to people and maybe you'll get lucky\nTo recruit some crewmembers talk to the tavern keeper - he is standing at the bar - and ask him about crew replenishment\nSelect a ship to be beefed-up with crew, then select the Hire button. After that, select how many sailors you want - pay attention to crew morale, though. Then press the 'Action' key to pay your gold and hire these seamen.",
"Thanks.",
"Aye, captain. Here you can hire crew. Also, sometimes you can find a good officer for your ship at a tavern - talk to people and maybe you'll get lucky\nTo recruit some crewmembers talk to the tavern keeper - he is standing at the bar - and ask him about crew replenishment\nSelect a ship to be beefed-up with crew, then select the Hire button. After that, select how many sailors you want - pay attention to crew morale, though. Then press the 'Action' key to pay your gold and hire these seamen.",
"Thanks.",
"Sometimes it happens that there is no free crew on an island...That's unfortunate but you'll have to sail to another island to hire crew\nNow hire some crew. I'll wait for you outside.",
"I'll be there soon..",
"That's fine, sir. All what we have to do now is to repair our ship. While you were hiring crew I've found the local shipyard.",
"Good. Let's go there.",
"I know where it is. You can return to the ship.",
"Excuse me, captain, but you better hire as much crew as you can. Your ship should always be under your full control\nBut, since you can always do that later, we can go fix our boat for now. I've found the local shipyard.",
"Good. Let's go there.",
"I know where it is. You can return to the ship.",
"Aye-aye, sir! Follow me.",
"Go.",
"We are now at the shipyard. Here you can fix your ship, sell her, or buy another one. Also, at a shipyard you can install different cannons on your ship\nDo you want me to give you instructions on how to repair your ship?",
"Yes, tell me.",
"Nah, I can handle that.",
"Alright. Talk to the shipwright and ask him for repairs. Then choose a ship that needs to be repaired - you have only one right now. Then select 'Repair'. If you have enough money just press the 'Action' key after highlighting the 'Fix All' button, and your ship will be fully repaired\nIf not - then you'll have to select a percentage of hull and rigging to be repaired. Select Hull and then set the desired value. Then do the same with Sails. Then select 'Ok' and press the 'Action' key to confirm repairs.",
"Great, thanks.",
"Well, if so, I'll wait for you outside.",
"Alright.",
"I guess that's all, sir. I can give you some suggestions for what to do if you want, but now I must tell you something\nI'm old and tired of sailing, so I'd like to leave your ship and stay here. It was great to sail under your command, sir, but now I want retire. Sorry, if that causes troubles for you.",
"Hm...I can understand that.",
"But I'll be glad to help you with my advice anytime you'll be on Oxbay.",
"Can you give me some suggestions about what to do next?",
"Tell me about sailing my ship.",
"Thanks for your help, Malcolm. Good-bye!",
"Well, when I was at the store I noticed that they have pretty low prices for Sandal and Silk. If I were you, I'd go to a loan shark and get some money from him\nThen I'd buy all the Silk and Sandal here and sail to the island of Redmond - you can fetch a good price for both Sandal and Silk there\nYou'll get a hefty profit and then I'd suggest you repay your debt to the loan shark.",
"Sounds nice. Where can I find the loan shark's office?",
"Tell me about sailing my ship.",
"Thanks for your help, Malcolm. Good-bye!",
"His house is right in front of the local store. Go and ask him for a loan.",
"Tell me about sailing my ship.",
"Thanks for your help, Malcolm. Good-bye!",
"Alright. But before you go, I should remind you what business you were going to attend to while on land.",
"Go on.",
"Firstly, we delivered a load of chocolate and leather to Oxbay - now we should sell it to the local trader. If needed I'll guide you to his store later\nAlso, our ship took some damage in that last storm - it need to be repaired. The local shipyard should easily handle the repairs. I can lead you there too if you want\nNext, we need to hire some new crewmembers to replace those who were washed away by the storm. Talk to the local tavern keeper about hiring more crew.",
"Is that all?",
"Almost. Your spyglass is old and scratched. You should get yourself a new one. It should be available for sale somewhere in town.",
"Thanks. Farewell.",
"As you wish, sir. I can give you some suggestions for what to do if you want, but now I must tell you something\nI'm old and tired of sailing, so I'd like to leave your ship and stay here. It was great to sail under your command, sir, but now I want retire. Sorry, if that causes troubles for you.",
"Hm...I can understand that.",
"But I'll be glad to help you with my advice anytime you'll be in Oxbay.",
"Can you give me some suggestions on what to do next?",
"Tell me about sailing my ship.",
"Thanks for your help, Malcolm. Good-bye!",
"As you wish, sir. I can give you some suggestions for what to do if you want, but now I must tell you something\nI'm old and tired of sailing, so I'd like to leave your ship and stay here. It was great to sail under your command, sir, but now I want retire. Sorry, if that causes troubles for you.",
"Hm...I can understand that.",
"But I'll be glad to help you with my advice anytime you'll be in Oxbay.",
"Can you give me some suggestions on what to do next?",
"Tell me about sailing my ship.",
"Thanks for your help, Malcolm. Good-bye!",
"Well, steering a ship is not as hard as it may seem. Ships move with the wind. The harder the wind blows, the faster the ship goes. You can set your sails in two positions - Full and Battle, or strike them altogether\nIn battle position, the ship becomes more maneuverable but maximum speed is decreased. With Full sails, your ship moves faster but turns slower. Always keep your eye on the wind - your ship won't go very fast if you're sailing against it.",
"Tell me about firing cannons.",
"Tell me about boarding enemy ships.",
"Thanks for your help, Malcolm. Good-bye!",
"Firing in Third-person Mode is simple - just keep enemies within firing range of your cannons and press the 'A' button when your cannons are loaded. Your cannoneers will automatically aim the cannons at your enemy\nFiring manually from the deck is a bit tricky. You should aim your cannons at enemy ships, but not like you do with a pistol or a musket. Don't forget that cannons fire on ballistic trajectory and you must raise the aiming cursor higher if enemy is far from you\nOr lower it if the enemy is close. You can even do a direct fire, but only if your enemy is very close to you.",
"Tell me about boarding enemy ships.",
"Tell me about sailing my ship.",
"Thanks for your help, Malcolm. Good-bye!",
"To board an enemy ship you should get very close to her. Your and her relative speeds also should be near the same unless you have the special ability or high Grappling skill\nThen you need to open the Action Menu and select the Boarding command. Then you'll have to cut your way through the enemy ship's decks with your crew, slashing and killing opposing sailors\nAfter you win the boarding battle, you can plunder all the goods from that ship or take it with you if you have a proper officer to assign as a captain on the captured ship.",
"Tell me about firing cannons.",
"Tell me about sailing my ship.",
"Thanks for your help, Malcolm. Good-bye!",
"See you, captain. Visit me if you visit this town again.",
"Sure. Be happy on dry land.",
"Need my advice, captain?",
"Can you give me some suggestions on what to do next?",
"Tell me about sailing my ship.",
"Thanks for your help, Malcolm. Good-bye!",

};