string DLG_TEXT[43] = {
"Glad to see you, ",
". My name is ",
", and I'm at your service.",
"And I'm captain ",
".",
"Glad to see you again, ",
".",
"It's you! I was hoping I'd never see your face again.",
"Good day to you, too, ",
".",
"Sometimes life is unfair, ",
"Would you like to see my stock?",
"Yes, show me what you've got.",
"Later. For now, I need to talk to you.",
"Some other time.",
"Are you looking to deal some goods, or do you just want to buy some gear?",
"I need to sell some of the goods I've brought.",
"I'm looking to buy.",
"Neither, thanks. Goodbye!",
"All right. What do you want to talk about?",
"I'm listening.",
"I was asked to deliver some cargo to you.",
"Would you, perchance, be in need of a captain, sir? I have an excellent ship, and I can deliver any cargo, anywhere you like.",
"I've got no time for talk right now.",
"No, I don't need your services. At least, not as long as you're sinking French ships.",
"In that case, goodbye.",
"I'm sorry, but I don't have anything for you at the moment.",
"I'll come back later, then.",
"I'm sorry, but you don't have enough room on your ship for the job that I have in mind.",
"I'll come back later, then.",
"Oh! I was just going to ask you to do me a favor. Thing is, I need some cargo delivered to ",
", and as soon as possible. If you manage to do it in a month's time, you'll receive ",
" gold when you arrive. How does that sound?",
"I definitely like it.",
"I can't accept it.",
"I already told you today that I don't have anything for you.",
"Oh, sorry.",
"You're a bit late, don't you think? I've already received everything I needed. Goodbye.",
"Farewell.",
"Oh! I've been waiting for it for a long time. Here is your reward, young man.",
"Always welcome.",
"Sorry, I don't need your services at the moment.",
"That's too bad. Let me ask you something else, then.",

};