string DLG_TEXT[118] = {
"Captain, so long as your target still lives, we have nothing to talk about.",
"Fine, senor. Fine. I'll be back when I've finished the job.",
"You've done well, captain. And here's your 3000 gold, just as we agreed.",
"Thank you. Any other jobs for me?",
"Thanks - and goodbye. I'm finished with this racket.",
"Ah, captain! Well done - you've certainly earned your 4500 gold. I trust everything went smoothly enough?",
"Yes. It was almost pleasant work. One doesn't often run across such an offensive lout as that ",
"Geffrey Bampfylde",
"! How about another job?",
"It was easy. Too easy, in fact. Something tells me I should get out of this business while my luck still holds.",
"Captain, you never cease to amaze me! To be honest, I wasn't sure you could handle ",
"Pepin Bertillon",
". Please accept my apologies for doubting you. Along with your 7000 gold, as promised.",
"You're right to apologize. The only thing that man did well was talk. If money was always this easy, I'd already be a rich man.",
"Thanks - and goodbye. I'm finished with this racket.",
"Captain, you are the finest mercenary I've ever had the pleasure to work with! Here is your 10000 gold. But tell me, how on earth did you manage to beat ",
"Amerigo Vieira",
"? He eluded my best men for several years!",
"A lot of skill and a little luck are all I've ever needed.",
"Never mind how I did it. It's done. And I've had enough of this kind of work.",
"Captain, you've done me a great favor by ridding me of the Italian! Unfortunately, you've also learned too much. You'll have to take this knowledge to an early grave. I'm very sorry, captain.",
"So, ",
"Vito Leone",
" was right about your treachery! I should've taken him at his word. En garde, you faithless dog!",
"Captain, what are you doing here?!",
"Don ",
"Vito Leone",
" has told me a lot of interesting things about the way you do business. In particular, he told me that your partners have a tendency to die young...",
"Ah, Captain ",
"! I was wondering when you would grace us with your presence. You certainly weren't in a terrible hurry to finish the job, were you?",
"And you don't seem terribly frightened for a man with a hefty bounty for his head.",
"Hefty? Since when is 1500 gold a hefty price for my head? Look around you, captain! What do you see?",
"I was never very good at parlor games. What am I looking for, exactly?",
"Certainly you can't miss the three armed men who stand ready to cut you to ribbons if you make one wrong move. I'm certain my head is worth much more than 1500 gold -- how about yours?",
"I begin to see your point.",
"Oh, these are men, are they? I thought you were raising wild boars.",
"My point is simple enough. You can't hope to finish the mission that poor, foolish ",
"Ambroz Bricenos",
" sent you on.",
"When you put it that way, it's hard to argue. It seems I'm left with no choice but to apologize for the disturbance and leave you. I trust I won't have to fight my way out?",
"Is that right? It's arrogant cretins like you that I especially like to put in their place! Shall we dance?!",
"You won't have to, captain, I take no offense - you get used to this sort of thing in my line of work. In fact, if you're interested, I could propose a truly profitable job...",
"I'm listening.",
"Thanks for the offer, but this encounter hasn't much increased my interest in this sort of work.",
"The conditions are very simple. First: You have a month to finish the job - no more. If the job is done on time, the reward will be waiting for you as long as it takes you to come and collect.",
"...",
"Second: You never leave a witness. No exceptions will be tolerated.",
"...",
"And third: Upon receiving your reward, you get a new job right away. You may refuse it, but you can't take time to sleep on it.",
"...",
"Those are the conditions. If you violate just one of them - or refuse to take a job - we will no longer be working together. In fact, it would be unwise to speak with me again.",
"I can live with those conditions. What would my first job be?",
"I see. Thanks for the offer, but I'm not ready to be a full-time mercenary.",
"I'm sure you've already guessed. Get rid of ",
"Ambroz Bricenos",
" ",
"Ambroz Bricenos",
". That will prove your loyalty to me and earn you 3000 gold.",
"I like it when the money matches the risk. I'll do it.",
"Sorry, but I can't turn on a former employer, even if he sent me on a fool's errand.",
"Perfect. Don't forget, you've got exactly one month to do it.",
"I remember.",
"Then I won't delay you further, captain. And if you should decide to pay a visit to ",
"Ambroz Bricenos",
", well - don't bother. You probably won't find him alive.",
"Understood. Goodbye.",
"Too bad - it was a pleasure working with you. Farewell, captain.",
"Goodbye.",
"You shouldn't have said that, captain. I can't tolerate rudeness. Prepare to die!",
"I'm not ready to do that - but it seems you are!",
"Of course. The target is a merchant by the name of ",
"Geffrey Bampfylde",
"Geffrey Bampfylde",
". His house is in Greenford, across the street and to the left of the tavern. The reward is 4500 gold.",
"Prepare the gold. This job won't take long.",
"Sounds like more trouble than it's worth. I'm out of the game.",
"Beginning to like it, eh, captain? Be sure you don't come to like it too much; that's the surest path to failure. Now, listen carefully - this job is not an easy one.",
"I like a challenge. Tell me about it.",
"Sounds like more trouble than it's worth. I'm out of the game.",
"The target is a smuggler named ",
"Pepin Bertillon",
"Pepin Bertillon",
". He has been quite hard to track down - we've only managed to learn that his ship often visits Quebradas Costillas.",
"A pirate island, eh? Convenient - no soldiers to deal with....",
"Sounds like more trouble than it's worth. I'm out of the game.",
"No soldiers, true. But there are cutthroats, and lots of them. They're stupid, but armed and dangerous. So ",
"Pepin Bertillon",
" is not likely to show up there without bodyguards. Considering the danger, the reward for this job is 7000 gold.",
"For that kind of money, you can consider it done.",
"Sounds like more trouble than it's worth. I'm out of the game.",
"Considering your abilities, I'm sure you will. But the next job is going to be quite difficult.",
"I can handle it.",
"In that case, I'll pass.",
"I hope you can, because this time the target is my most personal enemy. His name is ",
"Amerigo Vieira",
"Amerigo Vieira",
". He lives on Conceicao, in a house to the right of the governor's residence, upstairs.",
"And how much is this dangerous job worth to you?",
"Sounds like more trouble than it's worth. I'm out of the game.",
"10000 gold. But remember: He's probably the best fencer in the entire archipelago. I'm counting on you, captain. ",
"Amerigo Vieira",
" has betrayed me, and I can't rest easy while he's alive.",
"He's already dead - he just doesn't know it yet.",
"Sounds like more trouble than it's worth. I'm out of the game.",
"Your skill is unmatched, and I have a job that only you can accomplish.",
"I'm listening.",
"I've had enough of your jobs. I'm out of this racket.",
"Not long ago, a messenger from the mainland arrived in the archipelago. He must die, and as soon as possible. The news he brings is too dangerous.",
"The messenger it is, then. The reward?",
"I've had enough of your jobs. I'm out of this racket.",
"Truly a royal sum - 20000 gold. This job is very important to me.",
"It's a deal. How do I find him?",
"Sounds too dangerous. I'm out of this racket.",
"That could be a problem. We don't know his exact location, or even his name. We know only that he's an old Italian, and that he's somewhere on Conceicao. So you'll have to go there and find him yourself.",
"That's not much to go on. But I'll find him.",
"Sounds like more trouble than it's worth. I'm out of the game.",
"I should've known you'd have a little chat with the old fox instead of just killing him! I should have done the job myself. Well, he'll get what's coming to him soon enough. And you'll get yours right now!",
"You're delusional, but I'll be happy to set you straight. En garde!",

};