string DLG_TEXT[22] = {
"Tell me, ",
"? Isn't that the 'Cleopatra' awash out there?",
"No, sir. That's the '",
"', my ship.",
"Have you ever seen the 'Cleopatra' during your sails?",
"No, I'm afraid I've never seen a ship with that name.",
"That's too bad. If you do ever see it, please tell its captain - my son - that I'm waiting for him.",
"If I get the chance, I certainly will. Farewell, captain.",
"Excuse me, ",
". Have you seen the 'Cleopatra' in your travels?",
"No, sir. I haven't run across her. But I do have a letter for you from your son.",
"I've not only met your son, sir - I've brought him here with me.",
"Your son? That blockhead who can't even take care of himself? I brought him with me. He'll be along in a minute, if he doesn't get lost.",
"No, I haven't met your son, sir.",
"You've asked me that many times, old man - and the answer is still no.",
"A letter?! From Marc? You wouldn't lie to an old sailor, would you?",
"I might. But not this time. Here's the letter. I hope you'll see your son very soon.",
"Marc? Can it be?! The heavens have heard my prayers and brought you back to me!",
"All right. I'm won't disturb you further. Farewell!",
"Your parents can be proud of you for what you've done, ",
".",
"Thank you, sir. But now I must go - I've got a lot to do.",

};