string DLG_TEXT[135] = {
"Hello, ",
". I've heard you talking to that crazy old man. ",
"Milon Blacque",
".",
"That's none of your business, and I don't have time to explain it in any case.",
"What's makes you call him crazy? He seems sane enough to me.",
"Could you tell me, ",
", whose washtub is rolling there by the shore?",
"That's that one named '",
",' correct?",
"Yes, that's right.",
"Have some respect when you talk about my ship!",
"Oh, sorry. I didn't realize that was your washtub!",
"Watch your mouth!",
"Sorry, ",
". I'm just ribbing you a bit. My name is ",
". I work in the port.",
"My name's ",
", and I'm captain of the '",
".'",
"Yes, I figured that out, ",
".",
"Well, since you're such a clever fellow, maybe you can answer a couple of my questions.",
"With pleasure - I'm short on cash at the moment.",
"What? I'm not going to pay you to stand here and talk to me.",
"You want money, do you? All right, here's a gold coin for your time.",
"I'm sorry, ",
". I've just remembered that I have urgent business elsewhere.",
"Farewell.",
"Wait! Here's a gold coin.",
"What do you want to know, ",
"?",
"First, tell me the latest local news, and we'll go from there...",
"A big consignment of forbidden goods recently appeared in port\nThe port's inspector ",
"Turpin Cabanel",
"Turpin Cabanel",
" ran his legs off trying to find the ones who smuggled it into the city.",
"Nothing so unusual about that. I'm starting to wonder if your conversation is worth the money I paid.",
"Really? Where can I find him?",
"Don't rush off just yet - I've got a couple more fresh rumors for you.",
"Let's hear them. I hope they're more interesting then the first one.",
"No, thanks, ",
". I think I've heard enough.",
"Well, some pirates came to the city recently. They've been drinking and carousing all over town...",
"Pirates drinking?! That's even less interesting than your shocking tale of smuggling.",
"Pirates, you say? Where can I find them?",
"I'm sure most of them are still in the tavern, although I'm told they plan to leave the city soon.",
"Thanks. I've got to be going - time is money.",
"All right. Do you have anything else for me?",
"In that house by the dock.",
"Thanks for the information.",
"Can you tell me anything else of interest?",
"Well, there is one thing, ",
". It seems that ",
"Milon Blacque",
" has been coming to the dock every day to meet his son....",
"What's so unusual about that?",
"Everyone knows that the son and his ship disappeared many years ago.",
"So an old man has gone mad with grief? I don't see what that has to do with me.",
"Why is he still here and not in some asylum?",
"An asylum, here? You must be joking, captain. Still, he is cared for.",
"Cared for?",
"Yes. He has an adopted daughter, ",
"Rachel Blacque",
", who looks after him\nShe's a living doll, but as cold as the North Sea. Still, I'll win her someday.",
"Spare me your mooning over some local girl. It doesn't interest me.",
"I can tell you're well-informed about everything that happens around here. Do you mind answering a couple of my questions?",
"Hello, ",
". I've heard you talking to that crazy old man. ",
"Milon Blacque",
".",
"That's none of your business, and I don't have time to explain it in any case.",
"What's makes you call him crazy? He seems sane enough to me.",
"Fair winds to you, ",
".",
"Oh, it's you! Has anything new happened?",
"I've been told that you won't leave ",
"Rachel Blacque",
" and her father alone.",
"Hello, ",
". Haven't seen you for ages.",
"Do you remember telling me something about smugglers?",
"You told me something about smugglers recently - do you recall the details?",
"Let's talk later. More urgent business calls me.",
"Of course I do, ",
". Everyone in town's talking about it.",
"I see. Could you tell me something more?",
"Tell me more, then. I can tell by looking at you that you're somehow involved in that business.",
"What are you talking about? I just work here in the port.",
"You're telling me you don't know what's going on in the city? In the port where you work every day?",
"That's why I'm sure you know more than you're telling.",
"How would I know?!",
"I know what port workers are like. They love nothing more than to gossip about whose ship was just unloaded, what kinds of goods they carried, and what people they saw!",
"Don't play games. Even if you didn't personally help unload that contraband, you certainly know who did.",
"Fine. I'm probably mistaken. Sorry.",
"Sorry. I'm probably wrong about you. I haven't been myself lately.",
"All right, I see there's no reasoning with you. Goodbye.",
"I see where this is headed. How much will it cost to revive your memory?",
"Well, of course it's up to you. You don't have to talk to me. You could always talk to my sword instead.",
"I think 500 gold is a fair amount, ",
".",
"You've got a deal. Take the money and talk. ",
"Don't be ridiculous. I don't have that kind of money.",
"Then I can't help you, ",
".",
"I urge you to reconsider. Or you'll wish you had.",
"It's ",
"Raoul Calmes",
"Raoul Calmes",
" who's behind all this. That's all I know. Now let me get back to work.",
"Thanks for your help.",
"Don't make me laugh! If you try something here, the soldiers will have you.",
"By the time the soldiers get here, I'll have drawn and fired. And you won't be around to see them get me. Still, it's up to you.",
"You wouldn't do that - it'd be madness!",
"Go ahead and test me.",
"Devil! All right, fine - I'll tell you everything.",
"That's a clever boy. I'm listening.",
"Well, I'm out of here.",
"What are you talking about, ",
"? I'm a respectable man!",
"Never mind your games. It's very simple: Leave them alone, or I'll make you wish you had.",
"Don't bother lying to me. I can see the truth in your face.",
"Blast that girl! When I'm finished with her, she won't be able to complain to anyone else!",
"Are you deaf? If you touch her again...if you so much as look at her sideways...I'll have your guts for garters.",
"I'm not lying to you, ",
"!",
"Of course you are. I deal with better liars than you every day. Just understand this: If you touch her again, I'll see that you regret it for the rest of your short life. Do you understand?",
"Relax. I just want to know how long you're going to put up with her nonsense.",
"What do you mean?",
"I mean it's time you put that ",
"Rachel Blacque",
" in her place. Be a man!",
"Of course, ",
". I'll, uh...I'll just do that. Sure.",
"That's right, time to show that wench what she's really worth.",

};