string DLG_TEXT[172] = {
"I welcome you, ",
". My name is ",
". What's your name?",
"Hello, ",
"! I am ",
". May I know your name?",
"Yes, ",
". What do you want? By the way, my name is ",
". And yours?",
"I am ",
", a captain and the owner of the ship '",
"'.",
"My name is ",
".",
"You can call me captain ",
".",
"Hello. An officer left my ship. His name is",
"Nigel Blythe",
"Nigel Blythe",
". Your town is small enough that perhaps you've heard something about him.",
", a captain of '",
"'.",
"Oh, it's captain ",
" himself! What do you want to find out this time?",
"Hello, ",
". Do you want anything?",
"What kind of cock-and-bull stories have you heard here in the tavern lately?",
"What's new in this corner of the world?",
"What's going on hereabouts?",
"Could you, please, tell me how to get to one place?",
"I can't find the way to one place...",
"Could you tell me the way...?",
"I'd like to know what people say about one person in particular.",
"Can you tell me what people are saying about someone in particular?",
"I'd like to get some information about the locals.",
"Tell me about your colony.",
"What do you know about Oxbay?",
"I'd like to get some information about Oxbay.",
"Hello. An officer left my ship. His name is",
"Nigel Blythe",
"Nigel Blythe",
". Your town is small enough that perhaps you've heard something about him.",
"Well, there's nothing I need at the moment. Farewell!",
"Yes, I think I've heard that your friend was in our tavern",
"Thank you.",
"I am glad to meet you, captain ",
".",
"It's nice to meet you, ",
".",
"Nice to meet you, captain ",
". I don't suppose you're just curious about my name...",
"I am glad to meet you, captain ",
".",
"It's nice to meet you, ",
".",
"Nice to meet you, captain ",
". I don't suppose you're just curious about my name...",
"What kind of old sea dog's stories have you heard in the local tavern lately?",
"What's new here in this corner of the world?",
"How is it going hereabouts?",
"Could you tell me the way to one particular place?",
"I can't find the way to one place...",
"Could you tell me the way...?",
"Do you know what people are saying about this particular person?",
"Could you tell me anything about one man?",
"I'd like to get some information about the locals.",
"Tell me about your colony.",
"What do you know about Oxbay?",
"I'd like to get some information about Oxbay.",
"I am just enjoying the sights of the city. See you.",
"I see.... There is one more thing.",
"Thanks for the information. Farewell.",
"It's always nice to have such pleasant company, ",
". Tell me.",
"Yes, ",
"?",
"You like to chat, captain, don't you? Well, so do I...",
"It's always nice to have such pleasant company, ",
". I am listening to you.",
"Yes, ",
"?",
"You like to chat, captain, don't you? Well, so do I...",
"What kind of old sea dog's stories have you heard in the local tavern lately?",
"What's new here in this corner of the world?",
"How is it going hereabouts?",
"Could you tell me the way to one particular place?",
"I can't find the way to one place...",
"Could you tell me the way...?",
"Do you know what people say about this particular person?",
"I'd like to know what people are saying about one person.",
"I'd like to get some information about the locals.",
"Tell me about your colony.",
"What do you know about Oxbay?",
"I'd like to get some information about Oxbay.",
"Never mind...I've changed my mind. Good-bye.",
"Who has attracted your interest, ",
"?",
"Who do you mean, captain?",
"There are lots of people in Oxbay. Who exactly do you want to know about?",
"I want to know about the Governor of the colony.",
"I am interested in the tavern-keeper ",
"Everard Gordon",
"Everard Gordon",
".",
"Tell me about the owner of the shipyard, ",
"Oweyn McDorey",
"Oweyn McDorey",
".",
"I want to know about the trader named ",
"Alan Milds",
"Alan Milds",
".",
"I changed my mind. Forget about it.",
"Oxbay doesn't have its own governor - the island is under Redmond's governor's jurisdiction.",
"I see. I have a question.",
"Thank you, goodbye.",
"They say you can count on him. On the other hand, I've heard that he doesn't like to take unnecessary risks and always does his business prudently. I don't think he's into any shady business either.",
"I see. I have a question.",
"Thank you, goodbye.",
"A great lad. Always ready to help. I must say that for a backwater like this, he's quite a fine shipbuilder.",
"I see. I have a question.",
"Thank you, goodbye.",
"He's not very successful. He trades and trades, but always seems to end up poorer. Items are often out of stock. And he's always deep in debt.",
"I see. I have a question.",
"Thank you, goodbye.",
"Where do you want to get to, ",
"?",
" I have this city at my finger-tips, captain, so tell me where you want to get to.",
"You can count on me, ",
".",
"How can I get to the tavern?",
"Where is the shipyard?",
"Where can I sell the fine goods that I have brought with me?",
"Our tavern is at the city's square. It's a two-story wooden building with a stone foundation.\nI hope you can read English? There is a sign there.",
"I see. Thank you. Good-bye.",
"And where is the shipyard?",
"Where can I sell the fine goods that I brought with me?",
"If you go from the port, then when you enter the city, you should turn to the left, and you'll see a small stone building. That is the shipyard manager's office.",
"I see. And how can I get to the tavern?",
"Where can I sell the goods that I brought with me?",
"Thanks for your help. That is all I need to know.",
"Oh, that's easy, ",
"! If you turn your back to the sea-gates, the shop is to the right.",
"Where is the shipyard in this city?",
"How can I get to the tavern?",
"I see. That's all I need to know.",
"To be honest, I don't know much about it, but I can tell you what I do know.",
"What do you want to know about our colony?",
"With pleasure. What exactly do you want to know about?",
"I'd like to know the history of the colony...",
"Is there is anything else besides the city on this island?",
"Do you know anything about the fort that protects the city?",
"Let's talk about something else.",
"Our colony was built about 40 years ago. The island is pretty small, but it has very fertile soil, and there are a couple of convenient bays.\nNew sections are being developed, and trade has increased. Our city was the first settlement, and then came Greenford.",
"Continue...",
"That's clear. Let's talk about something else ",
"Then buccaneers became frequent visitors here, so they built the fort to protect the city.",
"I see. Let's end our conversation on that subject, and change the subject.",
"Most of the island is already developed. It's difficult to develop further because it's hard labor to clear the dense jungle, and we don't have enough people here to do that...",
"All right, tell me something else.",
"There is nothing special on our island. All islands are more or less the same in this archipelago.",
"I see. Continue...",
"We've got jungle, rocks, and deserted beaches...and I guess that's about it. Well, there is also Greenford, of course.",
"I see. Continue...",
"I see. Let's end our conversation on that subject, and change the subject.",
"I don't know anything.",
"That's too bad. Tell me more about the colony.",
"There is nothing special about the fort. It has thick walls, long-range cannons, and there are 1000 soldiers in the garrison.",
"I see. Continue...",
"Why do you want to know, captain? It's not very smart for me to chatter about the fort with every stranger. How do I know what you have on your mind?",
"Well, if the fort is such a sensitive subject for you, then let's not talk about it. Tell me about the colony.",
"I see. Let's end our conversation on that, and change the subject.",

};