string DLG_TEXT[118] = {
"Hello, my son. What brings you to the bosom of the Church? Did you come for confession, or perhaps to make a donation?",
"I have to speak with you, father.",
"I'd like to make a donation, holy father.",
"Just having a look around. I have to go.",
"I'm listening, my son.",
"I need access to the church library, father.",
"I have those papers that were stolen from you.",
"The papers you sent me to find now rest at the bottom of the sea - along with the one who stole them.",
"I was asked to deliver this letter to you.",
"I was asked to deliver this letter to you.",
"I'm afraid I wasn't able to fulfill your mission. By the time I reached the island, the 'Montanez' was already in combat with two pirate ships, and they sank her.",
"I've carried out your assignment. The ship you asked me to escort is docked at the port.",
"I don't have any business with you right now.",
"You've done well, my son! Did your voyage go smoothly?",
"Not entirely. When I finally met the barque, it had been attacked by two pirate ships bent on sinking it at any cost.",
"I see. Anything else?",
"Yes, there was one other thing. The ship's captain set down some passenger at Oxbay...",
"Yes, I know about that. In fact, that was the point of the whole venture. The arrival of this man in the archipelago is very important to the Church. I believe you'll meet him someday.",
"I see.",
"Now, then, allow me to give you your reward - and to propose a new mission.",
"Thank you, father. And what is this new mission?",
"My Lord - this is grave news indeed. Someone obviously knows of our plans and is actively opposing them.",
"I'm very sorry, father.",
"None of that, my son. You did all you could, and I think it would be unfair not to pay you for your attempt to help the Holy Church.",
"Thank you.",
"Now, would you agree to carry out another mission for me?",
"What will it be this time?",
"Nothing extraordinary. Just take this letter to Father Bernard on Redmond. And make certain no one sees it but him!",
"Agreed. I'll go now, if I may.",
"Yes, and may God be with you, my son.",
"Amen to that, father.",
"Let me see. Yes...yes, it's just as I thought! You've done well, but let me ask you a couple of questions.",
"Of course. What do you want to know?",
"Let me see. Yes...yes, it's just as I thought! But who opened the letter?",
"No one opened it, father! You think I would do such a thing?",
"You noticed that, did you? I knew this wouldn't end well.",
"So who opened it?",
"They were waiting for me at the bay when I landed. I had no choice but to let them see the letter. Men in red robes...it was as if they knew I was going to land there!",
"I see. This is easily forgiven, my son - especially since we foresaw this and wrote the letter in code\nYou've actually helped us to mislead our enemy. I'm pleased to pay you the sum I promised.",
"Thank you.",
"It's clear you feel no remorse for what you've done. That's your choice, of course. But I'll ask you to leave this church!",
"As you wish.",
"No, wait! I'm sorry, father. It was wrong of me.",
"Have you had any troubles on your journey?",
"Well, ",
"Father Bernard",
", asked me to land at a secluded bay to escape trouble - but they were waiting for me there...",
"Speak plainly in God's house, my son. You're suggesting that...",
"I'm suggesting nothing. I don't want to accuse anyone. I just thought you should be aware of this. At the bay, three men in red robes were waiting for me, and they were very interested in the letter. So interested, in fact, that I was forced to kill them.",
"I see that ",
"Father Bernard",
" was not unwise to give you this mission.",
"There's more, father. When I searched the bodies of my attackers, I found a strange medallion on the neck of each one.",
"May I see these medallions? Yes...interesting.... But let's get back to business. Here is your reward.",
"Thank you.",
"I have another mission for you, if you're interested\nAnd the reward will be much more generous this time.",
"What do you want me to do?",
"A ship will be arriving from Europe soon, carrying some people who are vital to our cause. I have every reason to believe that ship will be attacked, so your task is to meet it near Oxbay and escort it to our port.",
"Tell me the ship's name, and I'll do all I can.",
"It's a barque called 'Montanez,' under the command of ",
"Mergildo Hurtado",
", a Spanish officer.",
"All right. That should be all the information I need. I'll set sail as soon as possible - the quicker I'm on my way, the better my chance for success.",
"I'm sorry to hear that. Those papers were very important to the church.",
"You should be glad your enemies won't be able to use them against you, father.",
"That's true. But it's still a shame to lose them.",
"I'm sorry. Does this mean I can't have access to the library?",
"Perhaps it should - but you strike me as a man who would find a way regardless.",
"So, I can go in?",
"Yes, you may. You've got the whole day for reading. It's strange, though - you're the second person who's wanted to get in there so badly.",
"Thank you, father.",
"Perfect! Please, give them to me right now.",
"Here they are.",
"Not so fast, padre!",
"What do you mean, my son?",
"I've found out what kind of papers these are - so naturally their price has gone up.",
"You're blackmailing me?!",
"Did you think your priestly robes made you immune to a little honest extortion? If you don't want these papers to fall into the wrong hands, you'll give me access to the library and 5000 cash.",
"Have you no fear of God? Where can I find such money?",
"Well, let's just check these notes, shall we? Yes, here it is: '...17000 gold were given to equip the ship and hire sailors....' What I'm asking for is just a fraction of that amount.",
"Enough! We may be heard. Here is your money. Now give me those papers!",
"They're all yours. Now how about the library?",
"You've done a fine job for the good of Church, my son. You will be rewarded.",
"What about the library? May I go in there?",
"Oh, yes. I'd forgotten about that. Of course you may go in. It's strange, though - you're the second person who's wanted to get in there so badly.",
"Thank you, father.",
"I'm afraid that's not possible. The library is closed to laymen.",
"Maybe you can make an exception for me. Look - I have my own ship and crew. Perhaps if you help me with my problem, I can help with some of yours.",
"You're a captain? Then perhaps you really can aid me and the Spanish Church.",
"Great! What do you want me to do?",
"Some very important papers were stolen several days ago from the church. I suspect they were taken by ",
"Ferro Cerezo",
"Ferro Cerezo",
". Unfortunately, I don't have any hard evidence against him.",
"So, you want me to find out if he has the papers - and bring them back to you if he does?",
"Yes. They're very important documents. Leave no stone unturned in your search for them.",
"Where can I find this man?",
"I managed to find out that he has his own ship. It's a sloop, if I am not mistaken. And he is often seen at Conceicao - he's probably involved in smuggling.",
"I'll find him. Will you allow me access to the library if I bring the papers back?",
"Certainly. You'll be able to spend one full day in there, although I don't understand why a sailor would be interested in that.",
"Bless me then, father, and I'll be on my way.",
"Of course, my son.  How much do you want to give?",
"I am sorry, father, but I can't make a donation just now.",
"I'm afraid 100 gold is all I can afford just now.",
"I should think the Lord would look kindly on 1000 gold.",
"I'm doing well these days, so I'll give 5000 gold piasters.",
"It's your decision, my son. It's never too late to change - and keep in mind that all will be taken into account at the time of your death.",
"My death is still a long way off, God willing! Let's talk about something else.",
"Sorry, father. I've got to go.",
"I thank you for your gift in the name of the Holy Church, my son.",
"I need to talk to you, father.",
"I'm sorry, father, but I've got to go.",
"I thank you for your gift in the name of the Holy Church, my son.",
"I need to talk to you, father.",
"I'm sorry, father, but I've got to go.",
"I thank you for your gift in the name of the Holy Church, my son.",
"I need to talk to you, father.",
"I'm sorry, father, but I've got to go.",

};