string DLG_TEXT[31] = {
"Good to meet you, ",
". My name is ",
", and I am at your service.",
"Thanks. I'm Captain ",
".",
"Glad to see you again, ",
".",
"You! I'd hoped you'd never darken my door again.",
"Good day, ",
".",
"Sorry about that, ",
"Do you want to see my goods?",
"Sure. Show me what you have in stock.",
"Not right now. Let's talk.",
"No, thanks. Maybe next time.",
"Are you looking to buy or sell?",
"I've got some goods I want to sell.",
"I'd like to buy some gear.",
"Neither, thanks. So long.",
"I'm all ears. What's on your mind?",
"I'm looking for work for my ship and crew.",
"I'm interested in a worker of yours, Clauss. I'd like to pay off his debt.",
"Pay for him? Sure, you can do that. He has worked off a part of his debt...",
"Enough. Just tell me how much money do I have to give you.",
"Let me check my papers...aha...yes.... Yes, here it is. Clauss owes me 2632 gold.",
"Hmm, the lad spent up a lot. Here's your money. Now tell me, where can I find Clauss?",
"I think I'll delay the payment a bit.",
"I've sent him to the tavern to get a keg of ale. You'll find him there.",
"Thanks.",
"I'm afraid I don't need your services just now.",
"That's too bad. Let's talk about something else.",

};