string DLG_TEXT[25] = {
"Don't just stand there! Come in, come in!",
"...",
"Where are you going, you young whelp of a sailor? Bring her about and sail yourself of here. This is no place for the likes of you!",
"I need to talk to ",
"Alistair Garcilaso",
"Alistair Garcilaso",
".",
"Hold on! Aren't you ",
", the one who makes tradesmen tremble at the sound of your name?",
"I suppose that could be me. What's it to you?",
"Wait! I'm just wondering if some member of your brotherhood is making up a crew, by any chance.",
"At the moment only old ",
"Anacleto Rui Sa Pinto",
" is looking for people. But nobody wants to join his crew. He's an unlucky fellow, to say the least. You can try, but never say you weren't warned.",
"And where can I find this ",
"Anacleto Rui Sa Pinto",
"?",
"At the tavern, of course. Where else?",
"Thanks. I'll go look for him.",
"Very sorry! I won't say another word. Make yourself at home.",
"I intend to.",
"I doubt he wants to talk to you. Get out!",
"Maybe I'll go see for myself if he wants to talk to me.",
"And maybe I'll stop you!",
"We'll see, won't we?",

};