string DLG_TEXT[36] = {
"Are you the one askin' for ",
"Camilo Machado",
"?",
"Yes. I would like to talk to him.",
"Is that so? You should know ",
"Camilo Machado",
" ain't an easy one to talk to.",
"Thanks for the tip, but unless you make his appointments, I'll be on my way.",
"Let's say I'm an associate of ",
"Camilo Machado",
" and if you want an audience with him, you'll have to talk to me.",
"Well, my conversation with him is not for your ears. Bring me to your boss or move aside. I can find him myself without your help.",
"In that case, I have an idea - take me to your boss or I'll run you through.",
"I can take you to him, but you need to surrender your sword and your gun.",
"You think you're tough? A snap of my fingers and there will be nothing of you left!",
"I go with my weapons, or I don't go at all, and I'll find ",
"Camilo Machado",
" without your help.",
"After I shoot you in the liver, you will live maybe a few hours and die in excruciating pain.",
"Do you want to speak with ",
"Camilo Machado",
" or not? Give me your weapons, or we trade blows!",
"If you shoot me, you'll die yourself.... So I think you're bluffing.",
"I've said all I will say. Take me to ",
"Camilo Machado",
", or let me find him myself.",
"Then take me to ",
"Camilo Machado",
", or you'll have my steel to deal with.",
"Let's go, but I warn you that ",
"Camilo Machado",
" won't like this one bit.",
"Calm down, I'll take you to ",
"Camilo Machado",
", and then it's your problem.",
"Now we are talking. Lead me.",

};