string DLG_TEXT[49] = {
"I heard that you want to see me. So, what business do you have for me?",
"I'd like offer my services.",
"Are you a captain? What's your name?",
"My name is ",
", captain of the '",
"'.",
"Good, I'll remember your name. Now, tell me what made you come to me.",
"I'd like to talk business with you.",
"Nothing. I'll take my leave, if you'll allow me.",
"You can leave.  But don't disappear completely, it's possible I'll have plans for you.",
"As you say, mijnheer.",
"I am all ears. What made you come to me?",
"Business mijnheer.",
"I'm leaving.",
"Then let's talk business.",
"I am here on behalf of those women standing by your entrance.",
"Your mission is a success. The missing children have been returned to their parents",
"I want to talk about a man who finds favor from your grace.",
"Your mission is accomplished, mijnheer.",
"I don't have anything to discuss with you at the moment, mijnheer",
"Yes, I already know that, here is your reward. I hope that in future I will be able to use your services.",
"Any time, mijnheer",
"So, who do you want to discuss.",
"A buccaneer, ",
"Bernardo Gamboa",
", mijnheer.",
"Ah. That man?! And what do you want me to say? As far as I know, his reputation is stainless...",
"You would be wrong. From what I know he kidnapped a girl from your town.",
"Ah, ah, ah. Are you sure about that? I don't want to insult him unjustly.",
"If you don't mind, I will investigate this privately. No one will know of your involvement. If he didn't kidnap this girl, your relationship with him will remain intact, if he did, then you would show to everybody how just and powerful you are.",
"Hmmm... That is not unreasonable. Indeed, I don't risk anything in this case. You may find out what's going on. If your mission ends successfully, I'll reward you. But, since this is your initiative, it will be a modest sum.",
"Thank you mijnheer.",
"Remind me, what were we discussing?",
"We were talking about a kidnapped girl.",
"Ah, yes, I recall. As I understand, she really was kidnapped.",
"Yes. The scoundrel didn't want to give the girl back and was slaughtered by his own men.",
"Well, no pirate - no problem. Here is your reward. You can leave my room now...",
"As you please.",
"Ah, that's what you wanted to discuss...",
"I don't understand why you don't take this more seriously. Isn't it your responsibility to provide for safety of the colony's citizens?",
"Captain, I'll forgive your criticism of me this once. Don't do it again if you want find favor in this office\nAs to those women...I can tell that you are a smart man, so, I will tell you something.",
"I am all ears.",
"Two soldiers were found dead today. One of them had a piece of a black fabric in his hand\nSeveral hours before they were discovered a frigate was spotted sailing away from the island under full sail.",
"And this halts your investigation?",
"Well... It's obvious the kidnapped children were taken away from the island. Under the circumstances the search isn't worth the money that will be spend on such an expedition\nMoreover, they could be anywhere.  You should understand that Captain. The sea offers many places to hide\nAnyway, if you are so touched by the grief of those women, I offer you a challenge to find their children\nI promise that if the search will be successful, I'll show my gratitude to you.",
"All right, I agree, but first I'd like to know where I can find a witness who saw the frigate.",
"No, I don't want to spend my time on such nonsense.",
"You accept? Perfect! You can find the witness in the tavern. It was a merchant captain who sighted that ship.",
"Thank you, may I take leave of you now?",

};