string DLG_TEXT[306] = {
"Introduce yourself, if you please. I don't believe I'm acquainted with you.",
"My name is ",
", and I'm captain of the ",
".",
"Captain ",
". I trust you are in good health. So, to what do I owe the honor of your visit?",
"Hello, ",
", hello.  What is the purpose of your visit?",
"I'm listening, Captain ",
". What's this regarding?",
"I have business to discuss.",
"I was hoping you had work for an able captain.",
"Just stopping by, sir. Goodbye",
"Well, Captain ",
", I can see by your face you have something to tell me.",
"I'm sorry to report the settlement on Oxbay has been attacked.",
"Have you returned with the prisoner? Where is he? I want to see him.",
"I am sorry, sir, I bring you ill news. The prisoner escaped before I arrived at Oxbay.",
"Hmm...you have my attention, captain.",
"Let's talk about it later, sir.",
"I've just returned from Oxbay, sir.",
"Your task has been carried out.",
"Alas, I have nothing for you at the moment. Though feel free to inquire later.",
"I have business to discuss.",
"It's only a visit of courtesy. And now goodbye.",
"All right, Captain ",
", but before seeking an audience with me, you should consider your choice of topics more wisely.",
"Do you have work for an able captain?",
"Just stopping by, sir. Goodbye",
"Hahahaha, don't be so modest, captain. Maybe you want to say that they started it first!",
"Well, as a matter of fact, that is the case, sir.",
"Anyway, I am happy to hand you this reward for battling with the pirates.",
"Thank you, sir. We should discuss something.",
"Thank you. And may I inquire, do you have work for an able captain?",
"I am thankful, Sir ",
", for this reward. Unfortunately, I must be on my way. Goodbye.",
"Hmm, this news is unsettling.... But how can there be pirates in these waters? \nThe squadron commanded by Captain Tomlison assured me they had caught or sunk all these scoundrels!",
"That's just it, sir. These were not pirates. These were French ships, and French troops.",
"What?! I knew it. His honor, Carl, should have given a warning shot a long time ago\nPlease, tell me everything. How did you manage to slip away? How many ships, how many guns and troops? Where did they come from? \nAre you sure that these were ships of the French fleet?",
"Absolutely, sir. French flags were the first thing I noticed.",
"This is terrible, terrible! French soldiers holding English soil, and almost no gold in the colony's treasury to wage open war. How we are going to protect our homes? \nI am afraid, ",
", that this will affect you and your ship.",
"Me? How?",
"We were talking about the French squadron.",
"Hmm. I don't like the sound of that. I'd better go, sir.",
"You see, captain, after the campaign against the pirates, there are only two warships left in service, and these are too valuable to spare on such a venture. In light of this, I hearby issue the order to commandeer and arm private vessels wherever needed for the defense of our lands\nI am sorry, captain, but your ship will not be exempt from this order.",
"What? I'll not let you commandeer my ship!",
"Ah, yes...yes.... So what kind of ships were used to lay siege to the fort? What kind of arms did they have? How many soldiers?",
"I counted five ships...  a 24-gun brig, a 20-gun schooner.... The rest of the ships were obscured by the fog.",
"Dear ",
", to my regret, I can't let you go. I must commandeer your vessel and set it against these invaders.",
"Excuse me, sir, I didn't quite hear what you said...",
"If you resist, captain, I'll have to confiscate your ship\nTry to understand that I have no alternative.",
"Well, then, let me offer you an alternative - my ship and I are at your service.",
"You're going to force me? Go ahead and try it!",
"Your information is not a great help, captain. That's unfortunate, because your situation is not enviable. I am going to tell you something anyway, ",
".",
"Tell me something? Interesting...I am all ears, sir",
"An excellent decision, Captain ",
". I am glad we have found a resolution that suits us both. Now, to your task. It seems to me that instead of pressing you into the service of the army, it would be better if you\nacted alone.",
"What do you mean, sir?",
"I'll ignore your insolence for now, captain. But keep in mind, there is a loaded gun in my desk, and there are guards outside the door. Now let me continue...",
" In that case, I'd like to captain my ship myself! Let me sail her for you, sir!",
"As a new face in these waters, my hope is that you may be the key to securing more information about the French forces\nFrom the neighboring colony on the island, you can cross through the jungle and penetrate the walls of the city, and there discover more from the local citizens.\nPerhaps you'd even be able to eavesdrop on the French troops themselves.",
"You want me to sneak into the captured city and find out about the French plans for the colony?",
"And what about the payment, sir?",
"Yes.... A bold plan if I say so myself. If successful, perhaps we'll know where to expect any new attack, and more important, how to free our colony.",
"I understand. All the best to you, sir.",
"By the way, perhaps you could advance part of the payment before I get underway?",
"If you are in need of money, captain, here's 1000 gold. But spend it on getting the ship ready for the trip. Keep in mind, that I am going to deduct this money from your final payment.",
"Thank you, sir.",
"Unfortunately, Captain ",
", I can't pay you in advance - our funds must be spent on building a squadron and making the fort ready for a possible military campaign.",
"How inspiring.",
"I assure you, captain, you'll be compensated. But don't try to fool me. If you try to slip away from your duties, \nI'll announce that you are a pirate, and Captain Tomilson's squadron will hunt you 'til the end of your days.",
"If there is anything left of it after the battle with the French!",
"Hmm.... Our conversation has gone a bit awry. Remember, your task is to retrieve information about the French plans for Oxbay\nTalk with locals, go to the tavern - it's sure to be intact and open, I'm certain the French don't mind resting after the battle.\nDo what you can to find out about the plans of the French command\nBelieve me, in this case I'll be quite generous with my reward. Good luck, ",
"Goodbye, sir.",
"Listen, ",
", think of it as a necessary evil. In the end, you should feel fortunate\nYou've been accepted in the service of the Crown, a position many are longing to enjoy. Besides, I am known to be generous to my captains!",
"I hope to witness that generosity soon.",
"Hmm.... Congratulations on your return, captain. Please make your report.",
"The citizens of Oxbay have no love for their captors.",
"And did you manage to find out about what this invasion means for future French plans?",
"They are using Oxbay as a stepping stone for an assault on Redmond. The squadron that sits off Oxbay is awaiting ammunition, planned to arrive from Falaise de Fleur aboard a cargo ship. Once they are re-supplied, they are going to set sail and attack Redmond.",
"This information is invaluable. You've proved your worth. Thank you for your service, ",
". Here is 3000 gold as payment.",
"Thank you, sir.",
"Now, in light of this news, your next task is to ensure that ammunition does not reach Oxbay. When we finally meet the French in battle, the less gunpowder they have, the better.",
"You want me to sink the barque?",
"I'll leave the method up to you, captain. Board it, sink it... that's your decision. The main thing is to keep the French from getting that ammunition.",
"And what of its escort? It may prove too much for my ship.",
"Yes. It's sure to have an escort. For sure, ",
".",
"Agreed. But, ",
", perhaps there's a way to use that to our advantage.\nSince you've proven you have the ability to slip into hostile territory, and keep your wits about you. You should set sail for Falaise de Fleur. With a bit of wit and a few well-placed questions, maybe you'll be able take care of the escort before it sets sail...",
"Sounds doubtful...but I'll try.",
"Good, ",
", but don't forget to address me properly.",
"We freebooters aren't used to such formalities...",
"Then remember that as long as you serve me, you serve the Crown. Be mindful of this, captain.",
"Yes, sir.",
"I understand you managed to squeeze the life out of the French squadron?",
"Absolutely, sir.",
"After you set sail, I sent another captain to Oxbay. She managed to discover a large cave on the island near a secluded beach\nI intend to land a garrison of soldiers and hide them in this cave. Once they're in place, I will use these soldiers to free the city as we make a coordinated attack from the sea and land.",
"A reasonable plan, but I doubt that there is enough room on my ship for an entire detachment.",
"No need, captain. I've already seen to the transport. Your task will be to guard the landing ship along its route. The sloop 'Albion' commanded by Captain ",
"Ewan Glover",
"Ewan Glover",
", is anchored in port. ",
"Ewan Glover",
" will wait for you at the town gates.",
"I see. Then, I suppose I shall take your leave...",
"Wait, I'm not finished. You have to escort the 'Albion' sloop to the harbor of Greenford on Oxbay\nA local man, loyal to the Crown, will show you the way to the cave. After that, once again you'll infiltrate Oxbay, and seek out one of our agents concealed in the town.",
"That's a lot to remember. So what am I to do when I reach the agent?",
"He has some very important information. That's why you must do your best to make sure he survives and can convey that important information to us.",
"And the agent's name?",
"Counterspy",
". He has made contacts with the local citizens. If you can't find him straight away, ask around. But do so discreetly.",
"As you wish. Now, when may I expect payment for my last mission?",
"Don't worry, ",
", here is your gold.",
"Nice to hear that, sir.",
"Now you can go, captain. I'm looking forward to your next report.",
"Goodbye, sir.",
"Well, Captain ",
"..., I had thought better of you. But what's done is done. At least part of the task is completed.",
"But...",
"Congratulations, captain. Honestly, I can't tell you what a relief it has been since I took you into my service.",
"Thank you, sir",
"I am not interested in your explanations, captain. I heard your report from ",
"Counterspy",
" and he explained what happened. I am just disappointed that because of your failure, there will be more blood lost in this war.",
"I am sorry, ",
", I did my best.",
"... Well. These things do happen. After all, thanks to you, we've had the opportunity to rebuild our squadron.",
"So what's is my next task?",
"You're going to participate in the assault of Oxbay as part of our squadron. It goes without saying you need to prepare\nI hope this will be enough for you. And, I have deducted a portion of your payment due to the loss of the 'Albion'.",
"When are we going to set sail?",
"Soon. For now, do whatever you need to in the city, and when the time comes, you'll be notified. And get some rest and relax. Every captain should have a hearty evening in the tavern after a sail.",
"Far from it, but in your words there is a kernel of truth.",
"That's not important. My messenger will find you. Good luck, captain.",
"Farewell.",
"counterspy",
" has just informed me of your exploits. And ",
"Ewan Glover",
"Ewan Glover",
" seemed quite satisfied with your cruising together.",
"Hmm.... I can't think of any exploits.",
"Ha. You're too modest. Well, here is your reward. I suggest you make your vessel seaworthy. You'll have to set sail again very soon.",
"And what kind of mission will it be this time?",
"The siege of Oxbay. You'll join our squadron which is going to free the island.",
"And when will the squadron set sail?",
"Soon. For now, do whatever you need to in the city, and when the time comes, you'll be notified. And get some rest and relax, every captain should have a hearty evening in the tavern after a sail. I'll send a messenger for you there.",
"All right. I'll take my leave now.",
"Ah?! What?! What are you doing here?! ",
"? ",
"Danielle",
"?!!",
"Sorry for interrupting your slumber, dear governor, but we have questions that need answers.",
"What do you mean? Leave now, and I shall consider sparing your life!",
"I think you misunderstand your position, governor, ",
". You no longer give the orders. And if you so much as think without asking, then ",
"Danielle",
", you may find yourself compelled to exercise your elegant fencing techniques.",
"All right, all right, please! Don't be so unruly. Of course I'll answer all your questions... Just sheath your sword, ",
"Danielle",
", please contain him! His look makes me nervous.",
"Be quiet and listen. We know all about your dealings with treasure, and you have much to answer for.",
"Please, you devils, don't hurt me!",
"A flattering assessment, but for now, you should tell us what you know about the idol that opens the doorway to the palace.",
"I'll not tell you scoundrels anything! Guards!",
"Oh no!",
"Danielle",
"! Let's head for our ships!",
"Escaped?! How could it be?",
"They didn't explain. Only that the search for the escapee is still ongoing.",
"Damn! This situation is getting out of hand!",
"Excuse me, sir, but I have good news for you.",
"So, let's hear it, ",
", I haven't got all day?",
"I found a trace of the captain who betrayed England and your trust.",
"Raoul Rheims",
"? It's true. It's not the worst news for today.",
"I am ready to get him now, if it pleases you, sir.",
"Of course, fair winds to you, ",
". And captain...this time you need to bring him back. And keep in mind that until he gets here, he shouldn't speak to anybody, even you. Is that clear?",
"Yes, sir. I'll do everything as you say.",
"! You've been away for such a long time, I've begun to worry about you!",
"I am all right, and I've completed your task.",
"To be honest, I am surprised, I didn't expect positive results from this expedition\nSo, you managed to get the whole collection for me, did you?",
"Yes sir, except one idol. It was bought by some stranger.",
"One idol? Let's have a look at what's missing.",
"Here, see for yourself, sir.",
"It's true, one idol is missing, what a pity.",
"Do you want me to find this one, too, sir?",
"No, don't worry about it, ",
". Though I appreciate that you are ready to help. Instead, I have another task for you. I'll find someone else to send after the idol\nOh, yes, I almost forgot. Here is the payment promised to you.",
"Thank you, sir, and I'm curious to know what mission you have for me.",
"Yes, well.... Several minutes before your arrival, ",
", I was informed that a pirate was captured in Greenford. This particular pirate has always managed to slip from my grasp many times and has annoyed me greatly\nI want you to bring this pirate to me.",
"Sounds simple enough, sir. Can I go?",
"Just a moment, ",
". I appreciate your enthusiasm, but that's not all.",
"Sorry, sir.",
"On your arrival to Greenford, talk to the prison commandant,  ",
"Greenford Prison Commendant",
"Greenford Prison Commendant",
"\nShow him this letter, and he will release the prisoner into your custody\nWhen you return, you'll receive 5000 gold.",
"Understood, sir.",
"I hope your return means that you have completed my task and have delivered the letter to its recipient.",
"Yes, sir. But it was a challenge. The manners of pirates leave much to be desired, but rest assured, he's got the letter.",
"Well done. I hope the next task will also be as skillfully handled, ",
".",
"And what might that job be?",
"Hold on, no need to rush, ",
". First, let me give you your reward.",
"Thank you, sir. It's a pleasure to work with you, sir.",
"And your flattery is always appreciated, ",
". Now, let's get down to business.",
"I'm all ears, sir.",
"Your next endeavor, ",
", is something of a personal matter for me. In my position it can be a bit unethical to use the Imperial forces for one's own business. So I'm especially keen to use you.",
"I am intrigued, sir. As long as you don't want me to take on the French fleet alone.",
"You have a sense of humor about you, ",
", but let's not get distracted from the main subject.",
"I am sorry, sir.",
"A ship was captured by pirates several days ago, '",
"pirate captain 06",
"', headed for Europe from New Light. As it was passing by our colony, pirates struck\nBesides the usual trade goods, there were several golden idols on board. These are rare Incan treasures that I have ordered for my collection\nI managed discover the pirate lord that ordered the capture. His name is ",
"Alistair Garcilaso",
"Alistair Garcilaso",
"\nThey say he and his gang of butchers and thieves are hiding in the Douwesen jungle, but I don't know where exactly\nI need you, ",
", to find them and bring my collection back somehow\nI realize that this is not the easiest task, and that's why I give you 10000 now and an equal amount if the mission is completed successfully\nAs I mentioned, I'm loathe to use army personnel for personal matters. And, the mere thought of landing troops on Douwesen...well, we'd risk a conflict with the Dutch\nYou're my only hope.",
"Finding men who don't wish to be found is hardly an easy task, but I think I serve you well, and this is a generous sum, indeed.",
"Well, if you accomplish this, it's well worth it, ",
". So, without further adieu, here is your payment. Good luck to you.",
"I'll return as soon as I can, sir.",
"You've returned, ",
", but where is ",
"Raoul Rheims",
"? I don't see him with you.",
"I have failed, sir, I lost the trail in the smuggler's den.",
"You disappoint me, ",
". Such a simple mission, and you couldn't complete it?! I had a higher opinion of you.",
"You have my apologies, sir. However, if I may, I did manage to find out what ",
"Raoul Rheims",
" is to do next. He's going on an expedition.",
"Well, it's not my nature to chastise failure, especially when an earnest effort's been made. But I hope you'll not fail your next mission.",
"Thank you for trusting me, sir. I'll do my best to not let you down again.",
"You're welcome, ",
". By the way, here is the 5000 gold that I promised to give you, although it's not fully deserved.",
"Thank you, sir. Your generosity amazes me.",
"Enough of this, ",
". You needn't flatter me. Now. Let's talk business. I understand you've been to the pirate's nest\nSo, now that you know where to go, I need you to take this letter and deliver it to the pirate lord. He goes by the name ",
"Isenbrandt Jurcksen",
"Isenbrandt Jurcksen",
"\nNow, before you become alarmed, I'm sure you're curious what possible communication I might have for this low devil. You may recall that ",
"Raoul Rheims",
" now knows too much for me to let him escape\nIf you aren't able to catch him, these pirates may. So when are you going to start on your journey?",
"My ship is ready to sail, sir.",
"Perfect. Then set sail immediately. After you've done your duty, return to me for the reward. Is everything clear, ",
"?",
"Yes, sir, I will set sail immediately.",
"Good, no one can disturb us.",
"Go ahead, sir.",
"First, I'd like share joyful news - Oxbay is free\nYou helped us greatly in our quest for victory. Thank you.",
"You're welcome. And perhaps you have something for me next?",
"Of course. I want you to bring me the person who betrayed us and put our colony in such peril! His name is ",
"Raoul Rheims",
"Raoul Rheims",
".",
"If I may ask, what did he do?",
"Inquisitive! I like that. Make no mistake. Rheims is a traitor to the Crown most vile. And a betrayer of his own crew as well. He was carrying out a very important mission when he switched allegiances\nWhen one of his crew warned me of Rheims' betrayal, we were nearly able to prevent this calamity\nSadly, the poor fellow was already at death's door, and he couldn't tell me where Rheims was heading\nWe know they stopped at the pirate encampment to re-supply. You should go to this pirate camp and if ",
"Raoul Rheims",
", is still there, arrest him\nIf he is not found, discover what you can.",
"Understood. However, facing pirates is dangerous. I expect to be well compensated.",
"And you will be. I will pay you 5000 gold now and 5000 when you return with the betrayer.",
"A fair price. I shall be on my way, sir.",
"How is it you're free? What's happened? What of the guards?",
"I'm sorry, but I was jailed unfairly. It wasn't going to be stuck there forever. When I regained my weapon, I only sought my freedom.",
"I am sorry, ",
"! There has been a terrible mistake\nMy soldiers were meant to arrest a French spy\nThey clearly mistook you for the spy.",
"Thanks for apologizing, sir, I wasn't sure I'd ever be free again.",
"I applaud your skill and cunning. It does you honor, but the jailer should be hanged for letting you escape!",
"I am afraid you don't have anybody to hang, sir. He's already been dealt with.",
"The jailer is your affair. Now, if you would kindly explain the reason why I found myself in jail.",
"Sir, I'd like to speak on his behalf. He says he was quite proficient with the guns in his day. I have need of a good gunner, and with your permission, I'd like to take him on.",
"Hmm. I suppose leniency can be considered, ",
", but this jailer serves the colony - I can't just let him go.",
"Then tell me your price for replacing him, sir.",
"1000 gold will be enough.",
"A fair bargain, sir. I accept",
"Ah well. This is more than I was expecting. It will be better if this jailer serves you.",
"Take him, but you may regret it later, I hear he is a drunkard.",
"I'll take your warning into consideration, sir. Now, perhaps you'd like to explain to me why I was arrested.",
"You're too bloodthirsty, but that may be what's required for this world - your hand will never waver with pity.",
"I hope so, sir. Now if you may, please tell me why you had me arrested?",
"A terrible mistake. A terrible mistake. My soldiers were sent to arrest a French spy. My agents assured me that he was in the tavern at that very moment\nIt appears he had already gone, and my soldiers arrested you instead.",
"Well, one mystery is solved. You can imagine my distress when I found myself in that dark scary place.",
"A terrible mistake. A terrible mistake. My soldiers were sent to arrest a spy\nMy agents assured me that he was in the tavern at that very moment\nIt appears he had already gone, and my soldiers arrested you instead.",
"Well, one mystery is solved.",
"Well, now that we are finished with all this nonsense, I'd like you to come with me to my study.\n I have important matters to discuss with you.",
"Of course, sir.",
"Please accept my apologies once again for the actions of my soldiers\nI think this money will prove to you how sorry I am about the incident.",
"Thank you, sir. For my part, I thank you for your kindness to me.",

};