string DLG_TEXT[27] = {
", dear customer, I am ",
", the owner of the local shipyard.",
"I am ",
", captain of the '",
"'.",
", ",
". How may I help you today, ",
"?",
"My ship needs to be repaired.",
"I just want to talk.",
"I should go.",
"Well, it's a pleasure to meet you. My shipyard is at your service then.",
"Great, ",
". Let's see what your yard has to offer.",
"I just want to talk.",
"I should go. Thanks.",
"What exactly do you want to talk about, ",
"?",
"Nothing at the moment.",
"Hmm...do you need anything else, ",
"?",
"Yes, I'd like to use your shipyard's services.",
"Thank you. Farewell!",
"What exactly do you need?",
"Let's see what your yard has to offer.",
"I would like to install fresh guns on my ship.",
"I should go. Thanks.",

};