string DLG_TEXT[22] = {
"What do you want, captain?",
"I'm Captain ",
".",
"I'm  ",
", owner of the '",
"'.",
"What do you have for me, captain?",
"A few goods to sell.",
"Nothing. Goodbye.",
"How can I help you, captain?",
"I want to sell something.",
"You can't. Goodbye.",
"Hm...I'm afraid you're mistaken. Go to the store -- they'll gladly buy what you have.",
"I'm afraid a store can't help me.",
"Thanks for the advice. Goodbye.",
"Is that so?",
"I have something no merchant will buy.",
"Maybe you should finish one piece of business before starting another?",
"I guess you're right.",
"Hmh...maybe I can help you. I'll find you a customer. We'll be waiting for you at the place called ",
".",
"Good. Until then.",

};