string DLG_TEXT[53] = {
"What are you doing here?",
"Relax, I've brought the goods!",
"What do you think? I brought the goods!",
"Look, get out of here! If you ruin the deal, we'll kill you!",
"You dare threaten me?",
"You'll choke on those words, scoundrel!",
"Calm down. I'll be on my way. Goodbye.",
"I suppose you have them in your pockets? Come on, where's your ship and the goods?",
"I wanted to make sure everything was all right first.",
"I didn't want to risk my ship. I wanted to check if everything was all right first.",
"The deal is off!",
"We won't cheat you. Come on, bring your ship, and watch for the coastal patrols.",
"Alright. Wait for me here.",
"What? DO you jest?",
"I'm completely serious.",
"You can't fool us like that! You'll pay for this with your head!",
"I doubt it!",
"You'll regret this!",
"Go howl somewhere else, scurvy dogs!",
"You'll regret this!",
"Go howl somewhere else, scurvy dogs!",
"Aha, good. So...",
". The price is ",
". So it will be ",
" total. Deal?",
"Deal.",
"No deal. I'll look for another buyer.",
"What are you doing here? You don't have anything to sell! This isn't what we want. Everything you've got we can buy in town!",
"No luck.",
"Glad to hear that. Shall we continue? ",
". The price is ",
". So it will be ",
" total. Deal?",
"Deal.",
"No deal. I'll look for another buyer.",
"Well...",
". The price is ",
". So it will be ",
" total. Good enough?",
"Sure.",
"Nah. I think I'll go look for another buyer.",
"And finally...",
". The price is ",
". ",
" total. That all right?",
"Yep.",
"No deal. I'll look for another buyer.",
"No luck? You arrange a meeting and then just say 'no luck'? Get out of here. You'd be wise to honor your deals in the future!",
"You were expecting honor among thieves? That's original.",
"The total sum is ",
" gold. Your money, our goods!",
"Deal!",
"Too much! No deal!",

};