string DLG_TEXT[92] = {
"What are you doing in my house, ",
"?",
"Oh, I am so sorry, I just called in to see who lives here and I am already leaving.",
"That's no business of yours, old hag. If you say one more word, you'll regret that you came into the world. Though actually...I just don't want to make get hands dirty.",
"Hello, ",
". ",
"Sabine Matton",
" has already told me about you.",
"I am very glad to meet you. As I understand you are ",
" and ",
"Sabine Matton",
" is your god-daughter?",
"I know what you mean when you say she 'told' you. She likes to blather more than any other person I know. Are you her godmother?",
"You know, I think that there is something wrong. Perhaps ",
"Sabine Matton",
" really told you that I was supposed to take her to you, but I was given  different instructions from her father.",
"Shut up, you, old hag. ",
"Sabine Matton",
" belongs to me and I am going to decide what to do with her.",
"What happened with my girl?! What did you do with her, parasite?!",
"Don't worry so much. Your daughter is on my ship, and she is all right.",
"Shut up you, hag. Don't annoy me with your crying. Your girl is alive, but it's my business what I do with her.",
"Ah, you heartless beast! What do you demand for her release? Money?!",
"You are quite perceptive. I really want to hold her for ransom.",
"You are quite right, of course. The jingle of gold coins has always been music to my ears.",
"Oh, I am sorry! It's good that you reminded me! I wanted to let her go a long time ago.",
"That ",
"Sabine Matton",
" and you have bored me to death with your moaning. Take the girl, and good riddance.",
"I don't have anything to talk about with you.",
"You still can't calm down? I am going to keep the girl with me for now, and then we'll see.",
"How much do you want, pirate, to set my girl free?!",
"How much can you offer, seigniorita?",
"What are you talking about? Tell me your price, and then we'll see.",
"I can give you all I have - 5000 gold.",
"You've got a deal, dear. Give me the money, and I'll set my ‘passenger' free.",
"Ah, you old hag, look what a hard bargain you drive! Well, give me the gold and I'll let your girl go.",
"Fine, I think I'll take the money but ",
"Sabine Matton",
" will stay with me, too.",
"Ha! All I have to do is take your money, and keep the girl with me!",
"Here is your gold, and I hope you choke on them!",
"Goodness, how rude! Anyway, I'll tell my people to free your daughter. Goodbye.",
"You are not the first one to wish that on me. Just give me your money, and wait for your girl to come.",
"No, you can't do this to us! No, please, ",
", take pity on us!",
"Don't worry so much, or you may spoil your digestion.... Oh, all right. Give me your money, and bed me goodbye.",
"Why not? You can't stop me. And if you take it into your head to call for the guards, then it will go very hard for your darling daughter.",
"Take your money and go. You are not a man! You are a monster!",
"Good bye, seigniorita.",
"Oh, please quit your squawking.",
"Oh, you are so kind, ",
"! I see that you've got a kind heart, although you play the part of the cruel pirate.",
"You are quite wrong, dear. I am just desperately tired of your daughter and her whims. And how long can any man stand to sail cooped up with the same girl?",
"You don't understand at all, old woman. Your daughter just wore me out with all her whims, and the modest pleasure I derive from her company can't compare with the endless annoyance she causes me.",
"I am afraid that you are mistaken, seigniorita. I am a pirate...",
"Come on, I am a real pirate. Don't think better of people than they really deserve.",
"I see now that I actually was too kind to you. You are a genuine pirate and murderer!",
"I am gratified that you finally esteem me for my true worth, but I really do have other engagements, so I'll have to cut this conversation short.",
"I am well accustomed to such words...but if you don't want anything to happen to you or your girl, I suggest you shut up!",
"I don't care what you think. I am an old woman, and I can see the truth.",
"As you wish, seigniorita, and now let me take my leave of you.",
"Well, I'm please you can see the truth, old woman, but I really must go.",
"Why?",
"Don't worry. I'll take your god-daughter to a safe place.",
"Easy, now. I am the one who decides what to do with the girl, and trust me, I'll find a use for her.",
"Well, ",
", probably",
"Sabine Matton",
" didn't know about her father's intentions. I can tell that you are a worthy man, and I give my permissions for my god-daughter to sail with you.",
"Thanks for trusting me...and now I must take my leave of you.",
"Actually I was supposed to bring your god-daughter to you...so here she is, and let me take my leave of you.",
"I wish you smooth sailing, ",
"!",
"Farewell.",
"What?! How dare you to say such things! You are a rascal, ",
"!",
"I am not going to listen to your insults. I am going to take the girl now and leave. If you try to stop me or hinder me then, I swear to God that I'll cut your throat!",
"No, only not my girl, please, let her go!",
"Be gone, old lady.",
"Yes, you are not mistaken. I am very grateful to you for what you've done for us.",
"Never mind. By the way ",
"Arnaud Matton",
" asked me to give you this letter.",
"Thanks, I leave it to your judgment. I'll be fine without it, but if you have a little gold to spare, I wouldn't mind.",
"Thank you once again. Wait a second! I'll dash off a couple of lines to",
"Arnaud Matton",
", and if it's not too much trouble, please deliver this letter to him.",
"Goodbye. I hope everything goes well with you.",
"Farewell.",
"Certainly, certainly! Here is all I have. There's 800 gold there, and I only hope it will be enough to cover your expenses.",
"Oh. Yes. Yes, indeed. And, by the way, I have a paper for you.",

};