string DLG_TEXT[61] = {
"Captain, you're still here? ",
"Mateus Santos",
" won't be in that tavern forever.",
"...",
"What can I do for you?",
"Is your name ",
"Vito Leone",
"Vito Leone",
"?",
"You've done well, captain! Here is your 10000 gold. If you ever need to...plan a funeral for someone, let us know - we'll provide the best service at a decent discount.",
"Thank you, and farewell.",
"Yes, that's me. And you must be captain ",
". I've heard a lot about your success performing certain...jobs.",
"You arrived a week ago, and you already know who I am and what I've been doing? Why?",
"In my line of work, lack of information is more dangerous than any bullet or sword. I see that you're surprised - ",
"Mateus Santos",
" hasn't told you who I am, right?",
"You do know everything, don't you? Yes, ",
"Mateus Santos",
" told me that you are a messenger, and the news you have brought is very dangerous.",
"A messenger? Quite the joker, that ",
"Mateus Santos",
"of yours. Captain, I am no messenger. I represent an organization that a Philistine might call the assassin guild. And I come not to bring news, but to sentence an imposter.",
"Is that so? An who is this imposter?",
"Our esteemed mister ",
"Mateus Santos",
", as you might have guessed. Two years ago, he appeared out of nowhere, killed the head of our organization's local branch, and took his place.",
"...",
"In theory, we could shut our eyes to this impudence, if he showed us some respect. But he not only killed our representative, he also stopped sharing profit with the guild. This, as you can understand, we could not forgive.",
"...",
"We tried to get rid of ",
"Mateus Santos",
" with the help of local mercenaries, but he is a resourceful man and has managed to thwart all attempts on his life. This is why the guild has decided to send its own man to deal with the problem.",
"And ",
"Mateus Santos",
" has promised me a hefty reward for the head of his would-be assassin - you.",
"Of course he did! Now that things are really serious, he understands who he's dealing with, and is afraid. But, my death won't change anything now - ",
"Mateus Santos",
" is going to die, very soon.",
"So, this won't stop me from killing you and getting my reward.",
"Oh, you could kill me...but you'll likely receive a bullet as reward for your efforts. Do you seriously think that ",
"Mateus Santos",
" will let you live after talking to me? I'm afraid this is your last job, captain.",
"Hmm...but if it is as you describe, what do you suggest?",
"Do you think me a fool? You want to live, and will say anything to save yourself. I'll kill you and get my reward!",
"I see two options for you in this situation. The first, let me live and go your own way. The second, help me get rid of ",
"Mateus Santos",
". The latter option, aside from saving your life, will earn you a considerable amount of money.",
"Hmm...I've no objection to money... or safety, for that matter. But how are you planning to kill ",
"Mateus Santos",
"? He is well-guarded, to say the least...",
"No way, deal with ",
"Mateus Santos",
" on your own! I'm out of this. Goodbye.",
"Do you think me a fool? You want to live, and will say anything to save yourself. I'll kill you and get my reward!",
"This I take upon myself. I will lure him to the tavern on Isla Muelle under the pretext of negotiations. He will come alone; don't worry. All you will have to do is go upstairs in the tavern and finish him. Then get back here, and I'll pay you your 10000 gold.",
"Deal. But if you have lied to me, I'll follow you to the ends of the earth...and when I do, you'll be sorry! Remember this.",
"No way, deal with ",
"Mateus Santos",
" on your own! I'll have no part in this. Goodbye.",
"Do you think me a fool? You want to live, and will say anything to save yourself. I'll kill you and get my reward!",

};